
extern zend_class_entry *zendframework_stdlib_extractor_extractioninterface_ce;

ZEPHIR_INIT_CLASS(ZendFramework_Stdlib_Extractor_ExtractionInterface);

ZEND_BEGIN_ARG_INFO_EX(arginfo_zendframework_stdlib_extractor_extractioninterface_extract, 0, 0, 1)
	ZEND_ARG_INFO(0, object)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(zendframework_stdlib_extractor_extractioninterface_method_entry) {
	PHP_ABSTRACT_ME(ZendFramework_Stdlib_Extractor_ExtractionInterface, extract, arginfo_zendframework_stdlib_extractor_extractioninterface_extract)
  PHP_FE_END
};
