
extern zend_class_entry *zendframework_servicemanager_abstractfactoryinterface_ce;

ZEPHIR_INIT_CLASS(ZendFramework_ServiceManager_AbstractFactoryInterface);

ZEND_BEGIN_ARG_INFO_EX(arginfo_zendframework_servicemanager_abstractfactoryinterface_cancreateservicewithname, 0, 0, 3)
	ZEND_ARG_OBJ_INFO(0, serviceLocator, ZendFramework\\ServiceManager\\ServiceLocatorInterface, 0)
	ZEND_ARG_INFO(0, name)
	ZEND_ARG_INFO(0, requestedName)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_INFO_EX(arginfo_zendframework_servicemanager_abstractfactoryinterface_createservicewithname, 0, 0, 3)
	ZEND_ARG_OBJ_INFO(0, serviceLocator, ZendFramework\\ServiceManager\\ServiceLocatorInterface, 0)
	ZEND_ARG_INFO(0, name)
	ZEND_ARG_INFO(0, requestedName)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(zendframework_servicemanager_abstractfactoryinterface_method_entry) {
	PHP_ABSTRACT_ME(ZendFramework_ServiceManager_AbstractFactoryInterface, canCreateServiceWithName, arginfo_zendframework_servicemanager_abstractfactoryinterface_cancreateservicewithname)
	PHP_ABSTRACT_ME(ZendFramework_ServiceManager_AbstractFactoryInterface, createServiceWithName, arginfo_zendframework_servicemanager_abstractfactoryinterface_createservicewithname)
  PHP_FE_END
};
