
extern zend_class_entry *zendframework_servicemanager_configinterface_ce;

ZEPHIR_INIT_CLASS(ZendFramework_ServiceManager_ConfigInterface);

ZEND_BEGIN_ARG_INFO_EX(arginfo_zendframework_servicemanager_configinterface_configureservicemanager, 0, 0, 1)
	ZEND_ARG_OBJ_INFO(0, serviceManager, ZendFramework\\ServiceManager\\ServiceManager, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(zendframework_servicemanager_configinterface_method_entry) {
	PHP_ABSTRACT_ME(ZendFramework_ServiceManager_ConfigInterface, configureServiceManager, arginfo_zendframework_servicemanager_configinterface_configureservicemanager)
  PHP_FE_END
};
