
extern zend_class_entry *zendframework_servicemanager_servicemanagerawareinterface_ce;

ZEPHIR_INIT_CLASS(ZendFramework_ServiceManager_ServiceManagerAwareInterface);

ZEND_BEGIN_ARG_INFO_EX(arginfo_zendframework_servicemanager_servicemanagerawareinterface_setservicemanager, 0, 0, 1)
	ZEND_ARG_INFO(0, serviceManager)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(zendframework_servicemanager_servicemanagerawareinterface_method_entry) {
	PHP_ABSTRACT_ME(ZendFramework_ServiceManager_ServiceManagerAwareInterface, setServiceManager, arginfo_zendframework_servicemanager_servicemanagerawareinterface_setservicemanager)
  PHP_FE_END
};
