
extern zend_class_entry *zendframework_db_adapter_driver_driverinterface_ce;

ZEPHIR_INIT_CLASS(ZendFramework_Db_Adapter_Driver_DriverInterface);

ZEND_BEGIN_ARG_INFO_EX(arginfo_zendframework_db_adapter_driver_driverinterface_getdatabaseplatformname, 0, 0, 0)
	ZEND_ARG_INFO(0, nameFormat)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_INFO_EX(arginfo_zendframework_db_adapter_driver_driverinterface_createstatement, 0, 0, 0)
	ZEND_ARG_INFO(0, sqlOrResource)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_INFO_EX(arginfo_zendframework_db_adapter_driver_driverinterface_createresult, 0, 0, 1)
	ZEND_ARG_INFO(0, resource)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_INFO_EX(arginfo_zendframework_db_adapter_driver_driverinterface_formatparametername, 0, 0, 1)
	ZEND_ARG_INFO(0, name)
	ZEND_ARG_INFO(0, type)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(zendframework_db_adapter_driver_driverinterface_method_entry) {
	PHP_ABSTRACT_ME(ZendFramework_Db_Adapter_Driver_DriverInterface, getDatabasePlatformName, arginfo_zendframework_db_adapter_driver_driverinterface_getdatabaseplatformname)
	PHP_ABSTRACT_ME(ZendFramework_Db_Adapter_Driver_DriverInterface, checkEnvironment, NULL)
	PHP_ABSTRACT_ME(ZendFramework_Db_Adapter_Driver_DriverInterface, getConnection, NULL)
	PHP_ABSTRACT_ME(ZendFramework_Db_Adapter_Driver_DriverInterface, createStatement, arginfo_zendframework_db_adapter_driver_driverinterface_createstatement)
	PHP_ABSTRACT_ME(ZendFramework_Db_Adapter_Driver_DriverInterface, createResult, arginfo_zendframework_db_adapter_driver_driverinterface_createresult)
	PHP_ABSTRACT_ME(ZendFramework_Db_Adapter_Driver_DriverInterface, getPrepareType, NULL)
	PHP_ABSTRACT_ME(ZendFramework_Db_Adapter_Driver_DriverInterface, formatParameterName, arginfo_zendframework_db_adapter_driver_driverinterface_formatparametername)
	PHP_ABSTRACT_ME(ZendFramework_Db_Adapter_Driver_DriverInterface, getLastGeneratedValue, NULL)
  PHP_FE_END
};
