
extern zend_class_entry *zendframework_db_adapter_driver_statementinterface_ce;

ZEPHIR_INIT_CLASS(ZendFramework_Db_Adapter_Driver_StatementInterface);

ZEND_BEGIN_ARG_INFO_EX(arginfo_zendframework_db_adapter_driver_statementinterface_prepare, 0, 0, 0)
	ZEND_ARG_INFO(0, sql)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_INFO_EX(arginfo_zendframework_db_adapter_driver_statementinterface_execute, 0, 0, 0)
	ZEND_ARG_INFO(0, parameters)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(zendframework_db_adapter_driver_statementinterface_method_entry) {
	PHP_ABSTRACT_ME(ZendFramework_Db_Adapter_Driver_StatementInterface, getResource, NULL)
	PHP_ABSTRACT_ME(ZendFramework_Db_Adapter_Driver_StatementInterface, prepare, arginfo_zendframework_db_adapter_driver_statementinterface_prepare)
	PHP_ABSTRACT_ME(ZendFramework_Db_Adapter_Driver_StatementInterface, isPrepared, NULL)
	PHP_ABSTRACT_ME(ZendFramework_Db_Adapter_Driver_StatementInterface, execute, arginfo_zendframework_db_adapter_driver_statementinterface_execute)
  PHP_FE_END
};
