
extern zend_class_entry *zendframework_mail_transport_transportinterface_ce;

ZEPHIR_INIT_CLASS(ZendFramework_Mail_Transport_TransportInterface);

ZEND_BEGIN_ARG_INFO_EX(arginfo_zendframework_mail_transport_transportinterface_send, 0, 0, 1)
	ZEND_ARG_INFO(0, message)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(zendframework_mail_transport_transportinterface_method_entry) {
	PHP_ABSTRACT_ME(ZendFramework_Mail_Transport_TransportInterface, send, arginfo_zendframework_mail_transport_transportinterface_send)
  PHP_FE_END
};
