
extern zend_class_entry *zendframework_permissions_rbac_abstractiterator_ce;

ZEPHIR_INIT_CLASS(ZendFramework_Permissions_Rbac_AbstractIterator);

PHP_METHOD(ZendFramework_Permissions_Rbac_AbstractIterator, current);
PHP_METHOD(ZendFramework_Permissions_Rbac_AbstractIterator, next);
PHP_METHOD(ZendFramework_Permissions_Rbac_AbstractIterator, key);
PHP_METHOD(ZendFramework_Permissions_Rbac_AbstractIterator, valid);
PHP_METHOD(ZendFramework_Permissions_Rbac_AbstractIterator, rewind);
PHP_METHOD(ZendFramework_Permissions_Rbac_AbstractIterator, hasChildren);
PHP_METHOD(ZendFramework_Permissions_Rbac_AbstractIterator, getChildren);
PHP_METHOD(ZendFramework_Permissions_Rbac_AbstractIterator, __construct);

ZEPHIR_INIT_FUNCS(zendframework_permissions_rbac_abstractiterator_method_entry) {
	PHP_ME(ZendFramework_Permissions_Rbac_AbstractIterator, current, NULL, ZEND_ACC_PUBLIC)
	PHP_ME(ZendFramework_Permissions_Rbac_AbstractIterator, next, NULL, ZEND_ACC_PUBLIC)
	PHP_ME(ZendFramework_Permissions_Rbac_AbstractIterator, key, NULL, ZEND_ACC_PUBLIC)
	PHP_ME(ZendFramework_Permissions_Rbac_AbstractIterator, valid, NULL, ZEND_ACC_PUBLIC)
	PHP_ME(ZendFramework_Permissions_Rbac_AbstractIterator, rewind, NULL, ZEND_ACC_PUBLIC)
	PHP_ME(ZendFramework_Permissions_Rbac_AbstractIterator, hasChildren, NULL, ZEND_ACC_PUBLIC)
	PHP_ME(ZendFramework_Permissions_Rbac_AbstractIterator, getChildren, NULL, ZEND_ACC_PUBLIC)
	PHP_ME(ZendFramework_Permissions_Rbac_AbstractIterator, __construct, NULL, ZEND_ACC_PUBLIC|ZEND_ACC_CTOR)
  PHP_FE_END
};
