
extern zend_class_entry *zendframework_permissions_rbac_assertioninterface_ce;

ZEPHIR_INIT_CLASS(ZendFramework_Permissions_Rbac_AssertionInterface);

ZEND_BEGIN_ARG_INFO_EX(arginfo_zendframework_permissions_rbac_assertioninterface_assert, 0, 0, 1)
	ZEND_ARG_INFO(0, rbac)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(zendframework_permissions_rbac_assertioninterface_method_entry) {
	PHP_ABSTRACT_ME(ZendFramework_Permissions_Rbac_AssertionInterface, assert, arginfo_zendframework_permissions_rbac_assertioninterface_assert)
  PHP_FE_END
};
