
extern zend_class_entry *zendframework_eventmanager_filter_filterinterface_ce;

ZEPHIR_INIT_CLASS(ZendFramework_EventManager_Filter_FilterInterface);

ZEND_BEGIN_ARG_INFO_EX(arginfo_zendframework_eventmanager_filter_filterinterface_run, 0, 0, 1)
	ZEND_ARG_INFO(0, context)
	ZEND_ARG_ARRAY_INFO(0, params, 1)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_INFO_EX(arginfo_zendframework_eventmanager_filter_filterinterface_attach, 0, 0, 1)
	ZEND_ARG_INFO(0, callback)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_INFO_EX(arginfo_zendframework_eventmanager_filter_filterinterface_detach, 0, 0, 1)
	ZEND_ARG_OBJ_INFO(0, filter, Zend\\Stdlib\\CallbackHandler, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(zendframework_eventmanager_filter_filterinterface_method_entry) {
	PHP_ABSTRACT_ME(ZendFramework_EventManager_Filter_FilterInterface, run, arginfo_zendframework_eventmanager_filter_filterinterface_run)
	PHP_ABSTRACT_ME(ZendFramework_EventManager_Filter_FilterInterface, attach, arginfo_zendframework_eventmanager_filter_filterinterface_attach)
	PHP_ABSTRACT_ME(ZendFramework_EventManager_Filter_FilterInterface, detach, arginfo_zendframework_eventmanager_filter_filterinterface_detach)
	PHP_ABSTRACT_ME(ZendFramework_EventManager_Filter_FilterInterface, getFilters, NULL)
	PHP_ABSTRACT_ME(ZendFramework_EventManager_Filter_FilterInterface, clearFilters, NULL)
	PHP_ABSTRACT_ME(ZendFramework_EventManager_Filter_FilterInterface, getResponses, NULL)
  PHP_FE_END
};
