
extern zend_class_entry *zendframework_db_adapter_profiler_profilerinterface_ce;

ZEPHIR_INIT_CLASS(ZendFramework_Db_Adapter_Profiler_ProfilerInterface);

ZEND_BEGIN_ARG_INFO_EX(arginfo_zendframework_db_adapter_profiler_profilerinterface_profilerstart, 0, 0, 1)
	ZEND_ARG_INFO(0, target)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(zendframework_db_adapter_profiler_profilerinterface_method_entry) {
	PHP_ABSTRACT_ME(ZendFramework_Db_Adapter_Profiler_ProfilerInterface, profilerStart, arginfo_zendframework_db_adapter_profiler_profilerinterface_profilerstart)
	PHP_ABSTRACT_ME(ZendFramework_Db_Adapter_Profiler_ProfilerInterface, profilerFinish, NULL)
  PHP_FE_END
};
