
extern zend_class_entry *zendframework_db_adapter_profiler_profilerawareinterface_ce;

ZEPHIR_INIT_CLASS(ZendFramework_Db_Adapter_Profiler_ProfilerAwareInterface);

ZEND_BEGIN_ARG_INFO_EX(arginfo_zendframework_db_adapter_profiler_profilerawareinterface_setprofiler, 0, 0, 1)
	ZEND_ARG_OBJ_INFO(0, profiler, ZendFramework\\Db\\Adapter\\Profiler\\ProfilerInterface, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(zendframework_db_adapter_profiler_profilerawareinterface_method_entry) {
	PHP_ABSTRACT_ME(ZendFramework_Db_Adapter_Profiler_ProfilerAwareInterface, setProfiler, arginfo_zendframework_db_adapter_profiler_profilerawareinterface_setprofiler)
  PHP_FE_END
};
