
extern zend_class_entry *zendframework_mail_storage_message_messageinterface_ce;

ZEPHIR_INIT_CLASS(ZendFramework_Mail_Storage_Message_MessageInterface);

ZEND_BEGIN_ARG_INFO_EX(arginfo_zendframework_mail_storage_message_messageinterface_hasflag, 0, 0, 1)
	ZEND_ARG_INFO(0, flag)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(zendframework_mail_storage_message_messageinterface_method_entry) {
	PHP_ABSTRACT_ME(ZendFramework_Mail_Storage_Message_MessageInterface, getTopLines, NULL)
	PHP_ABSTRACT_ME(ZendFramework_Mail_Storage_Message_MessageInterface, hasFlag, arginfo_zendframework_mail_storage_message_messageinterface_hasflag)
	PHP_ABSTRACT_ME(ZendFramework_Mail_Storage_Message_MessageInterface, getFlags, NULL)
  PHP_FE_END
};
