
extern zend_class_entry *zendframework_permissions_acl_role_roleinterface_ce;

ZEPHIR_INIT_CLASS(ZendFramework_Permissions_Acl_Role_RoleInterface);

ZEPHIR_INIT_FUNCS(zendframework_permissions_acl_role_roleinterface_method_entry) {
	PHP_ABSTRACT_ME(ZendFramework_Permissions_Acl_Role_RoleInterface, getRoleId, NULL)
  PHP_FE_END
};
