
extern zend_class_entry *zendframework_validator_barcode_adapterinterface_ce;

ZEPHIR_INIT_CLASS(ZendFramework_Validator_Barcode_AdapterInterface);

ZEND_BEGIN_ARG_INFO_EX(arginfo_zendframework_validator_barcode_adapterinterface_hasvalidlength, 0, 0, 1)
	ZEND_ARG_INFO(0, value)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_INFO_EX(arginfo_zendframework_validator_barcode_adapterinterface_hasvalidcharacters, 0, 0, 1)
	ZEND_ARG_INFO(0, value)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_INFO_EX(arginfo_zendframework_validator_barcode_adapterinterface_hasvalidchecksum, 0, 0, 1)
	ZEND_ARG_INFO(0, value)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_INFO_EX(arginfo_zendframework_validator_barcode_adapterinterface_usechecksum, 0, 0, 0)
	ZEND_ARG_INFO(0, check)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(zendframework_validator_barcode_adapterinterface_method_entry) {
	PHP_ABSTRACT_ME(ZendFramework_Validator_Barcode_AdapterInterface, hasValidLength, arginfo_zendframework_validator_barcode_adapterinterface_hasvalidlength)
	PHP_ABSTRACT_ME(ZendFramework_Validator_Barcode_AdapterInterface, hasValidCharacters, arginfo_zendframework_validator_barcode_adapterinterface_hasvalidcharacters)
	PHP_ABSTRACT_ME(ZendFramework_Validator_Barcode_AdapterInterface, hasValidChecksum, arginfo_zendframework_validator_barcode_adapterinterface_hasvalidchecksum)
	PHP_ABSTRACT_ME(ZendFramework_Validator_Barcode_AdapterInterface, getLength, NULL)
	PHP_ABSTRACT_ME(ZendFramework_Validator_Barcode_AdapterInterface, getCharacters, NULL)
	PHP_ABSTRACT_ME(ZendFramework_Validator_Barcode_AdapterInterface, getChecksum, NULL)
	PHP_ABSTRACT_ME(ZendFramework_Validator_Barcode_AdapterInterface, useChecksum, arginfo_zendframework_validator_barcode_adapterinterface_usechecksum)
  PHP_FE_END
};
