
extern zend_class_entry *zendframework_view_model_clearablemodelinterface_ce;

ZEPHIR_INIT_CLASS(ZendFramework_View_Model_ClearableModelInterface);

ZEPHIR_INIT_FUNCS(zendframework_view_model_clearablemodelinterface_method_entry) {
	PHP_ABSTRACT_ME(ZendFramework_View_Model_ClearableModelInterface, clearChildren, NULL)
	PHP_ABSTRACT_ME(ZendFramework_View_Model_ClearableModelInterface, clearOptions, NULL)
	PHP_ABSTRACT_ME(ZendFramework_View_Model_ClearableModelInterface, clearVariables, NULL)
  PHP_FE_END
};
