
extern zend_class_entry *zendframework_view_model_retrievablechildreninterface_ce;

ZEPHIR_INIT_CLASS(ZendFramework_View_Model_RetrievableChildrenInterface);

ZEND_BEGIN_ARG_INFO_EX(arginfo_zendframework_view_model_retrievablechildreninterface_getchildrenbycaptureto, 0, 0, 1)
	ZEND_ARG_INFO(0, capture)
	ZEND_ARG_INFO(0, recursive)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(zendframework_view_model_retrievablechildreninterface_method_entry) {
	PHP_ABSTRACT_ME(ZendFramework_View_Model_RetrievableChildrenInterface, getChildrenByCaptureTo, arginfo_zendframework_view_model_retrievablechildreninterface_getchildrenbycaptureto)
  PHP_FE_END
};
