
extern zend_class_entry *zendframework_crypt_symmetric_padding_paddinginterface_ce;

ZEPHIR_INIT_CLASS(ZendFramework_Crypt_Symmetric_Padding_PaddingInterface);

ZEND_BEGIN_ARG_INFO_EX(arginfo_zendframework_crypt_symmetric_padding_paddinginterface_pad, 0, 0, 1)
	ZEND_ARG_INFO(0, string)
	ZEND_ARG_INFO(0, blockSize)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_INFO_EX(arginfo_zendframework_crypt_symmetric_padding_paddinginterface_strip, 0, 0, 1)
	ZEND_ARG_INFO(0, string)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(zendframework_crypt_symmetric_padding_paddinginterface_method_entry) {
	PHP_ABSTRACT_ME(ZendFramework_Crypt_Symmetric_Padding_PaddingInterface, pad, arginfo_zendframework_crypt_symmetric_padding_paddinginterface_pad)
	PHP_ABSTRACT_ME(ZendFramework_Crypt_Symmetric_Padding_PaddingInterface, strip, arginfo_zendframework_crypt_symmetric_padding_paddinginterface_strip)
  PHP_FE_END
};
