
extern zend_class_entry *zendframework_inputfilter_inputinterface_ce;

ZEPHIR_INIT_CLASS(ZendFramework_InputFilter_InputInterface);

ZEND_BEGIN_ARG_INFO_EX(arginfo_zendframework_inputfilter_inputinterface_setallowempty, 0, 0, 1)
	ZEND_ARG_INFO(0, allowEmpty)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_INFO_EX(arginfo_zendframework_inputfilter_inputinterface_setbreakonfailure, 0, 0, 1)
	ZEND_ARG_INFO(0, breakOnFailure)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_INFO_EX(arginfo_zendframework_inputfilter_inputinterface_seterrormessage, 0, 0, 1)
	ZEND_ARG_INFO(0, errorMessage)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_INFO_EX(arginfo_zendframework_inputfilter_inputinterface_setfilterchain, 0, 0, 1)
	ZEND_ARG_INFO(0, filterChain)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_INFO_EX(arginfo_zendframework_inputfilter_inputinterface_setname, 0, 0, 1)
	ZEND_ARG_INFO(0, name)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_INFO_EX(arginfo_zendframework_inputfilter_inputinterface_setrequired, 0, 0, 1)
	ZEND_ARG_INFO(0, required)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_INFO_EX(arginfo_zendframework_inputfilter_inputinterface_setvalidatorchain, 0, 0, 1)
	ZEND_ARG_INFO(0, validatorChain)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_INFO_EX(arginfo_zendframework_inputfilter_inputinterface_setvalue, 0, 0, 1)
	ZEND_ARG_INFO(0, value)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_INFO_EX(arginfo_zendframework_inputfilter_inputinterface_merge, 0, 0, 1)
	ZEND_ARG_INFO(0, input)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(zendframework_inputfilter_inputinterface_method_entry) {
	PHP_ABSTRACT_ME(ZendFramework_InputFilter_InputInterface, setAllowEmpty, arginfo_zendframework_inputfilter_inputinterface_setallowempty)
	PHP_ABSTRACT_ME(ZendFramework_InputFilter_InputInterface, setBreakOnFailure, arginfo_zendframework_inputfilter_inputinterface_setbreakonfailure)
	PHP_ABSTRACT_ME(ZendFramework_InputFilter_InputInterface, setErrorMessage, arginfo_zendframework_inputfilter_inputinterface_seterrormessage)
	PHP_ABSTRACT_ME(ZendFramework_InputFilter_InputInterface, setFilterChain, arginfo_zendframework_inputfilter_inputinterface_setfilterchain)
	PHP_ABSTRACT_ME(ZendFramework_InputFilter_InputInterface, setName, arginfo_zendframework_inputfilter_inputinterface_setname)
	PHP_ABSTRACT_ME(ZendFramework_InputFilter_InputInterface, setRequired, arginfo_zendframework_inputfilter_inputinterface_setrequired)
	PHP_ABSTRACT_ME(ZendFramework_InputFilter_InputInterface, setValidatorChain, arginfo_zendframework_inputfilter_inputinterface_setvalidatorchain)
	PHP_ABSTRACT_ME(ZendFramework_InputFilter_InputInterface, setValue, arginfo_zendframework_inputfilter_inputinterface_setvalue)
	PHP_ABSTRACT_ME(ZendFramework_InputFilter_InputInterface, merge, arginfo_zendframework_inputfilter_inputinterface_merge)
	PHP_ABSTRACT_ME(ZendFramework_InputFilter_InputInterface, allowEmpty, NULL)
	PHP_ABSTRACT_ME(ZendFramework_InputFilter_InputInterface, breakOnFailure, NULL)
	PHP_ABSTRACT_ME(ZendFramework_InputFilter_InputInterface, getErrorMessage, NULL)
	PHP_ABSTRACT_ME(ZendFramework_InputFilter_InputInterface, getFilterChain, NULL)
	PHP_ABSTRACT_ME(ZendFramework_InputFilter_InputInterface, getName, NULL)
	PHP_ABSTRACT_ME(ZendFramework_InputFilter_InputInterface, getRawValue, NULL)
	PHP_ABSTRACT_ME(ZendFramework_InputFilter_InputInterface, isRequired, NULL)
	PHP_ABSTRACT_ME(ZendFramework_InputFilter_InputInterface, getValidatorChain, NULL)
	PHP_ABSTRACT_ME(ZendFramework_InputFilter_InputInterface, getValue, NULL)
	PHP_ABSTRACT_ME(ZendFramework_InputFilter_InputInterface, isValid, NULL)
	PHP_ABSTRACT_ME(ZendFramework_InputFilter_InputInterface, getMessages, NULL)
  PHP_FE_END
};
