
extern zend_class_entry *zendframework_xmlrpc_generator_generatorinterface_ce;

ZEPHIR_INIT_CLASS(ZendFramework_XmlRpc_Generator_GeneratorInterface);

ZEND_BEGIN_ARG_INFO_EX(arginfo_zendframework_xmlrpc_generator_generatorinterface_setencoding, 0, 0, 1)
	ZEND_ARG_INFO(0, encoding)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_INFO_EX(arginfo_zendframework_xmlrpc_generator_generatorinterface_openelement, 0, 0, 1)
	ZEND_ARG_INFO(0, name)
	ZEND_ARG_INFO(0, value)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_INFO_EX(arginfo_zendframework_xmlrpc_generator_generatorinterface_closeelement, 0, 0, 1)
	ZEND_ARG_INFO(0, name)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_INFO_EX(arginfo_zendframework_xmlrpc_generator_generatorinterface_stripdeclaration, 0, 0, 1)
	ZEND_ARG_INFO(0, xml)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(zendframework_xmlrpc_generator_generatorinterface_method_entry) {
	PHP_ABSTRACT_ME(ZendFramework_XmlRpc_Generator_GeneratorInterface, getEncoding, NULL)
	PHP_ABSTRACT_ME(ZendFramework_XmlRpc_Generator_GeneratorInterface, setEncoding, arginfo_zendframework_xmlrpc_generator_generatorinterface_setencoding)
	PHP_ABSTRACT_ME(ZendFramework_XmlRpc_Generator_GeneratorInterface, openElement, arginfo_zendframework_xmlrpc_generator_generatorinterface_openelement)
	PHP_ABSTRACT_ME(ZendFramework_XmlRpc_Generator_GeneratorInterface, closeElement, arginfo_zendframework_xmlrpc_generator_generatorinterface_closeelement)
	PHP_ABSTRACT_ME(ZendFramework_XmlRpc_Generator_GeneratorInterface, saveXml, NULL)
	PHP_ABSTRACT_ME(ZendFramework_XmlRpc_Generator_GeneratorInterface, stripDeclaration, arginfo_zendframework_xmlrpc_generator_generatorinterface_stripdeclaration)
	PHP_ABSTRACT_ME(ZendFramework_XmlRpc_Generator_GeneratorInterface, flush, NULL)
	PHP_ABSTRACT_ME(ZendFramework_XmlRpc_Generator_GeneratorInterface, __toString, NULL)
  PHP_FE_END
};
