
extern zend_class_entry *zendframework_code_annotation_parser_parserinterface_ce;

ZEPHIR_INIT_CLASS(ZendFramework_Code_Annotation_Parser_ParserInterface);

ZEND_BEGIN_ARG_INFO_EX(arginfo_zendframework_code_annotation_parser_parserinterface_oncreateannotation, 0, 0, 1)
	ZEND_ARG_OBJ_INFO(0, e, ZendFramework\\EventManager\\EventInterface, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_INFO_EX(arginfo_zendframework_code_annotation_parser_parserinterface_registerannotation, 0, 0, 1)
	ZEND_ARG_INFO(0, annotation)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_INFO_EX(arginfo_zendframework_code_annotation_parser_parserinterface_registerannotations, 0, 0, 1)
	ZEND_ARG_INFO(0, annotations)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(zendframework_code_annotation_parser_parserinterface_method_entry) {
	PHP_ABSTRACT_ME(ZendFramework_Code_Annotation_Parser_ParserInterface, onCreateAnnotation, arginfo_zendframework_code_annotation_parser_parserinterface_oncreateannotation)
	PHP_ABSTRACT_ME(ZendFramework_Code_Annotation_Parser_ParserInterface, registerAnnotation, arginfo_zendframework_code_annotation_parser_parserinterface_registerannotation)
	PHP_ABSTRACT_ME(ZendFramework_Code_Annotation_Parser_ParserInterface, registerAnnotations, arginfo_zendframework_code_annotation_parser_parserinterface_registerannotations)
  PHP_FE_END
};
