
extern zend_class_entry *zendframework_modulemanager_feature_autoloaderproviderinterface_ce;

ZEPHIR_INIT_CLASS(ZendFramework_ModuleManager_Feature_AutoloaderProviderInterface);

ZEPHIR_INIT_FUNCS(zendframework_modulemanager_feature_autoloaderproviderinterface_method_entry) {
	PHP_ABSTRACT_ME(ZendFramework_ModuleManager_Feature_AutoloaderProviderInterface, getAutoloaderConfig, NULL)
  PHP_FE_END
};
