
extern zend_class_entry *zendframework_modulemanager_feature_bootstraplistenerinterface_ce;

ZEPHIR_INIT_CLASS(ZendFramework_ModuleManager_Feature_BootstrapListenerInterface);

ZEND_BEGIN_ARG_INFO_EX(arginfo_zendframework_modulemanager_feature_bootstraplistenerinterface_onbootstrap, 0, 0, 1)
	ZEND_ARG_OBJ_INFO(0, e, ZendFramework\\EventManager\\EventInterface, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(zendframework_modulemanager_feature_bootstraplistenerinterface_method_entry) {
	PHP_ABSTRACT_ME(ZendFramework_ModuleManager_Feature_BootstrapListenerInterface, onBootstrap, arginfo_zendframework_modulemanager_feature_bootstraplistenerinterface_onbootstrap)
  PHP_FE_END
};
