
extern zend_class_entry *zendframework_modulemanager_feature_consolebannerproviderinterface_ce;

ZEPHIR_INIT_CLASS(ZendFramework_ModuleManager_Feature_ConsoleBannerProviderInterface);

ZEND_BEGIN_ARG_INFO_EX(arginfo_zendframework_modulemanager_feature_consolebannerproviderinterface_getconsolebanner, 0, 0, 1)
	ZEND_ARG_OBJ_INFO(0, console, ZendFramework\\Console\\Adapter\\AdapterInterface, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(zendframework_modulemanager_feature_consolebannerproviderinterface_method_entry) {
	PHP_ABSTRACT_ME(ZendFramework_ModuleManager_Feature_ConsoleBannerProviderInterface, getConsoleBanner, arginfo_zendframework_modulemanager_feature_consolebannerproviderinterface_getconsolebanner)
  PHP_FE_END
};
