
extern zend_class_entry *zendframework_modulemanager_feature_dependencyindicatorinterface_ce;

ZEPHIR_INIT_CLASS(ZendFramework_ModuleManager_Feature_DependencyIndicatorInterface);

ZEPHIR_INIT_FUNCS(zendframework_modulemanager_feature_dependencyindicatorinterface_method_entry) {
	PHP_ABSTRACT_ME(ZendFramework_ModuleManager_Feature_DependencyIndicatorInterface, getModuleDependencies, NULL)
  PHP_FE_END
};
