
extern zend_class_entry *zendframework_modulemanager_feature_filterproviderinterface_ce;

ZEPHIR_INIT_CLASS(ZendFramework_ModuleManager_Feature_FilterProviderInterface);

ZEPHIR_INIT_FUNCS(zendframework_modulemanager_feature_filterproviderinterface_method_entry) {
	PHP_ABSTRACT_ME(ZendFramework_ModuleManager_Feature_FilterProviderInterface, getFilterConfig, NULL)
  PHP_FE_END
};
