
extern zend_class_entry *zendframework_modulemanager_feature_initproviderinterface_ce;

ZEPHIR_INIT_CLASS(ZendFramework_ModuleManager_Feature_InitProviderInterface);

ZEND_BEGIN_ARG_INFO_EX(arginfo_zendframework_modulemanager_feature_initproviderinterface_init, 0, 0, 1)
	ZEND_ARG_OBJ_INFO(0, manager, ZendFramework\\ModuleManager\\ModuleManagerInterface, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(zendframework_modulemanager_feature_initproviderinterface_method_entry) {
	PHP_ABSTRACT_ME(ZendFramework_ModuleManager_Feature_InitProviderInterface, init, arginfo_zendframework_modulemanager_feature_initproviderinterface_init)
  PHP_FE_END
};
