
extern zend_class_entry *zendframework_modulemanager_feature_inputfilterproviderinterface_ce;

ZEPHIR_INIT_CLASS(ZendFramework_ModuleManager_Feature_InputFilterProviderInterface);

ZEPHIR_INIT_FUNCS(zendframework_modulemanager_feature_inputfilterproviderinterface_method_entry) {
	PHP_ABSTRACT_ME(ZendFramework_ModuleManager_Feature_InputFilterProviderInterface, getInputFilterConfig, NULL)
  PHP_FE_END
};
