
extern zend_class_entry *zendframework_modulemanager_feature_logwriterproviderinterface_ce;

ZEPHIR_INIT_CLASS(ZendFramework_ModuleManager_Feature_LogWriterProviderInterface);

ZEPHIR_INIT_FUNCS(zendframework_modulemanager_feature_logwriterproviderinterface_method_entry) {
	PHP_ABSTRACT_ME(ZendFramework_ModuleManager_Feature_LogWriterProviderInterface, getLogWriterConfig, NULL)
  PHP_FE_END
};
