
extern zend_class_entry *zendframework_modulemanager_feature_routeproviderinterface_ce;

ZEPHIR_INIT_CLASS(ZendFramework_ModuleManager_Feature_RouteProviderInterface);

ZEPHIR_INIT_FUNCS(zendframework_modulemanager_feature_routeproviderinterface_method_entry) {
	PHP_ABSTRACT_ME(ZendFramework_ModuleManager_Feature_RouteProviderInterface, getRouteConfig, NULL)
  PHP_FE_END
};
