
extern zend_class_entry *zendframework_modulemanager_feature_serializerproviderinterface_ce;

ZEPHIR_INIT_CLASS(ZendFramework_ModuleManager_Feature_SerializerProviderInterface);

ZEPHIR_INIT_FUNCS(zendframework_modulemanager_feature_serializerproviderinterface_method_entry) {
	PHP_ABSTRACT_ME(ZendFramework_ModuleManager_Feature_SerializerProviderInterface, getSerializerConfig, NULL)
  PHP_FE_END
};
