
extern zend_class_entry *zendframework_modulemanager_feature_serviceproviderinterface_ce;

ZEPHIR_INIT_CLASS(ZendFramework_ModuleManager_Feature_ServiceProviderInterface);

ZEPHIR_INIT_FUNCS(zendframework_modulemanager_feature_serviceproviderinterface_method_entry) {
	PHP_ABSTRACT_ME(ZendFramework_ModuleManager_Feature_ServiceProviderInterface, getServiceConfig, NULL)
  PHP_FE_END
};
