
extern zend_class_entry *zendframework_form_labelawareinterface_ce;

ZEPHIR_INIT_CLASS(ZendFramework_Form_LabelAwareInterface);

ZEND_BEGIN_ARG_INFO_EX(arginfo_zendframework_form_labelawareinterface_setlabel, 0, 0, 1)
	ZEND_ARG_INFO(0, label)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_INFO_EX(arginfo_zendframework_form_labelawareinterface_setlabelattributes, 0, 0, 1)
	ZEND_ARG_ARRAY_INFO(0, labelAttributes, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_INFO_EX(arginfo_zendframework_form_labelawareinterface_setlabeloptions, 0, 0, 1)
	ZEND_ARG_INFO(0, arrayOrTraversable)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_INFO_EX(arginfo_zendframework_form_labelawareinterface_setlabeloption, 0, 0, 2)
	ZEND_ARG_INFO(0, key)
	ZEND_ARG_INFO(0, value)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_INFO_EX(arginfo_zendframework_form_labelawareinterface_getlabeloption, 0, 0, 1)
	ZEND_ARG_INFO(0, key)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_INFO_EX(arginfo_zendframework_form_labelawareinterface_removelabeloption, 0, 0, 1)
	ZEND_ARG_INFO(0, key)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_INFO_EX(arginfo_zendframework_form_labelawareinterface_haslabeloption, 0, 0, 1)
	ZEND_ARG_INFO(0, key)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_INFO_EX(arginfo_zendframework_form_labelawareinterface_removelabeloptions, 0, 0, 1)
	ZEND_ARG_ARRAY_INFO(0, keys, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(zendframework_form_labelawareinterface_method_entry) {
	PHP_ABSTRACT_ME(ZendFramework_Form_LabelAwareInterface, setLabel, arginfo_zendframework_form_labelawareinterface_setlabel)
	PHP_ABSTRACT_ME(ZendFramework_Form_LabelAwareInterface, getLabel, NULL)
	PHP_ABSTRACT_ME(ZendFramework_Form_LabelAwareInterface, setLabelAttributes, arginfo_zendframework_form_labelawareinterface_setlabelattributes)
	PHP_ABSTRACT_ME(ZendFramework_Form_LabelAwareInterface, getLabelAttributes, NULL)
	PHP_ABSTRACT_ME(ZendFramework_Form_LabelAwareInterface, setLabelOptions, arginfo_zendframework_form_labelawareinterface_setlabeloptions)
	PHP_ABSTRACT_ME(ZendFramework_Form_LabelAwareInterface, getLabelOptions, NULL)
	PHP_ABSTRACT_ME(ZendFramework_Form_LabelAwareInterface, setLabelOption, arginfo_zendframework_form_labelawareinterface_setlabeloption)
	PHP_ABSTRACT_ME(ZendFramework_Form_LabelAwareInterface, getLabelOption, arginfo_zendframework_form_labelawareinterface_getlabeloption)
	PHP_ABSTRACT_ME(ZendFramework_Form_LabelAwareInterface, removeLabelOption, arginfo_zendframework_form_labelawareinterface_removelabeloption)
	PHP_ABSTRACT_ME(ZendFramework_Form_LabelAwareInterface, hasLabelOption, arginfo_zendframework_form_labelawareinterface_haslabeloption)
	PHP_ABSTRACT_ME(ZendFramework_Form_LabelAwareInterface, removeLabelOptions, arginfo_zendframework_form_labelawareinterface_removelabeloptions)
	PHP_ABSTRACT_ME(ZendFramework_Form_LabelAwareInterface, clearLabelOptions, NULL)
  PHP_FE_END
};
