
extern zend_class_entry *zendframework_db_adapter_platform_platforminterface_ce;

ZEPHIR_INIT_CLASS(ZendFramework_Db_Adapter_Platform_PlatformInterface);

ZEND_BEGIN_ARG_INFO_EX(arginfo_zendframework_db_adapter_platform_platforminterface_quoteidentifier, 0, 0, 1)
	ZEND_ARG_INFO(0, identifier)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_INFO_EX(arginfo_zendframework_db_adapter_platform_platforminterface_quoteidentifierchain, 0, 0, 1)
	ZEND_ARG_INFO(0, identifierChain)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_INFO_EX(arginfo_zendframework_db_adapter_platform_platforminterface_quotevalue, 0, 0, 1)
	ZEND_ARG_INFO(0, value)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_INFO_EX(arginfo_zendframework_db_adapter_platform_platforminterface_quotetrustedvalue, 0, 0, 1)
	ZEND_ARG_INFO(0, value)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_INFO_EX(arginfo_zendframework_db_adapter_platform_platforminterface_quotevaluelist, 0, 0, 1)
	ZEND_ARG_INFO(0, valueList)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_INFO_EX(arginfo_zendframework_db_adapter_platform_platforminterface_quoteidentifierinfragment, 0, 0, 1)
	ZEND_ARG_INFO(0, identifier)
	ZEND_ARG_ARRAY_INFO(0, additionalSafeWords, 1)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(zendframework_db_adapter_platform_platforminterface_method_entry) {
	PHP_ABSTRACT_ME(ZendFramework_Db_Adapter_Platform_PlatformInterface, getName, NULL)
	PHP_ABSTRACT_ME(ZendFramework_Db_Adapter_Platform_PlatformInterface, getQuoteIdentifierSymbol, NULL)
	PHP_ABSTRACT_ME(ZendFramework_Db_Adapter_Platform_PlatformInterface, quoteIdentifier, arginfo_zendframework_db_adapter_platform_platforminterface_quoteidentifier)
	PHP_ABSTRACT_ME(ZendFramework_Db_Adapter_Platform_PlatformInterface, quoteIdentifierChain, arginfo_zendframework_db_adapter_platform_platforminterface_quoteidentifierchain)
	PHP_ABSTRACT_ME(ZendFramework_Db_Adapter_Platform_PlatformInterface, getQuoteValueSymbol, NULL)
	PHP_ABSTRACT_ME(ZendFramework_Db_Adapter_Platform_PlatformInterface, quoteValue, arginfo_zendframework_db_adapter_platform_platforminterface_quotevalue)
	PHP_ABSTRACT_ME(ZendFramework_Db_Adapter_Platform_PlatformInterface, quoteTrustedValue, arginfo_zendframework_db_adapter_platform_platforminterface_quotetrustedvalue)
	PHP_ABSTRACT_ME(ZendFramework_Db_Adapter_Platform_PlatformInterface, quoteValueList, arginfo_zendframework_db_adapter_platform_platforminterface_quotevaluelist)
	PHP_ABSTRACT_ME(ZendFramework_Db_Adapter_Platform_PlatformInterface, getIdentifierSeparator, NULL)
	PHP_ABSTRACT_ME(ZendFramework_Db_Adapter_Platform_PlatformInterface, quoteIdentifierInFragment, arginfo_zendframework_db_adapter_platform_platforminterface_quoteidentifierinfragment)
  PHP_FE_END
};
