
extern zend_class_entry *zendframework_stdlib_hydrator_filterenabledinterface_ce;

ZEPHIR_INIT_CLASS(ZendFramework_Stdlib_Hydrator_FilterEnabledInterface);

ZEND_BEGIN_ARG_INFO_EX(arginfo_zendframework_stdlib_hydrator_filterenabledinterface_addfilter, 0, 0, 2)
	ZEND_ARG_INFO(0, name)
	ZEND_ARG_INFO(0, filter)
	ZEND_ARG_INFO(0, condition)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_INFO_EX(arginfo_zendframework_stdlib_hydrator_filterenabledinterface_hasfilter, 0, 0, 1)
	ZEND_ARG_INFO(0, name)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_INFO_EX(arginfo_zendframework_stdlib_hydrator_filterenabledinterface_removefilter, 0, 0, 1)
	ZEND_ARG_INFO(0, name)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(zendframework_stdlib_hydrator_filterenabledinterface_method_entry) {
	PHP_ABSTRACT_ME(ZendFramework_Stdlib_Hydrator_FilterEnabledInterface, addFilter, arginfo_zendframework_stdlib_hydrator_filterenabledinterface_addfilter)
	PHP_ABSTRACT_ME(ZendFramework_Stdlib_Hydrator_FilterEnabledInterface, hasFilter, arginfo_zendframework_stdlib_hydrator_filterenabledinterface_hasfilter)
	PHP_ABSTRACT_ME(ZendFramework_Stdlib_Hydrator_FilterEnabledInterface, removeFilter, arginfo_zendframework_stdlib_hydrator_filterenabledinterface_removefilter)
  PHP_FE_END
};
