
extern zend_class_entry *zendframework_filter_compress_compressionalgorithminterface_ce;

ZEPHIR_INIT_CLASS(ZendFramework_Filter_Compress_CompressionAlgorithmInterface);

ZEND_BEGIN_ARG_INFO_EX(arginfo_zendframework_filter_compress_compressionalgorithminterface_compress, 0, 0, 1)
	ZEND_ARG_INFO(0, value)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_INFO_EX(arginfo_zendframework_filter_compress_compressionalgorithminterface_decompress, 0, 0, 1)
	ZEND_ARG_INFO(0, value)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(zendframework_filter_compress_compressionalgorithminterface_method_entry) {
	PHP_ABSTRACT_ME(ZendFramework_Filter_Compress_CompressionAlgorithmInterface, compress, arginfo_zendframework_filter_compress_compressionalgorithminterface_compress)
	PHP_ABSTRACT_ME(ZendFramework_Filter_Compress_CompressionAlgorithmInterface, decompress, arginfo_zendframework_filter_compress_compressionalgorithminterface_decompress)
	PHP_ABSTRACT_ME(ZendFramework_Filter_Compress_CompressionAlgorithmInterface, toString, NULL)
  PHP_FE_END
};
