
extern zend_class_entry *zendframework_stdlib_hydrator_filter_filterinterface_ce;

ZEPHIR_INIT_CLASS(ZendFramework_Stdlib_Hydrator_Filter_FilterInterface);

ZEND_BEGIN_ARG_INFO_EX(arginfo_zendframework_stdlib_hydrator_filter_filterinterface_filter, 0, 0, 1)
	ZEND_ARG_INFO(0, property)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(zendframework_stdlib_hydrator_filter_filterinterface_method_entry) {
	PHP_ABSTRACT_ME(ZendFramework_Stdlib_Hydrator_Filter_FilterInterface, filter, arginfo_zendframework_stdlib_hydrator_filter_filterinterface_filter)
  PHP_FE_END
};
