
extern zend_class_entry *zendframework_view_helper_navigation_helperinterface_ce;

ZEPHIR_INIT_CLASS(ZendFramework_View_Helper_Navigation_HelperInterface);

ZEND_BEGIN_ARG_INFO_EX(arginfo_zendframework_view_helper_navigation_helperinterface_render, 0, 0, 0)
	ZEND_ARG_INFO(0, container)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_INFO_EX(arginfo_zendframework_view_helper_navigation_helperinterface_setacl, 0, 0, 0)
	ZEND_ARG_INFO(0, acl)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_INFO_EX(arginfo_zendframework_view_helper_navigation_helperinterface_setcontainer, 0, 0, 0)
	ZEND_ARG_INFO(0, container)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_INFO_EX(arginfo_zendframework_view_helper_navigation_helperinterface_setrenderinvisible, 0, 0, 0)
	ZEND_ARG_INFO(0, renderInvisible)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_INFO_EX(arginfo_zendframework_view_helper_navigation_helperinterface_setrole, 0, 0, 0)
	ZEND_ARG_INFO(0, role)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_INFO_EX(arginfo_zendframework_view_helper_navigation_helperinterface_setuseacl, 0, 0, 0)
	ZEND_ARG_INFO(0, useAcl)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(zendframework_view_helper_navigation_helperinterface_method_entry) {
	PHP_ABSTRACT_ME(ZendFramework_View_Helper_Navigation_HelperInterface, __toString, NULL)
	PHP_ABSTRACT_ME(ZendFramework_View_Helper_Navigation_HelperInterface, render, arginfo_zendframework_view_helper_navigation_helperinterface_render)
	PHP_ABSTRACT_ME(ZendFramework_View_Helper_Navigation_HelperInterface, setAcl, arginfo_zendframework_view_helper_navigation_helperinterface_setacl)
	PHP_ABSTRACT_ME(ZendFramework_View_Helper_Navigation_HelperInterface, getAcl, NULL)
	PHP_ABSTRACT_ME(ZendFramework_View_Helper_Navigation_HelperInterface, hasAcl, NULL)
	PHP_ABSTRACT_ME(ZendFramework_View_Helper_Navigation_HelperInterface, setContainer, arginfo_zendframework_view_helper_navigation_helperinterface_setcontainer)
	PHP_ABSTRACT_ME(ZendFramework_View_Helper_Navigation_HelperInterface, getContainer, NULL)
	PHP_ABSTRACT_ME(ZendFramework_View_Helper_Navigation_HelperInterface, hasContainer, NULL)
	PHP_ABSTRACT_ME(ZendFramework_View_Helper_Navigation_HelperInterface, setRenderInvisible, arginfo_zendframework_view_helper_navigation_helperinterface_setrenderinvisible)
	PHP_ABSTRACT_ME(ZendFramework_View_Helper_Navigation_HelperInterface, getRenderInvisible, NULL)
	PHP_ABSTRACT_ME(ZendFramework_View_Helper_Navigation_HelperInterface, setRole, arginfo_zendframework_view_helper_navigation_helperinterface_setrole)
	PHP_ABSTRACT_ME(ZendFramework_View_Helper_Navigation_HelperInterface, getRole, NULL)
	PHP_ABSTRACT_ME(ZendFramework_View_Helper_Navigation_HelperInterface, hasRole, NULL)
	PHP_ABSTRACT_ME(ZendFramework_View_Helper_Navigation_HelperInterface, setUseAcl, arginfo_zendframework_view_helper_navigation_helperinterface_setuseacl)
	PHP_ABSTRACT_ME(ZendFramework_View_Helper_Navigation_HelperInterface, getUseAcl, NULL)
  PHP_FE_END
};
