
extern zend_class_entry *zendframework_console_adapter_adapterinterface_ce;

ZEPHIR_INIT_CLASS(ZendFramework_Console_Adapter_AdapterInterface);

ZEND_BEGIN_ARG_INFO_EX(arginfo_zendframework_console_adapter_adapterinterface_write, 0, 0, 1)
	ZEND_ARG_INFO(0, text)
	ZEND_ARG_INFO(0, color)
	ZEND_ARG_INFO(0, bgColor)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_INFO_EX(arginfo_zendframework_console_adapter_adapterinterface_writetext, 0, 0, 1)
	ZEND_ARG_INFO(0, text)
	ZEND_ARG_INFO(0, color)
	ZEND_ARG_INFO(0, bgColor)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_INFO_EX(arginfo_zendframework_console_adapter_adapterinterface_writeline, 0, 0, 0)
	ZEND_ARG_INFO(0, text)
	ZEND_ARG_INFO(0, color)
	ZEND_ARG_INFO(0, bgColor)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_INFO_EX(arginfo_zendframework_console_adapter_adapterinterface_writeat, 0, 0, 3)
	ZEND_ARG_INFO(0, text)
	ZEND_ARG_INFO(0, x)
	ZEND_ARG_INFO(0, y)
	ZEND_ARG_INFO(0, color)
	ZEND_ARG_INFO(0, bgColor)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_INFO_EX(arginfo_zendframework_console_adapter_adapterinterface_writebox, 0, 0, 4)
	ZEND_ARG_INFO(0, x1)
	ZEND_ARG_INFO(0, y1)
	ZEND_ARG_INFO(0, x2)
	ZEND_ARG_INFO(0, y2)
	ZEND_ARG_INFO(0, lineStyle)
	ZEND_ARG_INFO(0, fillStyle)
	ZEND_ARG_INFO(0, color)
	ZEND_ARG_INFO(0, bgColor)
	ZEND_ARG_INFO(0, fillColor)
	ZEND_ARG_INFO(0, fillBgColor)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_INFO_EX(arginfo_zendframework_console_adapter_adapterinterface_writetextblock, 0, 0, 2)
	ZEND_ARG_INFO(0, text)
	ZEND_ARG_INFO(0, width)
	ZEND_ARG_INFO(0, height)
	ZEND_ARG_INFO(0, x)
	ZEND_ARG_INFO(0, y)
	ZEND_ARG_INFO(0, color)
	ZEND_ARG_INFO(0, bgColor)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_INFO_EX(arginfo_zendframework_console_adapter_adapterinterface_setpos, 0, 0, 2)
	ZEND_ARG_INFO(0, x)
	ZEND_ARG_INFO(0, y)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_INFO_EX(arginfo_zendframework_console_adapter_adapterinterface_colorize, 0, 0, 1)
	ZEND_ARG_INFO(0, string)
	ZEND_ARG_INFO(0, color)
	ZEND_ARG_INFO(0, bgColor)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_INFO_EX(arginfo_zendframework_console_adapter_adapterinterface_setcolor, 0, 0, 1)
	ZEND_ARG_INFO(0, color)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_INFO_EX(arginfo_zendframework_console_adapter_adapterinterface_setbgcolor, 0, 0, 1)
	ZEND_ARG_INFO(0, color)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_INFO_EX(arginfo_zendframework_console_adapter_adapterinterface_setcharset, 0, 0, 1)
	ZEND_ARG_INFO(0, charset)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_INFO_EX(arginfo_zendframework_console_adapter_adapterinterface_readline, 0, 0, 0)
	ZEND_ARG_INFO(0, maxLength)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_INFO_EX(arginfo_zendframework_console_adapter_adapterinterface_readchar, 0, 0, 0)
	ZEND_ARG_INFO(0, mask)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(zendframework_console_adapter_adapterinterface_method_entry) {
	PHP_ABSTRACT_ME(ZendFramework_Console_Adapter_AdapterInterface, write, arginfo_zendframework_console_adapter_adapterinterface_write)
	PHP_ABSTRACT_ME(ZendFramework_Console_Adapter_AdapterInterface, writeText, arginfo_zendframework_console_adapter_adapterinterface_writetext)
	PHP_ABSTRACT_ME(ZendFramework_Console_Adapter_AdapterInterface, writeLine, arginfo_zendframework_console_adapter_adapterinterface_writeline)
	PHP_ABSTRACT_ME(ZendFramework_Console_Adapter_AdapterInterface, writeAt, arginfo_zendframework_console_adapter_adapterinterface_writeat)
	PHP_ABSTRACT_ME(ZendFramework_Console_Adapter_AdapterInterface, writeBox, arginfo_zendframework_console_adapter_adapterinterface_writebox)
	PHP_ABSTRACT_ME(ZendFramework_Console_Adapter_AdapterInterface, writeTextBlock, arginfo_zendframework_console_adapter_adapterinterface_writetextblock)
	PHP_ABSTRACT_ME(ZendFramework_Console_Adapter_AdapterInterface, getWidth, NULL)
	PHP_ABSTRACT_ME(ZendFramework_Console_Adapter_AdapterInterface, getHeight, NULL)
	PHP_ABSTRACT_ME(ZendFramework_Console_Adapter_AdapterInterface, getSize, NULL)
	PHP_ABSTRACT_ME(ZendFramework_Console_Adapter_AdapterInterface, isUtf8, NULL)
	PHP_ABSTRACT_ME(ZendFramework_Console_Adapter_AdapterInterface, setPos, arginfo_zendframework_console_adapter_adapterinterface_setpos)
	PHP_ABSTRACT_ME(ZendFramework_Console_Adapter_AdapterInterface, hideCursor, NULL)
	PHP_ABSTRACT_ME(ZendFramework_Console_Adapter_AdapterInterface, showCursor, NULL)
	PHP_ABSTRACT_ME(ZendFramework_Console_Adapter_AdapterInterface, getTitle, NULL)
	PHP_ABSTRACT_ME(ZendFramework_Console_Adapter_AdapterInterface, colorize, arginfo_zendframework_console_adapter_adapterinterface_colorize)
	PHP_ABSTRACT_ME(ZendFramework_Console_Adapter_AdapterInterface, setColor, arginfo_zendframework_console_adapter_adapterinterface_setcolor)
	PHP_ABSTRACT_ME(ZendFramework_Console_Adapter_AdapterInterface, setBgColor, arginfo_zendframework_console_adapter_adapterinterface_setbgcolor)
	PHP_ABSTRACT_ME(ZendFramework_Console_Adapter_AdapterInterface, resetColor, NULL)
	PHP_ABSTRACT_ME(ZendFramework_Console_Adapter_AdapterInterface, setCharset, arginfo_zendframework_console_adapter_adapterinterface_setcharset)
	PHP_ABSTRACT_ME(ZendFramework_Console_Adapter_AdapterInterface, getCharset, NULL)
	PHP_ABSTRACT_ME(ZendFramework_Console_Adapter_AdapterInterface, getDefaultCharset, NULL)
	PHP_ABSTRACT_ME(ZendFramework_Console_Adapter_AdapterInterface, clear, NULL)
	PHP_ABSTRACT_ME(ZendFramework_Console_Adapter_AdapterInterface, clearLine, NULL)
	PHP_ABSTRACT_ME(ZendFramework_Console_Adapter_AdapterInterface, clearScreen, NULL)
	PHP_ABSTRACT_ME(ZendFramework_Console_Adapter_AdapterInterface, readLine, arginfo_zendframework_console_adapter_adapterinterface_readline)
	PHP_ABSTRACT_ME(ZendFramework_Console_Adapter_AdapterInterface, readChar, arginfo_zendframework_console_adapter_adapterinterface_readchar)
  PHP_FE_END
};
