
/* This file was generated automatically by Zephir do not modify it! */

#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#include <php.h>

#if PHP_VERSION_ID < 50500
#include <locale.h>
#endif

#include "php_ext.h"
#include "zendframework.h"

#include <ext/standard/info.h>

#include <Zend/zend_operators.h>
#include <Zend/zend_exceptions.h>
#include <Zend/zend_interfaces.h>

#include "kernel/main.h"
#include "kernel/fcall.h"
#include "kernel/memory.h"



zend_class_entry *zendframework_http_exception_exceptioninterface_ce;
zend_class_entry *zendframework_db_exception_exceptioninterface_ce;
zend_class_entry *zendframework_authentication_exception_exceptioninterface_ce;
zend_class_entry *zendframework_xmlrpc_exception_exceptioninterface_ce;
zend_class_entry *zendframework_mail_exception_exceptioninterface_ce;
zend_class_entry *zendframework_http_client_exception_exceptioninterface_ce;
zend_class_entry *zendframework_math_exception_exceptioninterface_ce;
zend_class_entry *zendframework_crypt_exception_exceptioninterface_ce;
zend_class_entry *zendframework_text_exception_exceptioninterface_ce;
zend_class_entry *zendframework_json_exception_exceptioninterface_ce;
zend_class_entry *zendframework_cache_exception_exceptioninterface_ce;
zend_class_entry *zendframework_servicemanager_exception_exceptioninterface_ce;
zend_class_entry *zendframework_authentication_adapter_exception_exceptioninterface_ce;
zend_class_entry *zendframework_code_exception_exceptioninterface_ce;
zend_class_entry *zendframework_file_exception_exceptioninterface_ce;
zend_class_entry *zendframework_paginator_exception_exceptioninterface_ce;
zend_class_entry *zendframework_progressbar_exception_exceptioninterface_ce;
zend_class_entry *zendframework_mvc_exception_exceptioninterface_ce;
zend_class_entry *zendframework_ldap_exception_exceptioninterface_ce;
zend_class_entry *zendframework_captcha_exception_exceptioninterface_ce;
zend_class_entry *zendframework_db_adapter_exception_exceptioninterface_ce;
zend_class_entry *zendframework_di_exception_exceptioninterface_ce;
zend_class_entry *zendframework_server_exception_exceptioninterface_ce;
zend_class_entry *zendframework_modulemanager_exception_exceptioninterface_ce;
zend_class_entry *zendframework_xmlrpc_client_exception_exceptioninterface_ce;
zend_class_entry *zendframework_loader_exception_exceptioninterface_ce;
zend_class_entry *zendframework_stdlib_exception_exceptioninterface_ce;
zend_class_entry *zendframework_http_client_adapter_exception_exceptioninterface_ce;
zend_class_entry *zendframework_i18n_exception_exceptioninterface_ce;
zend_class_entry *zendframework_tag_exception_exceptioninterface_ce;
zend_class_entry *zendframework_filter_exception_exceptioninterface_ce;
zend_class_entry *zendframework_form_exception_exceptioninterface_ce;
zend_class_entry *zendframework_mail_storage_exception_exceptioninterface_ce;
zend_class_entry *zendframework_file_transfer_exception_exceptioninterface_ce;
zend_class_entry *zendframework_json_server_exception_exceptioninterface_ce;
zend_class_entry *zendframework_validator_exception_exceptioninterface_ce;
zend_class_entry *zendframework_math_biginteger_exception_exceptioninterface_ce;
zend_class_entry *zendframework_serializer_exception_exceptioninterface_ce;
zend_class_entry *zendframework_view_exception_exceptioninterface_ce;
zend_class_entry *zendframework_di_locatorinterface_ce;
zend_class_entry *zendframework_eventmanager_eventscapableinterface_ce;
zend_class_entry *zendframework_text_table_exception_exceptioninterface_ce;
zend_class_entry *zendframework_uri_exception_exceptioninterface_ce;
zend_class_entry *zendframework_eventmanager_eventmanagerawareinterface_ce;
zend_class_entry *zendframework_eventmanager_exception_exceptioninterface_ce;
zend_class_entry *zendframework_navigation_exception_exceptioninterface_ce;
zend_class_entry *zendframework_soap_exception_exceptioninterface_ce;
zend_class_entry *zendframework_code_generic_prototype_prototypeinterface_ce;
zend_class_entry *zendframework_code_reflection_exception_exceptioninterface_ce;
zend_class_entry *zendframework_console_exception_exceptioninterface_ce;
zend_class_entry *zendframework_db_sql_expressioninterface_ce;
zend_class_entry *zendframework_http_header_exception_exceptioninterface_ce;
zend_class_entry *zendframework_ldap_converter_exception_exceptioninterface_ce;
zend_class_entry *zendframework_mail_header_exception_exceptioninterface_ce;
zend_class_entry *zendframework_mail_header_headerinterface_ce;
zend_class_entry *zendframework_mail_transport_exception_exceptioninterface_ce;
zend_class_entry *zendframework_mvc_router_routeinterface_ce;
zend_class_entry *zendframework_paginator_adapter_exception_exceptioninterface_ce;
zend_class_entry *zendframework_permissions_acl_exception_exceptioninterface_ce;
zend_class_entry *zendframework_server_reflection_exception_exceptioninterface_ce;
zend_class_entry *zendframework_session_exception_exceptioninterface_ce;
zend_class_entry *zendframework_stdlib_messageinterface_ce;
zend_class_entry *zendframework_text_figlet_exception_exceptioninterface_ce;
zend_class_entry *zendframework_xmlrpc_server_exception_exceptioninterface_ce;
zend_class_entry *zendframework_authentication_adapter_dbtable_exception_exceptioninterface_ce;
zend_class_entry *zendframework_authentication_adapter_http_exception_exceptioninterface_ce;
zend_class_entry *zendframework_code_annotation_annotationinterface_ce;
zend_class_entry *zendframework_code_generator_exception_exceptioninterface_ce;
zend_class_entry *zendframework_config_exception_exceptioninterface_ce;
zend_class_entry *zendframework_crypt_key_derivation_exception_exceptioninterface_ce;
zend_class_entry *zendframework_crypt_password_exception_exceptioninterface_ce;
zend_class_entry *zendframework_crypt_publickey_rsa_exception_exceptioninterface_ce;
zend_class_entry *zendframework_crypt_symmetric_exception_exceptioninterface_ce;
zend_class_entry *zendframework_db_resultset_exception_exceptioninterface_ce;
zend_class_entry *zendframework_db_rowgateway_exception_exceptioninterface_ce;
zend_class_entry *zendframework_db_sql_exception_exceptioninterface_ce;
zend_class_entry *zendframework_db_tablegateway_exception_exceptioninterface_ce;
zend_class_entry *zendframework_dom_exception_exceptioninterface_ce;
zend_class_entry *zendframework_escaper_exception_exceptioninterface_ce;
zend_class_entry *zendframework_eventmanager_eventinterface_ce;
zend_class_entry *zendframework_eventmanager_listeneraggregateinterface_ce;
zend_class_entry *zendframework_form_elementinterface_ce;
zend_class_entry *zendframework_form_elementprepareawareinterface_ce;
zend_class_entry *zendframework_form_formfactoryawareinterface_ce;
zend_class_entry *zendframework_inputfilter_exception_exceptioninterface_ce;
zend_class_entry *zendframework_log_exception_exceptioninterface_ce;
zend_class_entry *zendframework_mail_protocol_exception_exceptioninterface_ce;
zend_class_entry *zendframework_mail_storage_part_exception_exceptioninterface_ce;
zend_class_entry *zendframework_memory_exception_exceptioninterface_ce;
zend_class_entry *zendframework_modulemanager_listener_exception_exceptioninterface_ce;
zend_class_entry *zendframework_mvc_router_exception_exceptioninterface_ce;
zend_class_entry *zendframework_progressbar_adapter_exception_exceptioninterface_ce;
zend_class_entry *zendframework_authentication_adapter_adapterinterface_ce;
zend_class_entry *zendframework_db_adapter_statementcontainerinterface_ce;
zend_class_entry *zendframework_db_sql_sqlinterface_ce;
zend_class_entry *zendframework_di_definition_definitioninterface_ce;
zend_class_entry *zendframework_di_servicelocatorinterface_ce;
zend_class_entry *zendframework_eventmanager_filter_filterinterface_ce;
zend_class_entry *zendframework_eventmanager_sharedeventmanagerawareinterface_ce;
zend_class_entry *zendframework_form_fieldsetinterface_ce;
zend_class_entry *zendframework_http_header_headerinterface_ce;
zend_class_entry *zendframework_ldap_filter_exception_exceptioninterface_ce;
zend_class_entry *zendframework_loader_shortnamelocator_ce;
zend_class_entry *zendframework_mime_exception_exceptioninterface_ce;
zend_class_entry *zendframework_modulemanager_modulemanagerinterface_ce;
zend_class_entry *zendframework_permissions_acl_resource_resourceinterface_ce;
zend_class_entry *zendframework_permissions_acl_role_roleinterface_ce;
zend_class_entry *zendframework_permissions_rbac_exception_exceptioninterface_ce;
zend_class_entry *zendframework_stdlib_extractor_extractioninterface_ce;
zend_class_entry *zendframework_stdlib_hydrator_filter_filterproviderinterface_ce;
zend_class_entry *zendframework_stdlib_hydrator_hydrationinterface_ce;
zend_class_entry *zendframework_stdlib_parametersinterface_ce;
zend_class_entry *zendframework_tag_cloud_decorator_exception_exceptioninterface_ce;
zend_class_entry *zendframework_validator_validatorinterface_ce;
zend_class_entry *zendframework_view_helper_helperinterface_ce;
zend_class_entry *zendframework_authentication_adapter_http_resolverinterface_ce;
zend_class_entry *zendframework_authentication_adapter_validatableadapterinterface_ce;
zend_class_entry *zendframework_authentication_authenticationserviceinterface_ce;
zend_class_entry *zendframework_authentication_storage_storageinterface_ce;
zend_class_entry *zendframework_cache_pattern_patterninterface_ce;
zend_class_entry *zendframework_cache_storage_availablespacecapableinterface_ce;
zend_class_entry *zendframework_cache_storage_clearbynamespaceinterface_ce;
zend_class_entry *zendframework_cache_storage_clearbyprefixinterface_ce;
zend_class_entry *zendframework_cache_storage_clearexpiredinterface_ce;
zend_class_entry *zendframework_cache_storage_flushableinterface_ce;
zend_class_entry *zendframework_cache_storage_iterableinterface_ce;
zend_class_entry *zendframework_cache_storage_iteratorinterface_ce;
zend_class_entry *zendframework_cache_storage_optimizableinterface_ce;
zend_class_entry *zendframework_cache_storage_plugin_plugininterface_ce;
zend_class_entry *zendframework_cache_storage_storageinterface_ce;
zend_class_entry *zendframework_cache_storage_taggableinterface_ce;
zend_class_entry *zendframework_cache_storage_totalspacecapableinterface_ce;
zend_class_entry *zendframework_captcha_adapterinterface_ce;
zend_class_entry *zendframework_code_annotation_parser_parserinterface_ce;
zend_class_entry *zendframework_code_generator_docblock_tag_taginterface_ce;
zend_class_entry *zendframework_code_generator_generatorinterface_ce;
zend_class_entry *zendframework_code_generic_prototype_prototypegenericinterface_ce;
zend_class_entry *zendframework_code_reflection_docblock_tag_phpdoctypedtaginterface_ce;
zend_class_entry *zendframework_code_reflection_docblock_tag_taginterface_ce;
zend_class_entry *zendframework_code_reflection_reflectioninterface_ce;
zend_class_entry *zendframework_code_scanner_scannerinterface_ce;
zend_class_entry *zendframework_config_processor_processorinterface_ce;
zend_class_entry *zendframework_config_reader_readerinterface_ce;
zend_class_entry *zendframework_config_writer_writerinterface_ce;
zend_class_entry *zendframework_console_adapter_adapterinterface_ce;
zend_class_entry *zendframework_console_charset_charsetinterface_ce;
zend_class_entry *zendframework_console_colorinterface_ce;
zend_class_entry *zendframework_console_prompt_promptinterface_ce;
zend_class_entry *zendframework_console_routematcher_routematcherinterface_ce;
zend_class_entry *zendframework_crypt_password_passwordinterface_ce;
zend_class_entry *zendframework_crypt_symmetric_padding_paddinginterface_ce;
zend_class_entry *zendframework_crypt_symmetric_symmetricinterface_ce;
zend_class_entry *zendframework_db_adapter_adapterawareinterface_ce;
zend_class_entry *zendframework_db_adapter_adapterinterface_ce;
zend_class_entry *zendframework_db_adapter_driver_connectioninterface_ce;
zend_class_entry *zendframework_db_adapter_driver_driverinterface_ce;
zend_class_entry *zendframework_db_adapter_driver_feature_driverfeatureinterface_ce;
zend_class_entry *zendframework_db_adapter_driver_resultinterface_ce;
zend_class_entry *zendframework_db_adapter_driver_statementinterface_ce;
zend_class_entry *zendframework_db_adapter_platform_platforminterface_ce;
zend_class_entry *zendframework_db_adapter_profiler_profilerawareinterface_ce;
zend_class_entry *zendframework_db_adapter_profiler_profilerinterface_ce;
zend_class_entry *zendframework_db_metadata_metadatainterface_ce;
zend_class_entry *zendframework_db_resultset_resultsetinterface_ce;
zend_class_entry *zendframework_db_rowgateway_rowgatewayinterface_ce;
zend_class_entry *zendframework_db_sql_ddl_column_columninterface_ce;
zend_class_entry *zendframework_db_sql_ddl_constraint_constraintinterface_ce;
zend_class_entry *zendframework_db_sql_ddl_sqlinterface_ce;
zend_class_entry *zendframework_db_sql_platform_platformdecoratorinterface_ce;
zend_class_entry *zendframework_db_sql_predicate_predicateinterface_ce;
zend_class_entry *zendframework_db_sql_preparablesqlinterface_ce;
zend_class_entry *zendframework_db_tablegateway_tablegatewayinterface_ce;
zend_class_entry *zendframework_di_definition_partialmarker_ce;
zend_class_entry *zendframework_di_dependencyinjectioninterface_ce;
zend_class_entry *zendframework_eventmanager_eventmanagerinterface_ce;
zend_class_entry *zendframework_eventmanager_sharedeventaggregateawareinterface_ce;
zend_class_entry *zendframework_eventmanager_sharedeventmanagerinterface_ce;
zend_class_entry *zendframework_eventmanager_sharedlisteneraggregateinterface_ce;
zend_class_entry *zendframework_filter_compress_compressionalgorithminterface_ce;
zend_class_entry *zendframework_filter_encrypt_encryptionalgorithminterface_ce;
zend_class_entry *zendframework_filter_filterinterface_ce;
zend_class_entry *zendframework_form_elementattributeremovalinterface_ce;
zend_class_entry *zendframework_form_fieldsetprepareawareinterface_ce;
zend_class_entry *zendframework_form_forminterface_ce;
zend_class_entry *zendframework_form_labelawareinterface_ce;
zend_class_entry *zendframework_http_client_adapter_adapterinterface_ce;
zend_class_entry *zendframework_http_client_adapter_streaminterface_ce;
zend_class_entry *zendframework_http_header_multipleheaderinterface_ce;
zend_class_entry *zendframework_i18n_translator_loader_fileloaderinterface_ce;
zend_class_entry *zendframework_i18n_translator_loader_remoteloaderinterface_ce;
zend_class_entry *zendframework_i18n_translator_translatorawareinterface_ce;
zend_class_entry *zendframework_i18n_translator_translatorinterface_ce;
zend_class_entry *zendframework_inputfilter_emptycontextinterface_ce;
zend_class_entry *zendframework_inputfilter_inputfilterawareinterface_ce;
zend_class_entry *zendframework_inputfilter_inputfilterinterface_ce;
zend_class_entry *zendframework_inputfilter_inputfilterproviderinterface_ce;
zend_class_entry *zendframework_inputfilter_inputinterface_ce;
zend_class_entry *zendframework_inputfilter_inputproviderinterface_ce;
zend_class_entry *zendframework_inputfilter_replaceableinputinterface_ce;
zend_class_entry *zendframework_inputfilter_unknowninputscapableinterface_ce;
zend_class_entry *zendframework_ldap_node_schema_attributetype_attributetypeinterface_ce;
zend_class_entry *zendframework_ldap_node_schema_objectclass_objectclassinterface_ce;
zend_class_entry *zendframework_loader_pluginclasslocator_ce;
zend_class_entry *zendframework_loader_splautoloader_ce;
zend_class_entry *zendframework_log_filter_filterinterface_ce;
zend_class_entry *zendframework_log_formatter_formatterinterface_ce;
zend_class_entry *zendframework_log_loggerawareinterface_ce;
zend_class_entry *zendframework_log_loggerinterface_ce;
zend_class_entry *zendframework_log_processor_processorinterface_ce;
zend_class_entry *zendframework_log_writer_chromephp_chromephpinterface_ce;
zend_class_entry *zendframework_log_writer_firephp_firephpinterface_ce;
zend_class_entry *zendframework_log_writer_writerinterface_ce;
zend_class_entry *zendframework_mail_address_addressinterface_ce;
zend_class_entry *zendframework_mail_header_multipleheadersinterface_ce;
zend_class_entry *zendframework_mail_header_structuredinterface_ce;
zend_class_entry *zendframework_mail_header_unstructuredinterface_ce;
zend_class_entry *zendframework_mail_storage_folder_folderinterface_ce;
zend_class_entry *zendframework_mail_storage_message_messageinterface_ce;
zend_class_entry *zendframework_mail_storage_part_partinterface_ce;
zend_class_entry *zendframework_mail_storage_writable_writableinterface_ce;
zend_class_entry *zendframework_mail_transport_transportinterface_ce;
zend_class_entry *zendframework_math_biginteger_adapter_adapterinterface_ce;
zend_class_entry *zendframework_memory_container_containerinterface_ce;
zend_class_entry *zendframework_modulemanager_feature_autoloaderproviderinterface_ce;
zend_class_entry *zendframework_modulemanager_feature_bootstraplistenerinterface_ce;
zend_class_entry *zendframework_modulemanager_feature_configproviderinterface_ce;
zend_class_entry *zendframework_modulemanager_feature_consolebannerproviderinterface_ce;
zend_class_entry *zendframework_modulemanager_feature_consoleusageproviderinterface_ce;
zend_class_entry *zendframework_modulemanager_feature_controllerpluginproviderinterface_ce;
zend_class_entry *zendframework_modulemanager_feature_controllerproviderinterface_ce;
zend_class_entry *zendframework_modulemanager_feature_dependencyindicatorinterface_ce;
zend_class_entry *zendframework_modulemanager_feature_filterproviderinterface_ce;
zend_class_entry *zendframework_modulemanager_feature_formelementproviderinterface_ce;
zend_class_entry *zendframework_modulemanager_feature_hydratorproviderinterface_ce;
zend_class_entry *zendframework_modulemanager_feature_initproviderinterface_ce;
zend_class_entry *zendframework_modulemanager_feature_inputfilterproviderinterface_ce;
zend_class_entry *zendframework_modulemanager_feature_locatorregisteredinterface_ce;
zend_class_entry *zendframework_modulemanager_feature_logprocessorproviderinterface_ce;
zend_class_entry *zendframework_modulemanager_feature_logwriterproviderinterface_ce;
zend_class_entry *zendframework_modulemanager_feature_routeproviderinterface_ce;
zend_class_entry *zendframework_modulemanager_feature_serializerproviderinterface_ce;
zend_class_entry *zendframework_modulemanager_feature_serviceproviderinterface_ce;
zend_class_entry *zendframework_modulemanager_feature_validatorproviderinterface_ce;
zend_class_entry *zendframework_modulemanager_feature_viewhelperproviderinterface_ce;
zend_class_entry *zendframework_modulemanager_listener_configmergerinterface_ce;
zend_class_entry *zendframework_modulemanager_listener_servicelistenerinterface_ce;
zend_class_entry *zendframework_mvc_applicationinterface_ce;
zend_class_entry *zendframework_mvc_controller_plugin_plugininterface_ce;
zend_class_entry *zendframework_mvc_injectapplicationeventinterface_ce;
zend_class_entry *zendframework_mvc_responsesender_responsesenderinterface_ce;
zend_class_entry *zendframework_mvc_router_console_routeinterface_ce;
zend_class_entry *zendframework_mvc_router_http_routeinterface_ce;
zend_class_entry *zendframework_mvc_router_routestackinterface_ce;
zend_class_entry *zendframework_paginator_adapter_adapterinterface_ce;
zend_class_entry *zendframework_paginator_adapteraggregateinterface_ce;
zend_class_entry *zendframework_paginator_scrollingstyle_scrollingstyleinterface_ce;
zend_class_entry *zendframework_permissions_acl_aclinterface_ce;
zend_class_entry *zendframework_permissions_acl_assertion_assertioninterface_ce;
zend_class_entry *zendframework_permissions_rbac_assertioninterface_ce;
zend_class_entry *zendframework_permissions_rbac_roleinterface_ce;
zend_class_entry *zendframework_progressbar_upload_uploadhandlerinterface_ce;
zend_class_entry *zendframework_serializer_adapter_adapterinterface_ce;
zend_class_entry *zendframework_server_client_ce;
zend_class_entry *zendframework_server_server_ce;
zend_class_entry *zendframework_servicemanager_abstractfactoryinterface_ce;
zend_class_entry *zendframework_servicemanager_configinterface_ce;
zend_class_entry *zendframework_servicemanager_delegatorfactoryinterface_ce;
zend_class_entry *zendframework_servicemanager_factoryinterface_ce;
zend_class_entry *zendframework_servicemanager_initializerinterface_ce;
zend_class_entry *zendframework_servicemanager_mutablecreationoptionsinterface_ce;
zend_class_entry *zendframework_servicemanager_servicelocatorawareinterface_ce;
zend_class_entry *zendframework_servicemanager_servicelocatorinterface_ce;
zend_class_entry *zendframework_servicemanager_servicemanagerawareinterface_ce;
zend_class_entry *zendframework_session_config_configinterface_ce;
zend_class_entry *zendframework_session_managerinterface_ce;
zend_class_entry *zendframework_session_savehandler_savehandlerinterface_ce;
zend_class_entry *zendframework_session_storage_storageinitializationinterface_ce;
zend_class_entry *zendframework_session_storage_storageinterface_ce;
zend_class_entry *zendframework_session_validator_validatorinterface_ce;
zend_class_entry *zendframework_soap_wsdl_complextypestrategy_complextypestrategyinterface_ce;
zend_class_entry *zendframework_stdlib_arrayserializableinterface_ce;
zend_class_entry *zendframework_stdlib_dispatchableinterface_ce;
zend_class_entry *zendframework_stdlib_hydrator_filter_filterinterface_ce;
zend_class_entry *zendframework_stdlib_hydrator_filterenabledinterface_ce;
zend_class_entry *zendframework_stdlib_hydrator_hydratorawareinterface_ce;
zend_class_entry *zendframework_stdlib_hydrator_hydratorinterface_ce;
zend_class_entry *zendframework_stdlib_hydrator_hydratoroptionsinterface_ce;
zend_class_entry *zendframework_stdlib_hydrator_namingstrategy_namingstrategyinterface_ce;
zend_class_entry *zendframework_stdlib_hydrator_namingstrategyenabledinterface_ce;
zend_class_entry *zendframework_stdlib_hydrator_strategy_strategyinterface_ce;
zend_class_entry *zendframework_stdlib_hydrator_strategyenabledinterface_ce;
zend_class_entry *zendframework_stdlib_initializableinterface_ce;
zend_class_entry *zendframework_stdlib_jsonserializable_ce;
zend_class_entry *zendframework_stdlib_jsonserializable_phplegacycompatibility_ce;
zend_class_entry *zendframework_stdlib_parameterobjectinterface_ce;
zend_class_entry *zendframework_stdlib_requestinterface_ce;
zend_class_entry *zendframework_stdlib_responseinterface_ce;
zend_class_entry *zendframework_stdlib_stringwrapper_stringwrapperinterface_ce;
zend_class_entry *zendframework_tag_cloud_decorator_decoratorinterface_ce;
zend_class_entry *zendframework_tag_taggableinterface_ce;
zend_class_entry *zendframework_text_table_decorator_decoratorinterface_ce;
zend_class_entry *zendframework_uri_uriinterface_ce;
zend_class_entry *zendframework_validator_barcode_adapterinterface_ce;
zend_class_entry *zendframework_validator_translator_translatorawareinterface_ce;
zend_class_entry *zendframework_validator_translator_translatorinterface_ce;
zend_class_entry *zendframework_validator_validatorpluginmanagerawareinterface_ce;
zend_class_entry *zendframework_view_helper_navigation_helperinterface_ce;
zend_class_entry *zendframework_view_model_clearablemodelinterface_ce;
zend_class_entry *zendframework_view_model_modelinterface_ce;
zend_class_entry *zendframework_view_model_retrievablechildreninterface_ce;
zend_class_entry *zendframework_view_renderer_rendererinterface_ce;
zend_class_entry *zendframework_view_renderer_treerendererinterface_ce;
zend_class_entry *zendframework_view_resolver_resolverinterface_ce;
zend_class_entry *zendframework_xmlrpc_generator_generatorinterface_ce;
zend_class_entry *zendframework_http_exception_runtimeexception_ce;
zend_class_entry *zendframework_db_exception_runtimeexception_ce;
zend_class_entry *zendframework_authentication_exception_invalidargumentexception_ce;
zend_class_entry *zendframework_authentication_exception_runtimeexception_ce;
zend_class_entry *zendframework_db_exception_invalidargumentexception_ce;
zend_class_entry *zendframework_http_client_exception_runtimeexception_ce;
zend_class_entry *zendframework_http_exception_invalidargumentexception_ce;
zend_class_entry *zendframework_json_exception_runtimeexception_ce;
zend_class_entry *zendframework_mail_exception_invalidargumentexception_ce;
zend_class_entry *zendframework_mail_exception_runtimeexception_ce;
zend_class_entry *zendframework_xmlrpc_exception_invalidargumentexception_ce;
zend_class_entry *zendframework_xmlrpc_exception_runtimeexception_ce;
zend_class_entry *zendframework_crypt_exception_invalidargumentexception_ce;
zend_class_entry *zendframework_crypt_exception_runtimeexception_ce;
zend_class_entry *zendframework_db_exception_unexpectedvalueexception_ce;
zend_class_entry *zendframework_file_exception_runtimeexception_ce;
zend_class_entry *zendframework_http_exception_outofrangeexception_ce;
zend_class_entry *zendframework_math_exception_runtimeexception_ce;
zend_class_entry *zendframework_servicemanager_exception_runtimeexception_ce;
zend_class_entry *zendframework_cache_exception_runtimeexception_ce;
zend_class_entry *zendframework_di_exception_invalidargumentexception_ce;
zend_class_entry *zendframework_authentication_adapter_exception_invalidargumentexception_ce;
zend_class_entry *zendframework_authentication_adapter_exception_runtimeexception_ce;
zend_class_entry *zendframework_captcha_exception_runtimeexception_ce;
zend_class_entry *zendframework_code_exception_invalidargumentexception_ce;
zend_class_entry *zendframework_code_exception_runtimeexception_ce;
zend_class_entry *zendframework_http_client_adapter_exception_runtimeexception_ce;
zend_class_entry *zendframework_loader_exception_domainexception_ce;
zend_class_entry *zendframework_modulemanager_exception_runtimeexception_ce;
zend_class_entry *zendframework_mvc_exception_runtimeexception_ce;
zend_class_entry *zendframework_progressbar_exception_runtimeexception_ce;
zend_class_entry *zendframework_text_exception_invalidargumentexception_ce;
zend_class_entry *zendframework_text_exception_unexpectedvalueexception_ce;
zend_class_entry *zendframework_uri_exception_invalidargumentexception_ce;
zend_class_entry *zendframework_xmlrpc_exception_badmethodcallexception_ce;
zend_class_entry *zendframework_authentication_exception_unexpectedvalueexception_ce;
zend_class_entry *zendframework_captcha_exception_invalidargumentexception_ce;
zend_class_entry *zendframework_code_exception_badmethodcallexception_ce;
zend_class_entry *zendframework_db_adapter_exception_runtimeexception_ce;
zend_class_entry *zendframework_db_adapter_exception_unexpectedvalueexception_ce;
zend_class_entry *zendframework_db_exception_errorexception_ce;
zend_class_entry *zendframework_eventmanager_event_ce;
zend_class_entry *zendframework_eventmanager_exception_domainexception_ce;
zend_class_entry *zendframework_file_exception_badmethodcallexception_ce;
zend_class_entry *zendframework_file_exception_invalidargumentexception_ce;
zend_class_entry *zendframework_file_transfer_exception_runtimeexception_ce;
zend_class_entry *zendframework_filter_exception_runtimeexception_ce;
zend_class_entry *zendframework_form_exception_domainexception_ce;
zend_class_entry *zendframework_form_exception_invalidargumentexception_ce;
zend_class_entry *zendframework_http_client_exception_invalidargumentexception_ce;
zend_class_entry *zendframework_http_client_exception_outofrangeexception_ce;
zend_class_entry *zendframework_i18n_exception_runtimeexception_ce;
zend_class_entry *zendframework_json_exception_badmethodcallexception_ce;
zend_class_entry *zendframework_json_exception_invalidargumentexception_ce;
zend_class_entry *zendframework_json_server_exception_runtimeexception_ce;
zend_class_entry *zendframework_ldap_exception_invalidargumentexception_ce;
zend_class_entry *zendframework_mail_exception_badmethodcallexception_ce;
zend_class_entry *zendframework_mail_exception_domainexception_ce;
zend_class_entry *zendframework_mail_exception_outofboundsexception_ce;
zend_class_entry *zendframework_mail_storage_exception_invalidargumentexception_ce;
zend_class_entry *zendframework_mail_storage_exception_runtimeexception_ce;
zend_class_entry *zendframework_math_biginteger_exception_runtimeexception_ce;
zend_class_entry *zendframework_math_exception_invalidargumentexception_ce;
zend_class_entry *zendframework_modulemanager_exception_invalidargumentexception_ce;
zend_class_entry *zendframework_mvc_exception_invalidargumentexception_ce;
zend_class_entry *zendframework_paginator_exception_invalidargumentexception_ce;
zend_class_entry *zendframework_paginator_exception_runtimeexception_ce;
zend_class_entry *zendframework_paginator_exception_unexpectedvalueexception_ce;
zend_class_entry *zendframework_progressbar_exception_invalidargumentexception_ce;
zend_class_entry *zendframework_serializer_exception_runtimeexception_ce;
zend_class_entry *zendframework_server_exception_badmethodcallexception_ce;
zend_class_entry *zendframework_server_exception_invalidargumentexception_ce;
zend_class_entry *zendframework_server_exception_runtimeexception_ce;
zend_class_entry *zendframework_servicemanager_exception_invalidargumentexception_ce;
zend_class_entry *zendframework_stdlib_exception_domainexception_ce;
zend_class_entry *zendframework_stdlib_exception_runtimeexception_ce;
zend_class_entry *zendframework_stdlib_splpriorityqueue_ce;
zend_class_entry *zendframework_tag_exception_invalidargumentexception_ce;
zend_class_entry *zendframework_text_exception_outofboundsexception_ce;
zend_class_entry *zendframework_text_exception_overflowexception_ce;
zend_class_entry *zendframework_text_exception_runtimeexception_ce;
zend_class_entry *zendframework_validator_exception_invalidargumentexception_ce;
zend_class_entry *zendframework_validator_exception_runtimeexception_ce;
zend_class_entry *zendframework_xmlrpc_client_exception_invalidargumentexception_ce;
zend_class_entry *zendframework_xmlrpc_client_exception_runtimeexception_ce;
zend_class_entry *zendframework_authentication_adapter_dbtable_exception_invalidargumentexception_ce;
zend_class_entry *zendframework_authentication_adapter_dbtable_exception_runtimeexception_ce;
zend_class_entry *zendframework_authentication_adapter_exception_unexpectedvalueexception_ce;
zend_class_entry *zendframework_authentication_adapter_http_exception_invalidargumentexception_ce;
zend_class_entry *zendframework_authentication_adapter_http_exception_runtimeexception_ce;
zend_class_entry *zendframework_cache_exception_badmethodcallexception_ce;
zend_class_entry *zendframework_cache_exception_extensionnotloadedexception_ce;
zend_class_entry *zendframework_cache_exception_invalidargumentexception_ce;
zend_class_entry *zendframework_cache_exception_logicexception_ce;
zend_class_entry *zendframework_cache_exception_missingdependencyexception_ce;
zend_class_entry *zendframework_cache_exception_missingkeyexception_ce;
zend_class_entry *zendframework_cache_exception_outofspaceexception_ce;
zend_class_entry *zendframework_cache_exception_unexpectedvalueexception_ce;
zend_class_entry *zendframework_cache_exception_unsupportedmethodcallexception_ce;
zend_class_entry *zendframework_captcha_exception_domainexception_ce;
zend_class_entry *zendframework_captcha_exception_extensionnotloadedexception_ce;
zend_class_entry *zendframework_captcha_exception_imagenotloadableexception_ce;
zend_class_entry *zendframework_captcha_exception_nofontprovidedexception_ce;
zend_class_entry *zendframework_code_generator_exception_invalidargumentexception_ce;
zend_class_entry *zendframework_code_generator_exception_runtimeexception_ce;
zend_class_entry *zendframework_code_reflection_exception_badmethodcallexception_ce;
zend_class_entry *zendframework_code_reflection_exception_invalidargumentexception_ce;
zend_class_entry *zendframework_code_reflection_exception_runtimeexception_ce;
zend_class_entry *zendframework_config_exception_invalidargumentexception_ce;
zend_class_entry *zendframework_config_exception_runtimeexception_ce;
zend_class_entry *zendframework_console_exception_badmethodcallexception_ce;
zend_class_entry *zendframework_console_exception_invalidargumentexception_ce;
zend_class_entry *zendframework_console_exception_runtimeexception_ce;
zend_class_entry *zendframework_crypt_key_derivation_exception_invalidargumentexception_ce;
zend_class_entry *zendframework_crypt_key_derivation_exception_runtimeexception_ce;
zend_class_entry *zendframework_crypt_password_exception_invalidargumentexception_ce;
zend_class_entry *zendframework_crypt_password_exception_runtimeexception_ce;
zend_class_entry *zendframework_crypt_publickey_rsa_exception_invalidargumentexception_ce;
zend_class_entry *zendframework_crypt_publickey_rsa_exception_runtimeexception_ce;
zend_class_entry *zendframework_crypt_symmetric_exception_invalidargumentexception_ce;
zend_class_entry *zendframework_crypt_symmetric_exception_runtimeexception_ce;
zend_class_entry *zendframework_db_adapter_exception_errorexception_ce;
zend_class_entry *zendframework_db_adapter_exception_invalidargumentexception_ce;
zend_class_entry *zendframework_db_adapter_exception_invalidconnectionparametersexception_ce;
zend_class_entry *zendframework_db_adapter_exception_invalidqueryexception_ce;
zend_class_entry *zendframework_db_resultset_exception_invalidargumentexception_ce;
zend_class_entry *zendframework_db_resultset_exception_runtimeexception_ce;
zend_class_entry *zendframework_db_rowgateway_exception_invalidargumentexception_ce;
zend_class_entry *zendframework_db_rowgateway_exception_runtimeexception_ce;
zend_class_entry *zendframework_db_sql_exception_invalidargumentexception_ce;
zend_class_entry *zendframework_db_sql_exception_runtimeexception_ce;
zend_class_entry *zendframework_db_tablegateway_exception_invalidargumentexception_ce;
zend_class_entry *zendframework_db_tablegateway_exception_runtimeexception_ce;
zend_class_entry *zendframework_di_definition_annotation_inject_ce;
zend_class_entry *zendframework_di_definition_annotation_instantiator_ce;
zend_class_entry *zendframework_di_definition_arraydefinition_ce;
zend_class_entry *zendframework_di_definition_builder_injectionmethod_ce;
zend_class_entry *zendframework_di_definition_builder_phpclass_ce;
zend_class_entry *zendframework_di_di_ce;
zend_class_entry *zendframework_di_exception_circulardependencyexception_ce;
zend_class_entry *zendframework_di_exception_classnotfoundexception_ce;
zend_class_entry *zendframework_di_exception_invalidcallbackexception_ce;
zend_class_entry *zendframework_di_exception_invalidparamnameexception_ce;
zend_class_entry *zendframework_di_exception_invalidpositionexception_ce;
zend_class_entry *zendframework_di_exception_missingpropertyexception_ce;
zend_class_entry *zendframework_di_exception_runtimeexception_ce;
zend_class_entry *zendframework_di_exception_undefinedreferenceexception_ce;
zend_class_entry *zendframework_di_servicelocator_ce;
zend_class_entry *zendframework_dom_exception_badmethodcallexception_ce;
zend_class_entry *zendframework_dom_exception_runtimeexception_ce;
zend_class_entry *zendframework_escaper_exception_invalidargumentexception_ce;
zend_class_entry *zendframework_escaper_exception_runtimeexception_ce;
zend_class_entry *zendframework_eventmanager_exception_invalidargumentexception_ce;
zend_class_entry *zendframework_eventmanager_exception_invalidcallbackexception_ce;
zend_class_entry *zendframework_eventmanager_filter_filteriterator_ce;
zend_class_entry *zendframework_eventmanager_filterchain_ce;
zend_class_entry *zendframework_eventmanager_responsecollection_ce;
zend_class_entry *zendframework_file_transfer_exception_badmethodcallexception_ce;
zend_class_entry *zendframework_file_transfer_exception_invalidargumentexception_ce;
zend_class_entry *zendframework_file_transfer_exception_phpenvironmentexception_ce;
zend_class_entry *zendframework_filter_exception_badmethodcallexception_ce;
zend_class_entry *zendframework_filter_exception_domainexception_ce;
zend_class_entry *zendframework_filter_exception_extensionnotloadedexception_ce;
zend_class_entry *zendframework_filter_exception_invalidargumentexception_ce;
zend_class_entry *zendframework_form_exception_badmethodcallexception_ce;
zend_class_entry *zendframework_form_exception_extensionnotloadedexception_ce;
zend_class_entry *zendframework_form_exception_invalidelementexception_ce;
zend_class_entry *zendframework_form_exception_unexpectedvalueexception_ce;
zend_class_entry *zendframework_http_client_adapter_exception_initializationexception_ce;
zend_class_entry *zendframework_http_client_adapter_exception_invalidargumentexception_ce;
zend_class_entry *zendframework_http_client_adapter_exception_outofrangeexception_ce;
zend_class_entry *zendframework_http_client_adapter_exception_timeoutexception_ce;
zend_class_entry *zendframework_http_header_exception_domainexception_ce;
zend_class_entry *zendframework_http_header_exception_invalidargumentexception_ce;
zend_class_entry *zendframework_http_header_exception_runtimeexception_ce;
zend_class_entry *zendframework_i18n_exception_extensionnotloadedexception_ce;
zend_class_entry *zendframework_i18n_exception_invalidargumentexception_ce;
zend_class_entry *zendframework_i18n_exception_outofboundsexception_ce;
zend_class_entry *zendframework_i18n_exception_parseexception_ce;
zend_class_entry *zendframework_i18n_exception_rangeexception_ce;
zend_class_entry *zendframework_inputfilter_exception_invalidargumentexception_ce;
zend_class_entry *zendframework_inputfilter_exception_runtimeexception_ce;
zend_class_entry *zendframework_json_exception_recursionexception_ce;
zend_class_entry *zendframework_json_server_exception_errorexception_ce;
zend_class_entry *zendframework_json_server_exception_httpexception_ce;
zend_class_entry *zendframework_json_server_exception_invalidargumentexception_ce;
zend_class_entry *zendframework_ldap_converter_exception_converterexception_ce;
zend_class_entry *zendframework_ldap_converter_exception_invalidargumentexception_ce;
zend_class_entry *zendframework_ldap_converter_exception_unexpectedvalueexception_ce;
zend_class_entry *zendframework_ldap_exception_badmethodcallexception_ce;
zend_class_entry *zendframework_ldap_exception_ldapexception_ce;
zend_class_entry *zendframework_ldap_filter_exception_filterexception_ce;
zend_class_entry *zendframework_loader_exception_badmethodcallexception_ce;
zend_class_entry *zendframework_loader_exception_invalidargumentexception_ce;
zend_class_entry *zendframework_loader_exception_invalidpathexception_ce;
zend_class_entry *zendframework_loader_exception_missingresourcenamespaceexception_ce;
zend_class_entry *zendframework_loader_exception_pluginloaderexception_ce;
zend_class_entry *zendframework_loader_exception_runtimeexception_ce;
zend_class_entry *zendframework_loader_exception_securityexception_ce;
zend_class_entry *zendframework_log_exception_invalidargumentexception_ce;
zend_class_entry *zendframework_log_exception_runtimeexception_ce;
zend_class_entry *zendframework_mail_header_exception_badmethodcallexception_ce;
zend_class_entry *zendframework_mail_header_exception_invalidargumentexception_ce;
zend_class_entry *zendframework_mail_header_exception_runtimeexception_ce;
zend_class_entry *zendframework_mail_protocol_exception_invalidargumentexception_ce;
zend_class_entry *zendframework_mail_protocol_exception_runtimeexception_ce;
zend_class_entry *zendframework_mail_storage_exception_outofboundsexception_ce;
zend_class_entry *zendframework_mail_storage_part_exception_invalidargumentexception_ce;
zend_class_entry *zendframework_mail_storage_part_exception_runtimeexception_ce;
zend_class_entry *zendframework_mail_transport_exception_domainexception_ce;
zend_class_entry *zendframework_mail_transport_exception_invalidargumentexception_ce;
zend_class_entry *zendframework_mail_transport_exception_runtimeexception_ce;
zend_class_entry *zendframework_math_biginteger_exception_divisionbyzeroexception_ce;
zend_class_entry *zendframework_math_biginteger_exception_invalidargumentexception_ce;
zend_class_entry *zendframework_math_exception_domainexception_ce;
zend_class_entry *zendframework_memory_exception_invalidargumentexception_ce;
zend_class_entry *zendframework_memory_exception_runtimeexception_ce;
zend_class_entry *zendframework_mime_exception_runtimeexception_ce;
zend_class_entry *zendframework_modulemanager_exception_missingdependencymoduleexception_ce;
zend_class_entry *zendframework_modulemanager_listener_exception_invalidargumentexception_ce;
zend_class_entry *zendframework_modulemanager_listener_exception_runtimeexception_ce;
zend_class_entry *zendframework_modulemanager_moduleevent_ce;
zend_class_entry *zendframework_modulemanager_modulemanager_ce;
zend_class_entry *zendframework_mvc_exception_badmethodcallexception_ce;
zend_class_entry *zendframework_mvc_exception_domainexception_ce;
zend_class_entry *zendframework_mvc_exception_invalidcontrollerexception_ce;
zend_class_entry *zendframework_mvc_exception_invalidpluginexception_ce;
zend_class_entry *zendframework_mvc_exception_missinglocatorexception_ce;
zend_class_entry *zendframework_mvc_router_exception_invalidargumentexception_ce;
zend_class_entry *zendframework_mvc_router_exception_runtimeexception_ce;
zend_class_entry *zendframework_navigation_exception_badmethodcallexception_ce;
zend_class_entry *zendframework_navigation_exception_domainexception_ce;
zend_class_entry *zendframework_navigation_exception_invalidargumentexception_ce;
zend_class_entry *zendframework_navigation_exception_outofboundsexception_ce;
zend_class_entry *zendframework_paginator_adapter_exception_invalidargumentexception_ce;
zend_class_entry *zendframework_paginator_adapter_exception_runtimeexception_ce;
zend_class_entry *zendframework_paginator_adapter_exception_unexpectedvalueexception_ce;
zend_class_entry *zendframework_permissions_acl_assertion_exception_invalidassertionexception_ce;
zend_class_entry *zendframework_permissions_acl_exception_invalidargumentexception_ce;
zend_class_entry *zendframework_permissions_acl_exception_runtimeexception_ce;
zend_class_entry *zendframework_permissions_acl_resource_genericresource_ce;
zend_class_entry *zendframework_permissions_acl_role_genericrole_ce;
zend_class_entry *zendframework_permissions_acl_role_registry_ce;
zend_class_entry *zendframework_permissions_rbac_exception_invalidargumentexception_ce;
zend_class_entry *zendframework_progressbar_adapter_exception_invalidargumentexception_ce;
zend_class_entry *zendframework_progressbar_adapter_exception_runtimeexception_ce;
zend_class_entry *zendframework_progressbar_exception_outofrangeexception_ce;
zend_class_entry *zendframework_progressbar_exception_phpenvironmentexception_ce;
zend_class_entry *zendframework_serializer_exception_extensionnotloadedexception_ce;
zend_class_entry *zendframework_serializer_exception_invalidargumentexception_ce;
zend_class_entry *zendframework_server_reflection_exception_badmethodcallexception_ce;
zend_class_entry *zendframework_server_reflection_exception_invalidargumentexception_ce;
zend_class_entry *zendframework_server_reflection_exception_runtimeexception_ce;
zend_class_entry *zendframework_servicemanager_exception_circulardependencyfoundexception_ce;
zend_class_entry *zendframework_servicemanager_exception_circularreferenceexception_ce;
zend_class_entry *zendframework_servicemanager_exception_invalidservicenameexception_ce;
zend_class_entry *zendframework_servicemanager_exception_servicenotcreatedexception_ce;
zend_class_entry *zendframework_servicemanager_exception_servicenotfoundexception_ce;
zend_class_entry *zendframework_session_exception_badmethodcallexception_ce;
zend_class_entry *zendframework_session_exception_invalidargumentexception_ce;
zend_class_entry *zendframework_session_exception_runtimeexception_ce;
zend_class_entry *zendframework_soap_exception_badmethodcallexception_ce;
zend_class_entry *zendframework_soap_exception_invalidargumentexception_ce;
zend_class_entry *zendframework_soap_exception_runtimeexception_ce;
zend_class_entry *zendframework_soap_exception_unexpectedvalueexception_ce;
zend_class_entry *zendframework_stdlib_arraystack_ce;
zend_class_entry *zendframework_stdlib_arrayutils_ce;
zend_class_entry *zendframework_stdlib_callbackhandler_ce;
zend_class_entry *zendframework_stdlib_errorhandler_ce;
zend_class_entry *zendframework_stdlib_exception_badmethodcallexception_ce;
zend_class_entry *zendframework_stdlib_exception_extensionnotloadedexception_ce;
zend_class_entry *zendframework_stdlib_exception_invalidargumentexception_ce;
zend_class_entry *zendframework_stdlib_exception_invalidcallbackexception_ce;
zend_class_entry *zendframework_stdlib_exception_logicexception_ce;
zend_class_entry *zendframework_stdlib_message_ce;
zend_class_entry *zendframework_stdlib_parameters_ce;
zend_class_entry *zendframework_stdlib_prioritylist_ce;
zend_class_entry *zendframework_stdlib_priorityqueue_ce;
zend_class_entry *zendframework_stdlib_splqueue_ce;
zend_class_entry *zendframework_stdlib_splstack_ce;
zend_class_entry *zendframework_stdlib_stringutils_ce;
zend_class_entry *zendframework_tag_cloud_decorator_exception_invalidargumentexception_ce;
zend_class_entry *zendframework_tag_exception_invalidattributenameexception_ce;
zend_class_entry *zendframework_tag_exception_invalidelementnameexception_ce;
zend_class_entry *zendframework_tag_exception_outofboundsexception_ce;
zend_class_entry *zendframework_text_figlet_exception_invalidargumentexception_ce;
zend_class_entry *zendframework_text_figlet_exception_runtimeexception_ce;
zend_class_entry *zendframework_text_figlet_exception_unexpectedvalueexception_ce;
zend_class_entry *zendframework_text_table_exception_invalidargumentexception_ce;
zend_class_entry *zendframework_text_table_exception_invaliddecoratorexception_ce;
zend_class_entry *zendframework_text_table_exception_outofboundsexception_ce;
zend_class_entry *zendframework_text_table_exception_overflowexception_ce;
zend_class_entry *zendframework_text_table_exception_unexpectedvalueexception_ce;
zend_class_entry *zendframework_uri_exception_invaliduriexception_ce;
zend_class_entry *zendframework_uri_exception_invaliduripartexception_ce;
zend_class_entry *zendframework_validator_exception_badmethodcallexception_ce;
zend_class_entry *zendframework_validator_exception_extensionnotloadedexception_ce;
zend_class_entry *zendframework_validator_exception_invalidmagicmimefileexception_ce;
zend_class_entry *zendframework_view_exception_badmethodcallexception_ce;
zend_class_entry *zendframework_view_exception_domainexception_ce;
zend_class_entry *zendframework_view_exception_invalidargumentexception_ce;
zend_class_entry *zendframework_view_exception_invalidhelperexception_ce;
zend_class_entry *zendframework_view_exception_runtimeexception_ce;
zend_class_entry *zendframework_view_exception_unexpectedvalueexception_ce;
zend_class_entry *zendframework_xmlrpc_client_exception_faultexception_ce;
zend_class_entry *zendframework_xmlrpc_client_exception_httpexception_ce;
zend_class_entry *zendframework_xmlrpc_client_exception_introspectexception_ce;
zend_class_entry *zendframework_xmlrpc_exception_valueexception_ce;
zend_class_entry *zendframework_xmlrpc_server_exception_badmethodcallexception_ce;
zend_class_entry *zendframework_xmlrpc_server_exception_invalidargumentexception_ce;
zend_class_entry *zendframework_xmlrpc_server_exception_runtimeexception_ce;

ZEND_DECLARE_MODULE_GLOBALS(zendframework)

#define ZEPHIR_NUM_PREALLOCATED_FRAMES 25

void zephir_initialize_memory(zend_zephir_globals_def *zephir_globals_ptr TSRMLS_DC)
{
	zephir_memory_entry *start;
	size_t i;

	start = (zephir_memory_entry *) pecalloc(ZEPHIR_NUM_PREALLOCATED_FRAMES, sizeof(zephir_memory_entry), 1);
/* pecalloc() will take care of these members for every frame
	start->pointer      = 0;
	start->hash_pointer = 0;
	start->prev = NULL;
	start->next = NULL;
*/
	for (i = 0; i < ZEPHIR_NUM_PREALLOCATED_FRAMES; ++i) {
		start[i].addresses       = pecalloc(24, sizeof(zval*), 1);
		start[i].capacity        = 24;
		start[i].hash_addresses  = pecalloc(8, sizeof(zval*), 1);
		start[i].hash_capacity   = 8;

#ifndef ZEPHIR_RELEASE
		start[i].permanent = 1;
#endif
	}

	start[0].next = &start[1];
	start[ZEPHIR_NUM_PREALLOCATED_FRAMES - 1].prev = &start[ZEPHIR_NUM_PREALLOCATED_FRAMES - 2];

	for (i = 1; i < ZEPHIR_NUM_PREALLOCATED_FRAMES - 1; ++i) {
		start[i].next = &start[i + 1];
		start[i].prev = &start[i - 1];
	}

	zephir_globals_ptr->start_memory = start;
	zephir_globals_ptr->end_memory   = start + ZEPHIR_NUM_PREALLOCATED_FRAMES;

	zephir_globals_ptr->fcache = pemalloc(sizeof(HashTable), 1);
	zend_hash_init(zephir_globals_ptr->fcache, 128, NULL, NULL, 1); // zephir_fcall_cache_dtor

	/* 'Allocator sizeof operand mismatch' warning can be safely ignored */
	ALLOC_INIT_ZVAL(zephir_globals_ptr->global_null);
	Z_SET_REFCOUNT_P(zephir_globals_ptr->global_null, 2);

	/* 'Allocator sizeof operand mismatch' warning can be safely ignored */
	ALLOC_INIT_ZVAL(zephir_globals_ptr->global_false);
	Z_SET_REFCOUNT_P(zephir_globals_ptr->global_false, 2);
	ZVAL_FALSE(zephir_globals_ptr->global_false);

	/* 'Allocator sizeof operand mismatch' warning can be safely ignored */
	ALLOC_INIT_ZVAL(zephir_globals_ptr->global_true);
	Z_SET_REFCOUNT_P(zephir_globals_ptr->global_true, 2);
	ZVAL_TRUE(zephir_globals_ptr->global_true);

	zephir_globals_ptr->initialized = 1;
}

int zephir_cleanup_fcache(void *pDest TSRMLS_DC, int num_args, va_list args, zend_hash_key *hash_key)
{
	zephir_fcall_cache_entry **entry = (zephir_fcall_cache_entry**)pDest;
	zend_class_entry *scope;
	uint len = hash_key->nKeyLength;

	assert(hash_key->arKey != NULL);
	assert(hash_key->nKeyLength > 2 * sizeof(zend_class_entry**));

	memcpy(&scope, &hash_key->arKey[len - 2 * sizeof(zend_class_entry**)], sizeof(zend_class_entry*));

/*
#ifndef ZEPHIR_RELEASE
	{
		zend_class_entry *cls;
		memcpy(&cls, &hash_key->arKey[len - sizeof(zend_class_entry**)], sizeof(zend_class_entry*));

		fprintf(stderr, "func: %s, cls: %s, scope: %s [%u]\n", (*entry)->f->common.function_name, (cls ? cls->name : "N/A"), (scope ? scope->name : "N/A"), (uint)(*entry)->times);
	}
#endif
*/

#ifndef ZEPHIR_RELEASE
	if ((*entry)->f->type != ZEND_INTERNAL_FUNCTION || (scope && scope->type != ZEND_INTERNAL_CLASS)) {
		return ZEND_HASH_APPLY_REMOVE;
	}
#else
	if ((*entry)->type != ZEND_INTERNAL_FUNCTION || (scope && scope->type != ZEND_INTERNAL_CLASS)) {
		return ZEND_HASH_APPLY_REMOVE;
	}
#endif

#if PHP_VERSION_ID >= 50400
	if (scope && scope->type == ZEND_INTERNAL_CLASS && scope->info.internal.module->type != MODULE_PERSISTENT) {
		return ZEND_HASH_APPLY_REMOVE;
	}
#else
	if (scope && scope->type == ZEND_INTERNAL_CLASS && scope->module->type != MODULE_PERSISTENT) {
		return ZEND_HASH_APPLY_REMOVE;
	}
#endif

	return ZEND_HASH_APPLY_KEEP;
}

void zephir_deinitialize_memory(TSRMLS_D)
{
	size_t i;
	zend_zephir_globals_def *zephir_globals_ptr = ZEPHIR_VGLOBAL;

	if (zephir_globals_ptr->initialized != 1) {
		zephir_globals_ptr->initialized = 0;
		return;
	}

	if (zephir_globals_ptr->start_memory != NULL) {
		zephir_clean_restore_stack(TSRMLS_C);
	}

	zend_hash_apply_with_arguments(zephir_globals_ptr->fcache TSRMLS_CC, zephir_cleanup_fcache, 0);

#ifndef ZEPHIR_RELEASE
	assert(zephir_globals_ptr->start_memory != NULL);
#endif

	for (i = 0; i < ZEPHIR_NUM_PREALLOCATED_FRAMES; ++i) {
		pefree(zephir_globals_ptr->start_memory[i].hash_addresses, 1);
		pefree(zephir_globals_ptr->start_memory[i].addresses, 1);
	}

	pefree(zephir_globals_ptr->start_memory, 1);
	zephir_globals_ptr->start_memory = NULL;

	zend_hash_destroy(zephir_globals_ptr->fcache);
	pefree(zephir_globals_ptr->fcache, 1);
	zephir_globals_ptr->fcache = NULL;

	for (i = 0; i < 2; i++) {
		zval_ptr_dtor(&zephir_globals_ptr->global_null);
		zval_ptr_dtor(&zephir_globals_ptr->global_false);
		zval_ptr_dtor(&zephir_globals_ptr->global_true);
	}

	zephir_globals_ptr->initialized = 0;
}

static PHP_MINIT_FUNCTION(zendframework)
{
#if PHP_VERSION_ID < 50500
	char* old_lc_all = setlocale(LC_ALL, NULL);
	if (old_lc_all) {
		size_t len = strlen(old_lc_all);
		char *tmp  = calloc(len+1, 1);
		if (UNEXPECTED(!tmp)) {
			return FAILURE;
		}

		memcpy(tmp, old_lc_all, len);
		old_lc_all = tmp;
	}

	setlocale(LC_ALL, "C");
#endif

	ZEPHIR_INIT(ZendFramework_Http_Exception_ExceptionInterface);
	ZEPHIR_INIT(ZendFramework_Db_Exception_ExceptionInterface);
	ZEPHIR_INIT(ZendFramework_Authentication_Exception_ExceptionInterface);
	ZEPHIR_INIT(ZendFramework_XmlRpc_Exception_ExceptionInterface);
	ZEPHIR_INIT(ZendFramework_Mail_Exception_ExceptionInterface);
	ZEPHIR_INIT(ZendFramework_Http_Client_Exception_ExceptionInterface);
	ZEPHIR_INIT(ZendFramework_Math_Exception_ExceptionInterface);
	ZEPHIR_INIT(ZendFramework_Crypt_Exception_ExceptionInterface);
	ZEPHIR_INIT(ZendFramework_Text_Exception_ExceptionInterface);
	ZEPHIR_INIT(ZendFramework_Json_Exception_ExceptionInterface);
	ZEPHIR_INIT(ZendFramework_Cache_Exception_ExceptionInterface);
	ZEPHIR_INIT(ZendFramework_ServiceManager_Exception_ExceptionInterface);
	ZEPHIR_INIT(ZendFramework_Authentication_Adapter_Exception_ExceptionInterface);
	ZEPHIR_INIT(ZendFramework_Code_Exception_ExceptionInterface);
	ZEPHIR_INIT(ZendFramework_File_Exception_ExceptionInterface);
	ZEPHIR_INIT(ZendFramework_Paginator_Exception_ExceptionInterface);
	ZEPHIR_INIT(ZendFramework_ProgressBar_Exception_ExceptionInterface);
	ZEPHIR_INIT(ZendFramework_Mvc_Exception_ExceptionInterface);
	ZEPHIR_INIT(ZendFramework_Ldap_Exception_ExceptionInterface);
	ZEPHIR_INIT(ZendFramework_Captcha_Exception_ExceptionInterface);
	ZEPHIR_INIT(ZendFramework_Db_Adapter_Exception_ExceptionInterface);
	ZEPHIR_INIT(ZendFramework_Di_Exception_ExceptionInterface);
	ZEPHIR_INIT(ZendFramework_Server_Exception_ExceptionInterface);
	ZEPHIR_INIT(ZendFramework_ModuleManager_Exception_ExceptionInterface);
	ZEPHIR_INIT(ZendFramework_XmlRpc_Client_Exception_ExceptionInterface);
	ZEPHIR_INIT(ZendFramework_Loader_Exception_ExceptionInterface);
	ZEPHIR_INIT(ZendFramework_Stdlib_Exception_ExceptionInterface);
	ZEPHIR_INIT(ZendFramework_Http_Client_Adapter_Exception_ExceptionInterface);
	ZEPHIR_INIT(ZendFramework_I18n_Exception_ExceptionInterface);
	ZEPHIR_INIT(ZendFramework_Tag_Exception_ExceptionInterface);
	ZEPHIR_INIT(ZendFramework_Filter_Exception_ExceptionInterface);
	ZEPHIR_INIT(ZendFramework_Form_Exception_ExceptionInterface);
	ZEPHIR_INIT(ZendFramework_Mail_Storage_Exception_ExceptionInterface);
	ZEPHIR_INIT(ZendFramework_File_Transfer_Exception_ExceptionInterface);
	ZEPHIR_INIT(ZendFramework_Json_Server_Exception_ExceptionInterface);
	ZEPHIR_INIT(ZendFramework_Validator_Exception_ExceptionInterface);
	ZEPHIR_INIT(ZendFramework_Math_BigInteger_Exception_ExceptionInterface);
	ZEPHIR_INIT(ZendFramework_Serializer_Exception_ExceptionInterface);
	ZEPHIR_INIT(ZendFramework_View_Exception_ExceptionInterface);
	ZEPHIR_INIT(ZendFramework_Di_LocatorInterface);
	ZEPHIR_INIT(ZendFramework_EventManager_EventsCapableInterface);
	ZEPHIR_INIT(ZendFramework_Text_Table_Exception_ExceptionInterface);
	ZEPHIR_INIT(ZendFramework_Uri_Exception_ExceptionInterface);
	ZEPHIR_INIT(ZendFramework_EventManager_EventManagerAwareInterface);
	ZEPHIR_INIT(ZendFramework_EventManager_Exception_ExceptionInterface);
	ZEPHIR_INIT(ZendFramework_Navigation_Exception_ExceptionInterface);
	ZEPHIR_INIT(ZendFramework_Soap_Exception_ExceptionInterface);
	ZEPHIR_INIT(ZendFramework_Code_Generic_Prototype_PrototypeInterface);
	ZEPHIR_INIT(ZendFramework_Code_Reflection_Exception_ExceptionInterface);
	ZEPHIR_INIT(ZendFramework_Console_Exception_ExceptionInterface);
	ZEPHIR_INIT(ZendFramework_Db_Sql_ExpressionInterface);
	ZEPHIR_INIT(ZendFramework_Http_Header_Exception_ExceptionInterface);
	ZEPHIR_INIT(ZendFramework_Ldap_Converter_Exception_ExceptionInterface);
	ZEPHIR_INIT(ZendFramework_Mail_Header_Exception_ExceptionInterface);
	ZEPHIR_INIT(ZendFramework_Mail_Header_HeaderInterface);
	ZEPHIR_INIT(ZendFramework_Mail_Transport_Exception_ExceptionInterface);
	ZEPHIR_INIT(ZendFramework_Mvc_Router_RouteInterface);
	ZEPHIR_INIT(ZendFramework_Paginator_Adapter_Exception_ExceptionInterface);
	ZEPHIR_INIT(ZendFramework_Permissions_Acl_Exception_ExceptionInterface);
	ZEPHIR_INIT(ZendFramework_Server_Reflection_Exception_ExceptionInterface);
	ZEPHIR_INIT(ZendFramework_Session_Exception_ExceptionInterface);
	ZEPHIR_INIT(ZendFramework_Stdlib_MessageInterface);
	ZEPHIR_INIT(ZendFramework_Text_Figlet_Exception_ExceptionInterface);
	ZEPHIR_INIT(ZendFramework_XmlRpc_Server_Exception_ExceptionInterface);
	ZEPHIR_INIT(ZendFramework_Authentication_Adapter_DbTable_Exception_ExceptionInterface);
	ZEPHIR_INIT(ZendFramework_Authentication_Adapter_Http_Exception_ExceptionInterface);
	ZEPHIR_INIT(ZendFramework_Code_Annotation_AnnotationInterface);
	ZEPHIR_INIT(ZendFramework_Code_Generator_Exception_ExceptionInterface);
	ZEPHIR_INIT(ZendFramework_Config_Exception_ExceptionInterface);
	ZEPHIR_INIT(ZendFramework_Crypt_Key_Derivation_Exception_ExceptionInterface);
	ZEPHIR_INIT(ZendFramework_Crypt_Password_Exception_ExceptionInterface);
	ZEPHIR_INIT(ZendFramework_Crypt_PublicKey_Rsa_Exception_ExceptionInterface);
	ZEPHIR_INIT(ZendFramework_Crypt_Symmetric_Exception_ExceptionInterface);
	ZEPHIR_INIT(ZendFramework_Db_ResultSet_Exception_ExceptionInterface);
	ZEPHIR_INIT(ZendFramework_Db_RowGateway_Exception_ExceptionInterface);
	ZEPHIR_INIT(ZendFramework_Db_Sql_Exception_ExceptionInterface);
	ZEPHIR_INIT(ZendFramework_Db_TableGateway_Exception_ExceptionInterface);
	ZEPHIR_INIT(ZendFramework_Dom_Exception_ExceptionInterface);
	ZEPHIR_INIT(ZendFramework_Escaper_Exception_ExceptionInterface);
	ZEPHIR_INIT(ZendFramework_EventManager_EventInterface);
	ZEPHIR_INIT(ZendFramework_EventManager_ListenerAggregateInterface);
	ZEPHIR_INIT(ZendFramework_Form_ElementInterface);
	ZEPHIR_INIT(ZendFramework_Form_ElementPrepareAwareInterface);
	ZEPHIR_INIT(ZendFramework_Form_FormFactoryAwareInterface);
	ZEPHIR_INIT(ZendFramework_InputFilter_Exception_ExceptionInterface);
	ZEPHIR_INIT(ZendFramework_Log_Exception_ExceptionInterface);
	ZEPHIR_INIT(ZendFramework_Mail_Protocol_Exception_ExceptionInterface);
	ZEPHIR_INIT(ZendFramework_Mail_Storage_Part_Exception_ExceptionInterface);
	ZEPHIR_INIT(ZendFramework_Memory_Exception_ExceptionInterface);
	ZEPHIR_INIT(ZendFramework_ModuleManager_Listener_Exception_ExceptionInterface);
	ZEPHIR_INIT(ZendFramework_Mvc_Router_Exception_ExceptionInterface);
	ZEPHIR_INIT(ZendFramework_ProgressBar_Adapter_Exception_ExceptionInterface);
	ZEPHIR_INIT(ZendFramework_Authentication_Adapter_AdapterInterface);
	ZEPHIR_INIT(ZendFramework_Db_Adapter_StatementContainerInterface);
	ZEPHIR_INIT(ZendFramework_Db_Sql_SqlInterface);
	ZEPHIR_INIT(ZendFramework_Di_Definition_DefinitionInterface);
	ZEPHIR_INIT(ZendFramework_Di_ServiceLocatorInterface);
	ZEPHIR_INIT(ZendFramework_EventManager_Filter_FilterInterface);
	ZEPHIR_INIT(ZendFramework_EventManager_SharedEventManagerAwareInterface);
	ZEPHIR_INIT(ZendFramework_Form_FieldsetInterface);
	ZEPHIR_INIT(ZendFramework_Http_Header_HeaderInterface);
	ZEPHIR_INIT(ZendFramework_Ldap_Filter_Exception_ExceptionInterface);
	ZEPHIR_INIT(ZendFramework_Loader_ShortNameLocator);
	ZEPHIR_INIT(ZendFramework_Mime_Exception_ExceptionInterface);
	ZEPHIR_INIT(ZendFramework_ModuleManager_ModuleManagerInterface);
	ZEPHIR_INIT(ZendFramework_Permissions_Acl_Resource_ResourceInterface);
	ZEPHIR_INIT(ZendFramework_Permissions_Acl_Role_RoleInterface);
	ZEPHIR_INIT(ZendFramework_Permissions_Rbac_Exception_ExceptionInterface);
	ZEPHIR_INIT(ZendFramework_Stdlib_Extractor_ExtractionInterface);
	ZEPHIR_INIT(ZendFramework_Stdlib_Hydrator_Filter_FilterProviderInterface);
	ZEPHIR_INIT(ZendFramework_Stdlib_Hydrator_HydrationInterface);
	ZEPHIR_INIT(ZendFramework_Stdlib_ParametersInterface);
	ZEPHIR_INIT(ZendFramework_Tag_Cloud_Decorator_Exception_ExceptionInterface);
	ZEPHIR_INIT(ZendFramework_Validator_ValidatorInterface);
	ZEPHIR_INIT(ZendFramework_View_Helper_HelperInterface);
	ZEPHIR_INIT(ZendFramework_Authentication_Adapter_Http_ResolverInterface);
	ZEPHIR_INIT(ZendFramework_Authentication_Adapter_ValidatableAdapterInterface);
	ZEPHIR_INIT(ZendFramework_Authentication_AuthenticationServiceInterface);
	ZEPHIR_INIT(ZendFramework_Authentication_Storage_StorageInterface);
	ZEPHIR_INIT(ZendFramework_Cache_Pattern_PatternInterface);
	ZEPHIR_INIT(ZendFramework_Cache_Storage_AvailableSpaceCapableInterface);
	ZEPHIR_INIT(ZendFramework_Cache_Storage_ClearByNamespaceInterface);
	ZEPHIR_INIT(ZendFramework_Cache_Storage_ClearByPrefixInterface);
	ZEPHIR_INIT(ZendFramework_Cache_Storage_ClearExpiredInterface);
	ZEPHIR_INIT(ZendFramework_Cache_Storage_FlushableInterface);
	ZEPHIR_INIT(ZendFramework_Cache_Storage_IterableInterface);
	ZEPHIR_INIT(ZendFramework_Cache_Storage_IteratorInterface);
	ZEPHIR_INIT(ZendFramework_Cache_Storage_OptimizableInterface);
	ZEPHIR_INIT(ZendFramework_Cache_Storage_Plugin_PluginInterface);
	ZEPHIR_INIT(ZendFramework_Cache_Storage_StorageInterface);
	ZEPHIR_INIT(ZendFramework_Cache_Storage_TaggableInterface);
	ZEPHIR_INIT(ZendFramework_Cache_Storage_TotalSpaceCapableInterface);
	ZEPHIR_INIT(ZendFramework_Captcha_AdapterInterface);
	ZEPHIR_INIT(ZendFramework_Code_Annotation_Parser_ParserInterface);
	ZEPHIR_INIT(ZendFramework_Code_Generator_DocBlock_Tag_TagInterface);
	ZEPHIR_INIT(ZendFramework_Code_Generator_GeneratorInterface);
	ZEPHIR_INIT(ZendFramework_Code_Generic_Prototype_PrototypeGenericInterface);
	ZEPHIR_INIT(ZendFramework_Code_Reflection_DocBlock_Tag_PhpDocTypedTagInterface);
	ZEPHIR_INIT(ZendFramework_Code_Reflection_DocBlock_Tag_TagInterface);
	ZEPHIR_INIT(ZendFramework_Code_Reflection_ReflectionInterface);
	ZEPHIR_INIT(ZendFramework_Code_Scanner_ScannerInterface);
	ZEPHIR_INIT(ZendFramework_Config_Processor_ProcessorInterface);
	ZEPHIR_INIT(ZendFramework_Config_Reader_ReaderInterface);
	ZEPHIR_INIT(ZendFramework_Config_Writer_WriterInterface);
	ZEPHIR_INIT(ZendFramework_Console_Adapter_AdapterInterface);
	ZEPHIR_INIT(ZendFramework_Console_Charset_CharsetInterface);
	ZEPHIR_INIT(ZendFramework_Console_ColorInterface);
	ZEPHIR_INIT(ZendFramework_Console_Prompt_PromptInterface);
	ZEPHIR_INIT(ZendFramework_Console_RouteMatcher_RouteMatcherInterface);
	ZEPHIR_INIT(ZendFramework_Crypt_Password_PasswordInterface);
	ZEPHIR_INIT(ZendFramework_Crypt_Symmetric_Padding_PaddingInterface);
	ZEPHIR_INIT(ZendFramework_Crypt_Symmetric_SymmetricInterface);
	ZEPHIR_INIT(ZendFramework_Db_Adapter_AdapterAwareInterface);
	ZEPHIR_INIT(ZendFramework_Db_Adapter_AdapterInterface);
	ZEPHIR_INIT(ZendFramework_Db_Adapter_Driver_ConnectionInterface);
	ZEPHIR_INIT(ZendFramework_Db_Adapter_Driver_DriverInterface);
	ZEPHIR_INIT(ZendFramework_Db_Adapter_Driver_Feature_DriverFeatureInterface);
	ZEPHIR_INIT(ZendFramework_Db_Adapter_Driver_ResultInterface);
	ZEPHIR_INIT(ZendFramework_Db_Adapter_Driver_StatementInterface);
	ZEPHIR_INIT(ZendFramework_Db_Adapter_Platform_PlatformInterface);
	ZEPHIR_INIT(ZendFramework_Db_Adapter_Profiler_ProfilerAwareInterface);
	ZEPHIR_INIT(ZendFramework_Db_Adapter_Profiler_ProfilerInterface);
	ZEPHIR_INIT(ZendFramework_Db_Metadata_MetadataInterface);
	ZEPHIR_INIT(ZendFramework_Db_ResultSet_ResultSetInterface);
	ZEPHIR_INIT(ZendFramework_Db_RowGateway_RowGatewayInterface);
	ZEPHIR_INIT(ZendFramework_Db_Sql_Ddl_Column_ColumnInterface);
	ZEPHIR_INIT(ZendFramework_Db_Sql_Ddl_Constraint_ConstraintInterface);
	ZEPHIR_INIT(ZendFramework_Db_Sql_Ddl_SqlInterface);
	ZEPHIR_INIT(ZendFramework_Db_Sql_Platform_PlatformDecoratorInterface);
	ZEPHIR_INIT(ZendFramework_Db_Sql_Predicate_PredicateInterface);
	ZEPHIR_INIT(ZendFramework_Db_Sql_PreparableSqlInterface);
	ZEPHIR_INIT(ZendFramework_Db_TableGateway_TableGatewayInterface);
	ZEPHIR_INIT(ZendFramework_Di_Definition_PartialMarker);
	ZEPHIR_INIT(ZendFramework_Di_DependencyInjectionInterface);
	ZEPHIR_INIT(ZendFramework_EventManager_EventManagerInterface);
	ZEPHIR_INIT(ZendFramework_EventManager_SharedEventAggregateAwareInterface);
	ZEPHIR_INIT(ZendFramework_EventManager_SharedEventManagerInterface);
	ZEPHIR_INIT(ZendFramework_EventManager_SharedListenerAggregateInterface);
	ZEPHIR_INIT(ZendFramework_Filter_Compress_CompressionAlgorithmInterface);
	ZEPHIR_INIT(ZendFramework_Filter_Encrypt_EncryptionAlgorithmInterface);
	ZEPHIR_INIT(ZendFramework_Filter_FilterInterface);
	ZEPHIR_INIT(ZendFramework_Form_ElementAttributeRemovalInterface);
	ZEPHIR_INIT(ZendFramework_Form_FieldsetPrepareAwareInterface);
	ZEPHIR_INIT(ZendFramework_Form_FormInterface);
	ZEPHIR_INIT(ZendFramework_Form_LabelAwareInterface);
	ZEPHIR_INIT(ZendFramework_Http_Client_Adapter_AdapterInterface);
	ZEPHIR_INIT(ZendFramework_Http_Client_Adapter_StreamInterface);
	ZEPHIR_INIT(ZendFramework_Http_Header_MultipleHeaderInterface);
	ZEPHIR_INIT(ZendFramework_I18n_Translator_Loader_FileLoaderInterface);
	ZEPHIR_INIT(ZendFramework_I18n_Translator_Loader_RemoteLoaderInterface);
	ZEPHIR_INIT(ZendFramework_I18n_Translator_TranslatorAwareInterface);
	ZEPHIR_INIT(ZendFramework_I18n_Translator_TranslatorInterface);
	ZEPHIR_INIT(ZendFramework_InputFilter_EmptyContextInterface);
	ZEPHIR_INIT(ZendFramework_InputFilter_InputFilterAwareInterface);
	ZEPHIR_INIT(ZendFramework_InputFilter_InputFilterInterface);
	ZEPHIR_INIT(ZendFramework_InputFilter_InputFilterProviderInterface);
	ZEPHIR_INIT(ZendFramework_InputFilter_InputInterface);
	ZEPHIR_INIT(ZendFramework_InputFilter_InputProviderInterface);
	ZEPHIR_INIT(ZendFramework_InputFilter_ReplaceableInputInterface);
	ZEPHIR_INIT(ZendFramework_InputFilter_UnknownInputsCapableInterface);
	ZEPHIR_INIT(ZendFramework_Ldap_Node_Schema_AttributeType_AttributeTypeInterface);
	ZEPHIR_INIT(ZendFramework_Ldap_Node_Schema_ObjectClass_ObjectClassInterface);
	ZEPHIR_INIT(ZendFramework_Loader_PluginClassLocator);
	ZEPHIR_INIT(ZendFramework_Loader_SplAutoloader);
	ZEPHIR_INIT(ZendFramework_Log_Filter_FilterInterface);
	ZEPHIR_INIT(ZendFramework_Log_Formatter_FormatterInterface);
	ZEPHIR_INIT(ZendFramework_Log_LoggerAwareInterface);
	ZEPHIR_INIT(ZendFramework_Log_LoggerInterface);
	ZEPHIR_INIT(ZendFramework_Log_Processor_ProcessorInterface);
	ZEPHIR_INIT(ZendFramework_Log_Writer_ChromePhp_ChromePhpInterface);
	ZEPHIR_INIT(ZendFramework_Log_Writer_FirePhp_FirePhpInterface);
	ZEPHIR_INIT(ZendFramework_Log_Writer_WriterInterface);
	ZEPHIR_INIT(ZendFramework_Mail_Address_AddressInterface);
	ZEPHIR_INIT(ZendFramework_Mail_Header_MultipleHeadersInterface);
	ZEPHIR_INIT(ZendFramework_Mail_Header_StructuredInterface);
	ZEPHIR_INIT(ZendFramework_Mail_Header_UnstructuredInterface);
	ZEPHIR_INIT(ZendFramework_Mail_Storage_Folder_FolderInterface);
	ZEPHIR_INIT(ZendFramework_Mail_Storage_Message_MessageInterface);
	ZEPHIR_INIT(ZendFramework_Mail_Storage_Part_PartInterface);
	ZEPHIR_INIT(ZendFramework_Mail_Storage_Writable_WritableInterface);
	ZEPHIR_INIT(ZendFramework_Mail_Transport_TransportInterface);
	ZEPHIR_INIT(ZendFramework_Math_BigInteger_Adapter_AdapterInterface);
	ZEPHIR_INIT(ZendFramework_Memory_Container_ContainerInterface);
	ZEPHIR_INIT(ZendFramework_ModuleManager_Feature_AutoloaderProviderInterface);
	ZEPHIR_INIT(ZendFramework_ModuleManager_Feature_BootstrapListenerInterface);
	ZEPHIR_INIT(ZendFramework_ModuleManager_Feature_ConfigProviderInterface);
	ZEPHIR_INIT(ZendFramework_ModuleManager_Feature_ConsoleBannerProviderInterface);
	ZEPHIR_INIT(ZendFramework_ModuleManager_Feature_ConsoleUsageProviderInterface);
	ZEPHIR_INIT(ZendFramework_ModuleManager_Feature_ControllerPluginProviderInterface);
	ZEPHIR_INIT(ZendFramework_ModuleManager_Feature_ControllerProviderInterface);
	ZEPHIR_INIT(ZendFramework_ModuleManager_Feature_DependencyIndicatorInterface);
	ZEPHIR_INIT(ZendFramework_ModuleManager_Feature_FilterProviderInterface);
	ZEPHIR_INIT(ZendFramework_ModuleManager_Feature_FormElementProviderInterface);
	ZEPHIR_INIT(ZendFramework_ModuleManager_Feature_HydratorProviderInterface);
	ZEPHIR_INIT(ZendFramework_ModuleManager_Feature_InitProviderInterface);
	ZEPHIR_INIT(ZendFramework_ModuleManager_Feature_InputFilterProviderInterface);
	ZEPHIR_INIT(ZendFramework_ModuleManager_Feature_LocatorRegisteredInterface);
	ZEPHIR_INIT(ZendFramework_ModuleManager_Feature_LogProcessorProviderInterface);
	ZEPHIR_INIT(ZendFramework_ModuleManager_Feature_LogWriterProviderInterface);
	ZEPHIR_INIT(ZendFramework_ModuleManager_Feature_RouteProviderInterface);
	ZEPHIR_INIT(ZendFramework_ModuleManager_Feature_SerializerProviderInterface);
	ZEPHIR_INIT(ZendFramework_ModuleManager_Feature_ServiceProviderInterface);
	ZEPHIR_INIT(ZendFramework_ModuleManager_Feature_ValidatorProviderInterface);
	ZEPHIR_INIT(ZendFramework_ModuleManager_Feature_ViewHelperProviderInterface);
	ZEPHIR_INIT(ZendFramework_ModuleManager_Listener_ConfigMergerInterface);
	ZEPHIR_INIT(ZendFramework_ModuleManager_Listener_ServiceListenerInterface);
	ZEPHIR_INIT(ZendFramework_Mvc_ApplicationInterface);
	ZEPHIR_INIT(ZendFramework_Mvc_Controller_Plugin_PluginInterface);
	ZEPHIR_INIT(ZendFramework_Mvc_InjectApplicationEventInterface);
	ZEPHIR_INIT(ZendFramework_Mvc_ResponseSender_ResponseSenderInterface);
	ZEPHIR_INIT(ZendFramework_Mvc_Router_Console_RouteInterface);
	ZEPHIR_INIT(ZendFramework_Mvc_Router_Http_RouteInterface);
	ZEPHIR_INIT(ZendFramework_Mvc_Router_RouteStackInterface);
	ZEPHIR_INIT(ZendFramework_Paginator_AdapterAggregateInterface);
	ZEPHIR_INIT(ZendFramework_Paginator_Adapter_AdapterInterface);
	ZEPHIR_INIT(ZendFramework_Paginator_ScrollingStyle_ScrollingStyleInterface);
	ZEPHIR_INIT(ZendFramework_Permissions_Acl_AclInterface);
	ZEPHIR_INIT(ZendFramework_Permissions_Acl_Assertion_AssertionInterface);
	ZEPHIR_INIT(ZendFramework_Permissions_Rbac_AssertionInterface);
	ZEPHIR_INIT(ZendFramework_Permissions_Rbac_RoleInterface);
	ZEPHIR_INIT(ZendFramework_ProgressBar_Upload_UploadHandlerInterface);
	ZEPHIR_INIT(ZendFramework_Serializer_Adapter_AdapterInterface);
	ZEPHIR_INIT(ZendFramework_Server_Client);
	ZEPHIR_INIT(ZendFramework_Server_Server);
	ZEPHIR_INIT(ZendFramework_ServiceManager_AbstractFactoryInterface);
	ZEPHIR_INIT(ZendFramework_ServiceManager_ConfigInterface);
	ZEPHIR_INIT(ZendFramework_ServiceManager_DelegatorFactoryInterface);
	ZEPHIR_INIT(ZendFramework_ServiceManager_FactoryInterface);
	ZEPHIR_INIT(ZendFramework_ServiceManager_InitializerInterface);
	ZEPHIR_INIT(ZendFramework_ServiceManager_MutableCreationOptionsInterface);
	ZEPHIR_INIT(ZendFramework_ServiceManager_ServiceLocatorAwareInterface);
	ZEPHIR_INIT(ZendFramework_ServiceManager_ServiceLocatorInterface);
	ZEPHIR_INIT(ZendFramework_ServiceManager_ServiceManagerAwareInterface);
	ZEPHIR_INIT(ZendFramework_Session_Config_ConfigInterface);
	ZEPHIR_INIT(ZendFramework_Session_ManagerInterface);
	ZEPHIR_INIT(ZendFramework_Session_SaveHandler_SaveHandlerInterface);
	ZEPHIR_INIT(ZendFramework_Session_Storage_StorageInitializationInterface);
	ZEPHIR_INIT(ZendFramework_Session_Storage_StorageInterface);
	ZEPHIR_INIT(ZendFramework_Session_Validator_ValidatorInterface);
	ZEPHIR_INIT(ZendFramework_Soap_Wsdl_ComplexTypeStrategy_ComplexTypeStrategyInterface);
	ZEPHIR_INIT(ZendFramework_Stdlib_ArraySerializableInterface);
	ZEPHIR_INIT(ZendFramework_Stdlib_DispatchableInterface);
	ZEPHIR_INIT(ZendFramework_Stdlib_Hydrator_FilterEnabledInterface);
	ZEPHIR_INIT(ZendFramework_Stdlib_Hydrator_Filter_FilterInterface);
	ZEPHIR_INIT(ZendFramework_Stdlib_Hydrator_HydratorAwareInterface);
	ZEPHIR_INIT(ZendFramework_Stdlib_Hydrator_HydratorInterface);
	ZEPHIR_INIT(ZendFramework_Stdlib_Hydrator_HydratorOptionsInterface);
	ZEPHIR_INIT(ZendFramework_Stdlib_Hydrator_NamingStrategyEnabledInterface);
	ZEPHIR_INIT(ZendFramework_Stdlib_Hydrator_NamingStrategy_NamingStrategyInterface);
	ZEPHIR_INIT(ZendFramework_Stdlib_Hydrator_StrategyEnabledInterface);
	ZEPHIR_INIT(ZendFramework_Stdlib_Hydrator_Strategy_StrategyInterface);
	ZEPHIR_INIT(ZendFramework_Stdlib_InitializableInterface);
	ZEPHIR_INIT(ZendFramework_Stdlib_JsonSerializable);
	ZEPHIR_INIT(ZendFramework_Stdlib_JsonSerializable_PhpLegacyCompatibility);
	ZEPHIR_INIT(ZendFramework_Stdlib_ParameterObjectInterface);
	ZEPHIR_INIT(ZendFramework_Stdlib_RequestInterface);
	ZEPHIR_INIT(ZendFramework_Stdlib_ResponseInterface);
	ZEPHIR_INIT(ZendFramework_Stdlib_StringWrapper_StringWrapperInterface);
	ZEPHIR_INIT(ZendFramework_Tag_Cloud_Decorator_DecoratorInterface);
	ZEPHIR_INIT(ZendFramework_Tag_TaggableInterface);
	ZEPHIR_INIT(ZendFramework_Text_Table_Decorator_DecoratorInterface);
	ZEPHIR_INIT(ZendFramework_Uri_UriInterface);
	ZEPHIR_INIT(ZendFramework_Validator_Barcode_AdapterInterface);
	ZEPHIR_INIT(ZendFramework_Validator_Translator_TranslatorAwareInterface);
	ZEPHIR_INIT(ZendFramework_Validator_Translator_TranslatorInterface);
	ZEPHIR_INIT(ZendFramework_Validator_ValidatorPluginManagerAwareInterface);
	ZEPHIR_INIT(ZendFramework_View_Helper_Navigation_HelperInterface);
	ZEPHIR_INIT(ZendFramework_View_Model_ClearableModelInterface);
	ZEPHIR_INIT(ZendFramework_View_Model_ModelInterface);
	ZEPHIR_INIT(ZendFramework_View_Model_RetrievableChildrenInterface);
	ZEPHIR_INIT(ZendFramework_View_Renderer_RendererInterface);
	ZEPHIR_INIT(ZendFramework_View_Renderer_TreeRendererInterface);
	ZEPHIR_INIT(ZendFramework_View_Resolver_ResolverInterface);
	ZEPHIR_INIT(ZendFramework_XmlRpc_Generator_GeneratorInterface);
	ZEPHIR_INIT(ZendFramework_Http_Exception_RuntimeException);
	ZEPHIR_INIT(ZendFramework_Db_Exception_RuntimeException);
	ZEPHIR_INIT(ZendFramework_Authentication_Exception_InvalidArgumentException);
	ZEPHIR_INIT(ZendFramework_Authentication_Exception_RuntimeException);
	ZEPHIR_INIT(ZendFramework_Db_Exception_InvalidArgumentException);
	ZEPHIR_INIT(ZendFramework_Http_Client_Exception_RuntimeException);
	ZEPHIR_INIT(ZendFramework_Http_Exception_InvalidArgumentException);
	ZEPHIR_INIT(ZendFramework_Json_Exception_RuntimeException);
	ZEPHIR_INIT(ZendFramework_Mail_Exception_InvalidArgumentException);
	ZEPHIR_INIT(ZendFramework_Mail_Exception_RuntimeException);
	ZEPHIR_INIT(ZendFramework_XmlRpc_Exception_InvalidArgumentException);
	ZEPHIR_INIT(ZendFramework_XmlRpc_Exception_RuntimeException);
	ZEPHIR_INIT(ZendFramework_Crypt_Exception_InvalidArgumentException);
	ZEPHIR_INIT(ZendFramework_Crypt_Exception_RuntimeException);
	ZEPHIR_INIT(ZendFramework_Db_Exception_UnexpectedValueException);
	ZEPHIR_INIT(ZendFramework_File_Exception_RuntimeException);
	ZEPHIR_INIT(ZendFramework_Http_Exception_OutOfRangeException);
	ZEPHIR_INIT(ZendFramework_Math_Exception_RuntimeException);
	ZEPHIR_INIT(ZendFramework_ServiceManager_Exception_RuntimeException);
	ZEPHIR_INIT(ZendFramework_Cache_Exception_RuntimeException);
	ZEPHIR_INIT(ZendFramework_Di_Exception_InvalidArgumentException);
	ZEPHIR_INIT(ZendFramework_Authentication_Adapter_Exception_InvalidArgumentException);
	ZEPHIR_INIT(ZendFramework_Authentication_Adapter_Exception_RuntimeException);
	ZEPHIR_INIT(ZendFramework_Captcha_Exception_RuntimeException);
	ZEPHIR_INIT(ZendFramework_Code_Exception_InvalidArgumentException);
	ZEPHIR_INIT(ZendFramework_Code_Exception_RuntimeException);
	ZEPHIR_INIT(ZendFramework_Http_Client_Adapter_Exception_RuntimeException);
	ZEPHIR_INIT(ZendFramework_Loader_Exception_DomainException);
	ZEPHIR_INIT(ZendFramework_ModuleManager_Exception_RuntimeException);
	ZEPHIR_INIT(ZendFramework_Mvc_Exception_RuntimeException);
	ZEPHIR_INIT(ZendFramework_ProgressBar_Exception_RuntimeException);
	ZEPHIR_INIT(ZendFramework_Text_Exception_InvalidArgumentException);
	ZEPHIR_INIT(ZendFramework_Text_Exception_UnexpectedValueException);
	ZEPHIR_INIT(ZendFramework_Uri_Exception_InvalidArgumentException);
	ZEPHIR_INIT(ZendFramework_XmlRpc_Exception_BadMethodCallException);
	ZEPHIR_INIT(ZendFramework_Authentication_Exception_UnexpectedValueException);
	ZEPHIR_INIT(ZendFramework_Captcha_Exception_InvalidArgumentException);
	ZEPHIR_INIT(ZendFramework_Code_Exception_BadMethodCallException);
	ZEPHIR_INIT(ZendFramework_Db_Adapter_Exception_RuntimeException);
	ZEPHIR_INIT(ZendFramework_Db_Adapter_Exception_UnexpectedValueException);
	ZEPHIR_INIT(ZendFramework_Db_Exception_ErrorException);
	ZEPHIR_INIT(ZendFramework_EventManager_Event);
	ZEPHIR_INIT(ZendFramework_EventManager_Exception_DomainException);
	ZEPHIR_INIT(ZendFramework_File_Exception_BadMethodCallException);
	ZEPHIR_INIT(ZendFramework_File_Exception_InvalidArgumentException);
	ZEPHIR_INIT(ZendFramework_File_Transfer_Exception_RuntimeException);
	ZEPHIR_INIT(ZendFramework_Filter_Exception_RuntimeException);
	ZEPHIR_INIT(ZendFramework_Form_Exception_DomainException);
	ZEPHIR_INIT(ZendFramework_Form_Exception_InvalidArgumentException);
	ZEPHIR_INIT(ZendFramework_Http_Client_Exception_InvalidArgumentException);
	ZEPHIR_INIT(ZendFramework_Http_Client_Exception_OutOfRangeException);
	ZEPHIR_INIT(ZendFramework_I18n_Exception_RuntimeException);
	ZEPHIR_INIT(ZendFramework_Json_Exception_BadMethodCallException);
	ZEPHIR_INIT(ZendFramework_Json_Exception_InvalidArgumentException);
	ZEPHIR_INIT(ZendFramework_Json_Server_Exception_RuntimeException);
	ZEPHIR_INIT(ZendFramework_Ldap_Exception_InvalidArgumentException);
	ZEPHIR_INIT(ZendFramework_Mail_Exception_BadMethodCallException);
	ZEPHIR_INIT(ZendFramework_Mail_Exception_DomainException);
	ZEPHIR_INIT(ZendFramework_Mail_Exception_OutOfBoundsException);
	ZEPHIR_INIT(ZendFramework_Mail_Storage_Exception_InvalidArgumentException);
	ZEPHIR_INIT(ZendFramework_Mail_Storage_Exception_RuntimeException);
	ZEPHIR_INIT(ZendFramework_Math_BigInteger_Exception_RuntimeException);
	ZEPHIR_INIT(ZendFramework_Math_Exception_InvalidArgumentException);
	ZEPHIR_INIT(ZendFramework_ModuleManager_Exception_InvalidArgumentException);
	ZEPHIR_INIT(ZendFramework_Mvc_Exception_InvalidArgumentException);
	ZEPHIR_INIT(ZendFramework_Paginator_Exception_InvalidArgumentException);
	ZEPHIR_INIT(ZendFramework_Paginator_Exception_RuntimeException);
	ZEPHIR_INIT(ZendFramework_Paginator_Exception_UnexpectedValueException);
	ZEPHIR_INIT(ZendFramework_ProgressBar_Exception_InvalidArgumentException);
	ZEPHIR_INIT(ZendFramework_Serializer_Exception_RuntimeException);
	ZEPHIR_INIT(ZendFramework_Server_Exception_BadMethodCallException);
	ZEPHIR_INIT(ZendFramework_Server_Exception_InvalidArgumentException);
	ZEPHIR_INIT(ZendFramework_Server_Exception_RuntimeException);
	ZEPHIR_INIT(ZendFramework_ServiceManager_Exception_InvalidArgumentException);
	ZEPHIR_INIT(ZendFramework_Stdlib_Exception_DomainException);
	ZEPHIR_INIT(ZendFramework_Stdlib_Exception_RuntimeException);
	ZEPHIR_INIT(ZendFramework_Stdlib_SplPriorityQueue);
	ZEPHIR_INIT(ZendFramework_Tag_Exception_InvalidArgumentException);
	ZEPHIR_INIT(ZendFramework_Text_Exception_OutOfBoundsException);
	ZEPHIR_INIT(ZendFramework_Text_Exception_OverflowException);
	ZEPHIR_INIT(ZendFramework_Text_Exception_RuntimeException);
	ZEPHIR_INIT(ZendFramework_Validator_Exception_InvalidArgumentException);
	ZEPHIR_INIT(ZendFramework_Validator_Exception_RuntimeException);
	ZEPHIR_INIT(ZendFramework_XmlRpc_Client_Exception_InvalidArgumentException);
	ZEPHIR_INIT(ZendFramework_XmlRpc_Client_Exception_RuntimeException);
	ZEPHIR_INIT(ZendFramework_Authentication_Adapter_DbTable_Exception_InvalidArgumentException);
	ZEPHIR_INIT(ZendFramework_Authentication_Adapter_DbTable_Exception_RuntimeException);
	ZEPHIR_INIT(ZendFramework_Authentication_Adapter_Exception_UnexpectedValueException);
	ZEPHIR_INIT(ZendFramework_Authentication_Adapter_Http_Exception_InvalidArgumentException);
	ZEPHIR_INIT(ZendFramework_Authentication_Adapter_Http_Exception_RuntimeException);
	ZEPHIR_INIT(ZendFramework_Cache_Exception_BadMethodCallException);
	ZEPHIR_INIT(ZendFramework_Cache_Exception_ExtensionNotLoadedException);
	ZEPHIR_INIT(ZendFramework_Cache_Exception_InvalidArgumentException);
	ZEPHIR_INIT(ZendFramework_Cache_Exception_LogicException);
	ZEPHIR_INIT(ZendFramework_Cache_Exception_MissingDependencyException);
	ZEPHIR_INIT(ZendFramework_Cache_Exception_MissingKeyException);
	ZEPHIR_INIT(ZendFramework_Cache_Exception_OutOfSpaceException);
	ZEPHIR_INIT(ZendFramework_Cache_Exception_UnexpectedValueException);
	ZEPHIR_INIT(ZendFramework_Cache_Exception_UnsupportedMethodCallException);
	ZEPHIR_INIT(ZendFramework_Captcha_Exception_DomainException);
	ZEPHIR_INIT(ZendFramework_Captcha_Exception_ExtensionNotLoadedException);
	ZEPHIR_INIT(ZendFramework_Captcha_Exception_ImageNotLoadableException);
	ZEPHIR_INIT(ZendFramework_Captcha_Exception_NoFontProvidedException);
	ZEPHIR_INIT(ZendFramework_Code_Generator_Exception_InvalidArgumentException);
	ZEPHIR_INIT(ZendFramework_Code_Generator_Exception_RuntimeException);
	ZEPHIR_INIT(ZendFramework_Code_Reflection_Exception_BadMethodCallException);
	ZEPHIR_INIT(ZendFramework_Code_Reflection_Exception_InvalidArgumentException);
	ZEPHIR_INIT(ZendFramework_Code_Reflection_Exception_RuntimeException);
	ZEPHIR_INIT(ZendFramework_Config_Exception_InvalidArgumentException);
	ZEPHIR_INIT(ZendFramework_Config_Exception_RuntimeException);
	ZEPHIR_INIT(ZendFramework_Console_Exception_BadMethodCallException);
	ZEPHIR_INIT(ZendFramework_Console_Exception_InvalidArgumentException);
	ZEPHIR_INIT(ZendFramework_Console_Exception_RuntimeException);
	ZEPHIR_INIT(ZendFramework_Crypt_Key_Derivation_Exception_InvalidArgumentException);
	ZEPHIR_INIT(ZendFramework_Crypt_Key_Derivation_Exception_RuntimeException);
	ZEPHIR_INIT(ZendFramework_Crypt_Password_Exception_InvalidArgumentException);
	ZEPHIR_INIT(ZendFramework_Crypt_Password_Exception_RuntimeException);
	ZEPHIR_INIT(ZendFramework_Crypt_PublicKey_Rsa_Exception_InvalidArgumentException);
	ZEPHIR_INIT(ZendFramework_Crypt_PublicKey_Rsa_Exception_RuntimeException);
	ZEPHIR_INIT(ZendFramework_Crypt_Symmetric_Exception_InvalidArgumentException);
	ZEPHIR_INIT(ZendFramework_Crypt_Symmetric_Exception_RuntimeException);
	ZEPHIR_INIT(ZendFramework_Db_Adapter_Exception_ErrorException);
	ZEPHIR_INIT(ZendFramework_Db_Adapter_Exception_InvalidArgumentException);
	ZEPHIR_INIT(ZendFramework_Db_Adapter_Exception_InvalidConnectionParametersException);
	ZEPHIR_INIT(ZendFramework_Db_Adapter_Exception_InvalidQueryException);
	ZEPHIR_INIT(ZendFramework_Db_ResultSet_Exception_InvalidArgumentException);
	ZEPHIR_INIT(ZendFramework_Db_ResultSet_Exception_RuntimeException);
	ZEPHIR_INIT(ZendFramework_Db_RowGateway_Exception_InvalidArgumentException);
	ZEPHIR_INIT(ZendFramework_Db_RowGateway_Exception_RuntimeException);
	ZEPHIR_INIT(ZendFramework_Db_Sql_Exception_InvalidArgumentException);
	ZEPHIR_INIT(ZendFramework_Db_Sql_Exception_RuntimeException);
	ZEPHIR_INIT(ZendFramework_Db_TableGateway_Exception_InvalidArgumentException);
	ZEPHIR_INIT(ZendFramework_Db_TableGateway_Exception_RuntimeException);
	ZEPHIR_INIT(ZendFramework_Di_Definition_Annotation_Inject);
	ZEPHIR_INIT(ZendFramework_Di_Definition_Annotation_Instantiator);
	ZEPHIR_INIT(ZendFramework_Di_Definition_ArrayDefinition);
	ZEPHIR_INIT(ZendFramework_Di_Definition_Builder_InjectionMethod);
	ZEPHIR_INIT(ZendFramework_Di_Definition_Builder_PhpClass);
	ZEPHIR_INIT(ZendFramework_Di_Di);
	ZEPHIR_INIT(ZendFramework_Di_Exception_CircularDependencyException);
	ZEPHIR_INIT(ZendFramework_Di_Exception_ClassNotFoundException);
	ZEPHIR_INIT(ZendFramework_Di_Exception_InvalidCallbackException);
	ZEPHIR_INIT(ZendFramework_Di_Exception_InvalidParamNameException);
	ZEPHIR_INIT(ZendFramework_Di_Exception_InvalidPositionException);
	ZEPHIR_INIT(ZendFramework_Di_Exception_MissingPropertyException);
	ZEPHIR_INIT(ZendFramework_Di_Exception_RuntimeException);
	ZEPHIR_INIT(ZendFramework_Di_Exception_UndefinedReferenceException);
	ZEPHIR_INIT(ZendFramework_Di_ServiceLocator);
	ZEPHIR_INIT(ZendFramework_Dom_Exception_BadMethodCallException);
	ZEPHIR_INIT(ZendFramework_Dom_Exception_RuntimeException);
	ZEPHIR_INIT(ZendFramework_Escaper_Exception_InvalidArgumentException);
	ZEPHIR_INIT(ZendFramework_Escaper_Exception_RuntimeException);
	ZEPHIR_INIT(ZendFramework_EventManager_Exception_InvalidArgumentException);
	ZEPHIR_INIT(ZendFramework_EventManager_Exception_InvalidCallbackException);
	ZEPHIR_INIT(ZendFramework_EventManager_FilterChain);
	ZEPHIR_INIT(ZendFramework_EventManager_Filter_FilterIterator);
	ZEPHIR_INIT(ZendFramework_EventManager_ResponseCollection);
	ZEPHIR_INIT(ZendFramework_File_Transfer_Exception_BadMethodCallException);
	ZEPHIR_INIT(ZendFramework_File_Transfer_Exception_InvalidArgumentException);
	ZEPHIR_INIT(ZendFramework_File_Transfer_Exception_PhpEnvironmentException);
	ZEPHIR_INIT(ZendFramework_Filter_Exception_BadMethodCallException);
	ZEPHIR_INIT(ZendFramework_Filter_Exception_DomainException);
	ZEPHIR_INIT(ZendFramework_Filter_Exception_ExtensionNotLoadedException);
	ZEPHIR_INIT(ZendFramework_Filter_Exception_InvalidArgumentException);
	ZEPHIR_INIT(ZendFramework_Form_Exception_BadMethodCallException);
	ZEPHIR_INIT(ZendFramework_Form_Exception_ExtensionNotLoadedException);
	ZEPHIR_INIT(ZendFramework_Form_Exception_InvalidElementException);
	ZEPHIR_INIT(ZendFramework_Form_Exception_UnexpectedValueException);
	ZEPHIR_INIT(ZendFramework_Http_Client_Adapter_Exception_InitializationException);
	ZEPHIR_INIT(ZendFramework_Http_Client_Adapter_Exception_InvalidArgumentException);
	ZEPHIR_INIT(ZendFramework_Http_Client_Adapter_Exception_OutOfRangeException);
	ZEPHIR_INIT(ZendFramework_Http_Client_Adapter_Exception_TimeoutException);
	ZEPHIR_INIT(ZendFramework_Http_Header_Exception_DomainException);
	ZEPHIR_INIT(ZendFramework_Http_Header_Exception_InvalidArgumentException);
	ZEPHIR_INIT(ZendFramework_Http_Header_Exception_RuntimeException);
	ZEPHIR_INIT(ZendFramework_I18n_Exception_ExtensionNotLoadedException);
	ZEPHIR_INIT(ZendFramework_I18n_Exception_InvalidArgumentException);
	ZEPHIR_INIT(ZendFramework_I18n_Exception_OutOfBoundsException);
	ZEPHIR_INIT(ZendFramework_I18n_Exception_ParseException);
	ZEPHIR_INIT(ZendFramework_I18n_Exception_RangeException);
	ZEPHIR_INIT(ZendFramework_InputFilter_Exception_InvalidArgumentException);
	ZEPHIR_INIT(ZendFramework_InputFilter_Exception_RuntimeException);
	ZEPHIR_INIT(ZendFramework_Json_Exception_RecursionException);
	ZEPHIR_INIT(ZendFramework_Json_Server_Exception_ErrorException);
	ZEPHIR_INIT(ZendFramework_Json_Server_Exception_HttpException);
	ZEPHIR_INIT(ZendFramework_Json_Server_Exception_InvalidArgumentException);
	ZEPHIR_INIT(ZendFramework_Ldap_Converter_Exception_ConverterException);
	ZEPHIR_INIT(ZendFramework_Ldap_Converter_Exception_InvalidArgumentException);
	ZEPHIR_INIT(ZendFramework_Ldap_Converter_Exception_UnexpectedValueException);
	ZEPHIR_INIT(ZendFramework_Ldap_Exception_BadMethodCallException);
	ZEPHIR_INIT(ZendFramework_Ldap_Exception_LdapException);
	ZEPHIR_INIT(ZendFramework_Ldap_Filter_Exception_FilterException);
	ZEPHIR_INIT(ZendFramework_Loader_Exception_BadMethodCallException);
	ZEPHIR_INIT(ZendFramework_Loader_Exception_InvalidArgumentException);
	ZEPHIR_INIT(ZendFramework_Loader_Exception_InvalidPathException);
	ZEPHIR_INIT(ZendFramework_Loader_Exception_MissingResourceNamespaceException);
	ZEPHIR_INIT(ZendFramework_Loader_Exception_PluginLoaderException);
	ZEPHIR_INIT(ZendFramework_Loader_Exception_RuntimeException);
	ZEPHIR_INIT(ZendFramework_Loader_Exception_SecurityException);
	ZEPHIR_INIT(ZendFramework_Log_Exception_InvalidArgumentException);
	ZEPHIR_INIT(ZendFramework_Log_Exception_RuntimeException);
	ZEPHIR_INIT(ZendFramework_Mail_Header_Exception_BadMethodCallException);
	ZEPHIR_INIT(ZendFramework_Mail_Header_Exception_InvalidArgumentException);
	ZEPHIR_INIT(ZendFramework_Mail_Header_Exception_RuntimeException);
	ZEPHIR_INIT(ZendFramework_Mail_Protocol_Exception_InvalidArgumentException);
	ZEPHIR_INIT(ZendFramework_Mail_Protocol_Exception_RuntimeException);
	ZEPHIR_INIT(ZendFramework_Mail_Storage_Exception_OutOfBoundsException);
	ZEPHIR_INIT(ZendFramework_Mail_Storage_Part_Exception_InvalidArgumentException);
	ZEPHIR_INIT(ZendFramework_Mail_Storage_Part_Exception_RuntimeException);
	ZEPHIR_INIT(ZendFramework_Mail_Transport_Exception_DomainException);
	ZEPHIR_INIT(ZendFramework_Mail_Transport_Exception_InvalidArgumentException);
	ZEPHIR_INIT(ZendFramework_Mail_Transport_Exception_RuntimeException);
	ZEPHIR_INIT(ZendFramework_Math_BigInteger_Exception_DivisionByZeroException);
	ZEPHIR_INIT(ZendFramework_Math_BigInteger_Exception_InvalidArgumentException);
	ZEPHIR_INIT(ZendFramework_Math_Exception_DomainException);
	ZEPHIR_INIT(ZendFramework_Memory_Exception_InvalidArgumentException);
	ZEPHIR_INIT(ZendFramework_Memory_Exception_RuntimeException);
	ZEPHIR_INIT(ZendFramework_Mime_Exception_RuntimeException);
	ZEPHIR_INIT(ZendFramework_ModuleManager_Exception_MissingDependencyModuleException);
	ZEPHIR_INIT(ZendFramework_ModuleManager_Listener_Exception_InvalidArgumentException);
	ZEPHIR_INIT(ZendFramework_ModuleManager_Listener_Exception_RuntimeException);
	ZEPHIR_INIT(ZendFramework_ModuleManager_ModuleEvent);
	ZEPHIR_INIT(ZendFramework_ModuleManager_ModuleManager);
	ZEPHIR_INIT(ZendFramework_Mvc_Exception_BadMethodCallException);
	ZEPHIR_INIT(ZendFramework_Mvc_Exception_DomainException);
	ZEPHIR_INIT(ZendFramework_Mvc_Exception_InvalidControllerException);
	ZEPHIR_INIT(ZendFramework_Mvc_Exception_InvalidPluginException);
	ZEPHIR_INIT(ZendFramework_Mvc_Exception_MissingLocatorException);
	ZEPHIR_INIT(ZendFramework_Mvc_Router_Exception_InvalidArgumentException);
	ZEPHIR_INIT(ZendFramework_Mvc_Router_Exception_RuntimeException);
	ZEPHIR_INIT(ZendFramework_Navigation_Exception_BadMethodCallException);
	ZEPHIR_INIT(ZendFramework_Navigation_Exception_DomainException);
	ZEPHIR_INIT(ZendFramework_Navigation_Exception_InvalidArgumentException);
	ZEPHIR_INIT(ZendFramework_Navigation_Exception_OutOfBoundsException);
	ZEPHIR_INIT(ZendFramework_Paginator_Adapter_Exception_InvalidArgumentException);
	ZEPHIR_INIT(ZendFramework_Paginator_Adapter_Exception_RuntimeException);
	ZEPHIR_INIT(ZendFramework_Paginator_Adapter_Exception_UnexpectedValueException);
	ZEPHIR_INIT(ZendFramework_Permissions_Acl_Assertion_Exception_InvalidAssertionException);
	ZEPHIR_INIT(ZendFramework_Permissions_Acl_Exception_InvalidArgumentException);
	ZEPHIR_INIT(ZendFramework_Permissions_Acl_Exception_RuntimeException);
	ZEPHIR_INIT(ZendFramework_Permissions_Acl_Resource_GenericResource);
	ZEPHIR_INIT(ZendFramework_Permissions_Acl_Role_GenericRole);
	ZEPHIR_INIT(ZendFramework_Permissions_Acl_Role_Registry);
	ZEPHIR_INIT(ZendFramework_Permissions_Rbac_Exception_InvalidArgumentException);
	ZEPHIR_INIT(ZendFramework_ProgressBar_Adapter_Exception_InvalidArgumentException);
	ZEPHIR_INIT(ZendFramework_ProgressBar_Adapter_Exception_RuntimeException);
	ZEPHIR_INIT(ZendFramework_ProgressBar_Exception_OutOfRangeException);
	ZEPHIR_INIT(ZendFramework_ProgressBar_Exception_PhpEnvironmentException);
	ZEPHIR_INIT(ZendFramework_Serializer_Exception_ExtensionNotLoadedException);
	ZEPHIR_INIT(ZendFramework_Serializer_Exception_InvalidArgumentException);
	ZEPHIR_INIT(ZendFramework_Server_Reflection_Exception_BadMethodCallException);
	ZEPHIR_INIT(ZendFramework_Server_Reflection_Exception_InvalidArgumentException);
	ZEPHIR_INIT(ZendFramework_Server_Reflection_Exception_RuntimeException);
	ZEPHIR_INIT(ZendFramework_ServiceManager_Exception_CircularDependencyFoundException);
	ZEPHIR_INIT(ZendFramework_ServiceManager_Exception_CircularReferenceException);
	ZEPHIR_INIT(ZendFramework_ServiceManager_Exception_InvalidServiceNameException);
	ZEPHIR_INIT(ZendFramework_ServiceManager_Exception_ServiceNotCreatedException);
	ZEPHIR_INIT(ZendFramework_ServiceManager_Exception_ServiceNotFoundException);
	ZEPHIR_INIT(ZendFramework_Session_Exception_BadMethodCallException);
	ZEPHIR_INIT(ZendFramework_Session_Exception_InvalidArgumentException);
	ZEPHIR_INIT(ZendFramework_Session_Exception_RuntimeException);
	ZEPHIR_INIT(ZendFramework_Soap_Exception_BadMethodCallException);
	ZEPHIR_INIT(ZendFramework_Soap_Exception_InvalidArgumentException);
	ZEPHIR_INIT(ZendFramework_Soap_Exception_RuntimeException);
	ZEPHIR_INIT(ZendFramework_Soap_Exception_UnexpectedValueException);
	ZEPHIR_INIT(ZendFramework_Stdlib_ArrayStack);
	ZEPHIR_INIT(ZendFramework_Stdlib_ArrayUtils);
	ZEPHIR_INIT(ZendFramework_Stdlib_CallbackHandler);
	ZEPHIR_INIT(ZendFramework_Stdlib_ErrorHandler);
	ZEPHIR_INIT(ZendFramework_Stdlib_Exception_BadMethodCallException);
	ZEPHIR_INIT(ZendFramework_Stdlib_Exception_ExtensionNotLoadedException);
	ZEPHIR_INIT(ZendFramework_Stdlib_Exception_InvalidArgumentException);
	ZEPHIR_INIT(ZendFramework_Stdlib_Exception_InvalidCallbackException);
	ZEPHIR_INIT(ZendFramework_Stdlib_Exception_LogicException);
	ZEPHIR_INIT(ZendFramework_Stdlib_Message);
	ZEPHIR_INIT(ZendFramework_Stdlib_Parameters);
	ZEPHIR_INIT(ZendFramework_Stdlib_PriorityList);
	ZEPHIR_INIT(ZendFramework_Stdlib_PriorityQueue);
	ZEPHIR_INIT(ZendFramework_Stdlib_SplQueue);
	ZEPHIR_INIT(ZendFramework_Stdlib_SplStack);
	ZEPHIR_INIT(ZendFramework_Stdlib_StringUtils);
	ZEPHIR_INIT(ZendFramework_Tag_Cloud_Decorator_Exception_InvalidArgumentException);
	ZEPHIR_INIT(ZendFramework_Tag_Exception_InvalidAttributeNameException);
	ZEPHIR_INIT(ZendFramework_Tag_Exception_InvalidElementNameException);
	ZEPHIR_INIT(ZendFramework_Tag_Exception_OutOfBoundsException);
	ZEPHIR_INIT(ZendFramework_Text_Figlet_Exception_InvalidArgumentException);
	ZEPHIR_INIT(ZendFramework_Text_Figlet_Exception_RuntimeException);
	ZEPHIR_INIT(ZendFramework_Text_Figlet_Exception_UnexpectedValueException);
	ZEPHIR_INIT(ZendFramework_Text_Table_Exception_InvalidArgumentException);
	ZEPHIR_INIT(ZendFramework_Text_Table_Exception_InvalidDecoratorException);
	ZEPHIR_INIT(ZendFramework_Text_Table_Exception_OutOfBoundsException);
	ZEPHIR_INIT(ZendFramework_Text_Table_Exception_OverflowException);
	ZEPHIR_INIT(ZendFramework_Text_Table_Exception_UnexpectedValueException);
	ZEPHIR_INIT(ZendFramework_Uri_Exception_InvalidUriException);
	ZEPHIR_INIT(ZendFramework_Uri_Exception_InvalidUriPartException);
	ZEPHIR_INIT(ZendFramework_Validator_Exception_BadMethodCallException);
	ZEPHIR_INIT(ZendFramework_Validator_Exception_ExtensionNotLoadedException);
	ZEPHIR_INIT(ZendFramework_Validator_Exception_InvalidMagicMimeFileException);
	ZEPHIR_INIT(ZendFramework_View_Exception_BadMethodCallException);
	ZEPHIR_INIT(ZendFramework_View_Exception_DomainException);
	ZEPHIR_INIT(ZendFramework_View_Exception_InvalidArgumentException);
	ZEPHIR_INIT(ZendFramework_View_Exception_InvalidHelperException);
	ZEPHIR_INIT(ZendFramework_View_Exception_RuntimeException);
	ZEPHIR_INIT(ZendFramework_View_Exception_UnexpectedValueException);
	ZEPHIR_INIT(ZendFramework_XmlRpc_Client_Exception_FaultException);
	ZEPHIR_INIT(ZendFramework_XmlRpc_Client_Exception_HttpException);
	ZEPHIR_INIT(ZendFramework_XmlRpc_Client_Exception_IntrospectException);
	ZEPHIR_INIT(ZendFramework_XmlRpc_Exception_ValueException);
	ZEPHIR_INIT(ZendFramework_XmlRpc_Server_Exception_BadMethodCallException);
	ZEPHIR_INIT(ZendFramework_XmlRpc_Server_Exception_InvalidArgumentException);
	ZEPHIR_INIT(ZendFramework_XmlRpc_Server_Exception_RuntimeException);

#if PHP_VERSION_ID < 50500
	setlocale(LC_ALL, old_lc_all);
	free(old_lc_all);
#endif
	return SUCCESS;
}

#ifndef ZEPHIR_RELEASE
static PHP_MSHUTDOWN_FUNCTION(zendframework)
{

	zephir_deinitialize_memory(TSRMLS_C);

	return SUCCESS;
}
#endif

/**
 * Initialize globals on each request or each thread started
 */
static void php_zephir_init_globals(zend_zendframework_globals *zephir_globals TSRMLS_DC)
{
	zephir_globals->initialized = 0;

	/* Memory options */
	zephir_globals->active_memory = NULL;

	/* Virtual Symbol Tables */
	zephir_globals->active_symbol_table = NULL;

	/* Cache Enabled */
#if PHP_VERSION_ID < 50600
	zephir_globals->cache_enabled = 1;
#else
	zephir_globals->cache_enabled = 0;
#endif

	/* Recursive Lock */
	zephir_globals->recursive_lock = 0;


}

static PHP_RINIT_FUNCTION(zendframework)
{

	zend_zendframework_globals *zephir_globals_ptr = ZEPHIR_VGLOBAL;

	php_zephir_init_globals(zephir_globals_ptr TSRMLS_CC);
	//zephir_init_interned_strings(TSRMLS_C);

	zephir_initialize_memory(zephir_globals_ptr TSRMLS_CC);

	return SUCCESS;
}

static PHP_RSHUTDOWN_FUNCTION(zendframework)
{

	

	zephir_deinitialize_memory(TSRMLS_C);
	return SUCCESS;
}

static PHP_MINFO_FUNCTION(zendframework)
{
	php_info_print_box_start(0);
	php_printf("%s", PHP_ZENDFRAMEWORK_DESCRIPTION);
	php_info_print_box_end();

	php_info_print_table_start();
	php_info_print_table_header(2, PHP_ZENDFRAMEWORK_NAME, "enabled");
	php_info_print_table_row(2, "Author", PHP_ZENDFRAMEWORK_AUTHOR);
	php_info_print_table_row(2, "Version", PHP_ZENDFRAMEWORK_VERSION);
	php_info_print_table_row(2, "Powered by Zephir", "Version " PHP_ZENDFRAMEWORK_ZEPVERSION);
	php_info_print_table_end();


}

static PHP_GINIT_FUNCTION(zendframework)
{
	php_zephir_init_globals(zendframework_globals TSRMLS_CC);
}

static PHP_GSHUTDOWN_FUNCTION(zendframework)
{

}

zend_module_entry zendframework_module_entry = {
	STANDARD_MODULE_HEADER_EX,
	NULL,
	NULL,
	PHP_ZENDFRAMEWORK_EXTNAME,
	NULL,
	PHP_MINIT(zendframework),
#ifndef ZEPHIR_RELEASE
	PHP_MSHUTDOWN(zendframework),
#else
	NULL,
#endif
	PHP_RINIT(zendframework),
	PHP_RSHUTDOWN(zendframework),
	PHP_MINFO(zendframework),
	PHP_ZENDFRAMEWORK_VERSION,
	ZEND_MODULE_GLOBALS(zendframework),
	PHP_GINIT(zendframework),
	PHP_GSHUTDOWN(zendframework),
	NULL,
	STANDARD_MODULE_PROPERTIES_EX
};

#ifdef COMPILE_DL_ZENDFRAMEWORK
ZEND_GET_MODULE(zendframework)
#endif
