
/* This file was generated automatically by Zephir do not modify it! */

#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#include <php.h>

#if PHP_VERSION_ID < 50500
#include <locale.h>
#endif

#include "php_ext.h"
#include "zendframework.h"

#include <ext/standard/info.h>

#include <Zend/zend_operators.h>
#include <Zend/zend_exceptions.h>
#include <Zend/zend_interfaces.h>

#include "kernel/main.h"
#include "kernel/fcall.h"
#include "kernel/memory.h"



zend_class_entry *zendframework_http_exception_exceptioninterface_ce;
zend_class_entry *zendframework_db_exception_exceptioninterface_ce;
zend_class_entry *zendframework_authentication_exception_exceptioninterface_ce;
zend_class_entry *zendframework_xmlrpc_exception_exceptioninterface_ce;
zend_class_entry *zendframework_mail_exception_exceptioninterface_ce;
zend_class_entry *zendframework_barcode_exception_exceptioninterface_ce;
zend_class_entry *zendframework_http_client_exception_exceptioninterface_ce;
zend_class_entry *zendframework_crypt_exception_exceptioninterface_ce;
zend_class_entry *zendframework_math_exception_exceptioninterface_ce;
zend_class_entry *zendframework_text_exception_exceptioninterface_ce;
zend_class_entry *zendframework_feed_exception_exceptioninterface_ce;
zend_class_entry *zendframework_json_exception_exceptioninterface_ce;
zend_class_entry *zendframework_db_adapter_exception_exceptioninterface_ce;
zend_class_entry *zendframework_authentication_adapter_exception_exceptioninterface_ce;
zend_class_entry *zendframework_code_exception_exceptioninterface_ce;
zend_class_entry *zendframework_cache_exception_exceptioninterface_ce;
zend_class_entry *zendframework_file_exception_exceptioninterface_ce;
zend_class_entry *zendframework_paginator_exception_exceptioninterface_ce;
zend_class_entry *zendframework_progressbar_exception_exceptioninterface_ce;
zend_class_entry *zendframework_mvc_exception_exceptioninterface_ce;
zend_class_entry *zendframework_servicemanager_exception_exceptioninterface_ce;
zend_class_entry *zendframework_server_exception_exceptioninterface_ce;
zend_class_entry *zendframework_captcha_exception_exceptioninterface_ce;
zend_class_entry *zendframework_modulemanager_exception_exceptioninterface_ce;
zend_class_entry *zendframework_barcode_object_exception_exceptioninterface_ce;
zend_class_entry *zendframework_di_exception_exceptioninterface_ce;
zend_class_entry *zendframework_i18n_exception_exceptioninterface_ce;
zend_class_entry *zendframework_stdlib_exception_exceptioninterface_ce;
zend_class_entry *zendframework_tag_exception_exceptioninterface_ce;
zend_class_entry *zendframework_xmlrpc_client_exception_exceptioninterface_ce;
zend_class_entry *zendframework_loader_exception_exceptioninterface_ce;
zend_class_entry *zendframework_mail_storage_exception_exceptioninterface_ce;
zend_class_entry *zendframework_filter_exception_exceptioninterface_ce;
zend_class_entry *zendframework_http_client_adapter_exception_exceptioninterface_ce;
zend_class_entry *zendframework_validator_exception_exceptioninterface_ce;
zend_class_entry *zendframework_file_transfer_exception_exceptioninterface_ce;
zend_class_entry *zendframework_form_exception_exceptioninterface_ce;
zend_class_entry *zendframework_json_server_exception_exceptioninterface_ce;
zend_class_entry *zendframework_view_exception_exceptioninterface_ce;
zend_class_entry *zendframework_ldap_exception_exceptioninterface_ce;
zend_class_entry *zendframework_math_biginteger_exception_exceptioninterface_ce;
zend_class_entry *zendframework_serializer_exception_exceptioninterface_ce;
zend_class_entry *zendframework_text_table_exception_exceptioninterface_ce;
zend_class_entry *zendframework_barcode_renderer_exception_exceptioninterface_ce;
zend_class_entry *zendframework_loader_shortnamelocator_ce;
zend_class_entry *zendframework_navigation_exception_exceptioninterface_ce;
zend_class_entry *zendframework_soap_exception_exceptioninterface_ce;
zend_class_entry *zendframework_code_reflection_exception_exceptioninterface_ce;
zend_class_entry *zendframework_console_exception_exceptioninterface_ce;
zend_class_entry *zendframework_eventmanager_exception_exceptioninterface_ce;
zend_class_entry *zendframework_feed_reader_exception_exceptioninterface_ce;
zend_class_entry *zendframework_feed_writer_exception_exceptioninterface_ce;
zend_class_entry *zendframework_http_header_exception_exceptioninterface_ce;
zend_class_entry *zendframework_ldap_converter_exception_exceptioninterface_ce;
zend_class_entry *zendframework_loader_splautoloader_ce;
zend_class_entry *zendframework_mail_header_exception_exceptioninterface_ce;
zend_class_entry *zendframework_mail_transport_exception_exceptioninterface_ce;
zend_class_entry *zendframework_paginator_adapter_exception_exceptioninterface_ce;
zend_class_entry *zendframework_permissions_acl_exception_exceptioninterface_ce;
zend_class_entry *zendframework_server_reflection_exception_exceptioninterface_ce;
zend_class_entry *zendframework_session_exception_exceptioninterface_ce;
zend_class_entry *zendframework_text_figlet_exception_exceptioninterface_ce;
zend_class_entry *zendframework_uri_exception_exceptioninterface_ce;
zend_class_entry *zendframework_xmlrpc_server_exception_exceptioninterface_ce;
zend_class_entry *zendframework_authentication_adapter_dbtable_exception_exceptioninterface_ce;
zend_class_entry *zendframework_authentication_adapter_http_exception_exceptioninterface_ce;
zend_class_entry *zendframework_code_generator_exception_exceptioninterface_ce;
zend_class_entry *zendframework_config_exception_exceptioninterface_ce;
zend_class_entry *zendframework_crypt_key_derivation_exception_exceptioninterface_ce;
zend_class_entry *zendframework_crypt_password_exception_exceptioninterface_ce;
zend_class_entry *zendframework_crypt_publickey_rsa_exception_exceptioninterface_ce;
zend_class_entry *zendframework_crypt_symmetric_exception_exceptioninterface_ce;
zend_class_entry *zendframework_db_resultset_exception_exceptioninterface_ce;
zend_class_entry *zendframework_db_rowgateway_exception_exceptioninterface_ce;
zend_class_entry *zendframework_db_sql_exception_exceptioninterface_ce;
zend_class_entry *zendframework_db_tablegateway_exception_exceptioninterface_ce;
zend_class_entry *zendframework_dom_exception_exceptioninterface_ce;
zend_class_entry *zendframework_escaper_exception_exceptioninterface_ce;
zend_class_entry *zendframework_feed_pubsubhubbub_exception_exceptioninterface_ce;
zend_class_entry *zendframework_inputfilter_exception_exceptioninterface_ce;
zend_class_entry *zendframework_log_exception_exceptioninterface_ce;
zend_class_entry *zendframework_mail_protocol_exception_exceptioninterface_ce;
zend_class_entry *zendframework_mail_storage_part_exception_exceptioninterface_ce;
zend_class_entry *zendframework_memory_exception_exceptioninterface_ce;
zend_class_entry *zendframework_modulemanager_listener_exception_exceptioninterface_ce;
zend_class_entry *zendframework_mvc_router_exception_exceptioninterface_ce;
zend_class_entry *zendframework_progressbar_adapter_exception_exceptioninterface_ce;
zend_class_entry *zendframework_stdlib_messageinterface_ce;
zend_class_entry *zendframework_db_adapter_driver_sqlsrv_exception_exceptioninterface_ce;
zend_class_entry *zendframework_ldap_filter_exception_exceptioninterface_ce;
zend_class_entry *zendframework_loader_pluginclasslocator_ce;
zend_class_entry *zendframework_mime_exception_exceptioninterface_ce;
zend_class_entry *zendframework_permissions_rbac_exception_exceptioninterface_ce;
zend_class_entry *zendframework_tag_cloud_decorator_exception_exceptioninterface_ce;
zend_class_entry *zendframework_cache_storage_flushableinterface_ce;
zend_class_entry *zendframework_cache_storage_iterableinterface_ce;
zend_class_entry *zendframework_cache_storage_taggableinterface_ce;
zend_class_entry *zendframework_cache_storage_totalspacecapableinterface_ce;
zend_class_entry *zendframework_config_reader_readerinterface_ce;
zend_class_entry *zendframework_filter_compress_compressionalgorithminterface_ce;
zend_class_entry *zendframework_filter_encrypt_encryptionalgorithminterface_ce;
zend_class_entry *zendframework_filter_filterinterface_ce;
zend_class_entry *zendframework_log_filter_filterinterface_ce;
zend_class_entry *zendframework_log_formatter_formatterinterface_ce;
zend_class_entry *zendframework_log_loggerinterface_ce;
zend_class_entry *zendframework_log_processor_processorinterface_ce;
zend_class_entry *zendframework_log_writer_chromephp_chromephpinterface_ce;
zend_class_entry *zendframework_log_writer_writerinterface_ce;
zend_class_entry *zendframework_stdlib_arrayserializableinterface_ce;
zend_class_entry *zendframework_stdlib_dispatchableinterface_ce;
zend_class_entry *zendframework_stdlib_initializableinterface_ce;
zend_class_entry *zendframework_stdlib_parameterobjectinterface_ce;
zend_class_entry *zendframework_stdlib_parametersinterface_ce;
zend_class_entry *zendframework_stdlib_requestinterface_ce;
zend_class_entry *zendframework_stdlib_responseinterface_ce;
zend_class_entry *zendframework_http_exception_runtimeexception_ce;
zend_class_entry *zendframework_db_exception_runtimeexception_ce;
zend_class_entry *zendframework_db_exception_invalidargumentexception_ce;
zend_class_entry *zendframework_authentication_exception_invalidargumentexception_ce;
zend_class_entry *zendframework_authentication_exception_runtimeexception_ce;
zend_class_entry *zendframework_barcode_exception_invalidargumentexception_ce;
zend_class_entry *zendframework_barcode_exception_runtimeexception_ce;
zend_class_entry *zendframework_http_client_exception_runtimeexception_ce;
zend_class_entry *zendframework_http_exception_invalidargumentexception_ce;
zend_class_entry *zendframework_json_exception_runtimeexception_ce;
zend_class_entry *zendframework_mail_exception_invalidargumentexception_ce;
zend_class_entry *zendframework_mail_exception_runtimeexception_ce;
zend_class_entry *zendframework_xmlrpc_exception_invalidargumentexception_ce;
zend_class_entry *zendframework_xmlrpc_exception_runtimeexception_ce;
zend_class_entry *zendframework_crypt_exception_invalidargumentexception_ce;
zend_class_entry *zendframework_crypt_exception_runtimeexception_ce;
zend_class_entry *zendframework_db_exception_errorexception_ce;
zend_class_entry *zendframework_db_exception_unexpectedvalueexception_ce;
zend_class_entry *zendframework_file_exception_runtimeexception_ce;
zend_class_entry *zendframework_http_exception_outofrangeexception_ce;
zend_class_entry *zendframework_math_exception_runtimeexception_ce;
zend_class_entry *zendframework_servicemanager_exception_runtimeexception_ce;
zend_class_entry *zendframework_cache_exception_runtimeexception_ce;
zend_class_entry *zendframework_di_exception_invalidargumentexception_ce;
zend_class_entry *zendframework_feed_exception_invalidargumentexception_ce;
zend_class_entry *zendframework_feed_exception_runtimeexception_ce;
zend_class_entry *zendframework_authentication_adapter_exception_invalidargumentexception_ce;
zend_class_entry *zendframework_authentication_adapter_exception_runtimeexception_ce;
zend_class_entry *zendframework_barcode_exception_outofrangeexception_ce;
zend_class_entry *zendframework_captcha_exception_runtimeexception_ce;
zend_class_entry *zendframework_code_exception_invalidargumentexception_ce;
zend_class_entry *zendframework_code_exception_runtimeexception_ce;
zend_class_entry *zendframework_feed_exception_badmethodcallexception_ce;
zend_class_entry *zendframework_http_client_adapter_exception_runtimeexception_ce;
zend_class_entry *zendframework_loader_exception_domainexception_ce;
zend_class_entry *zendframework_modulemanager_exception_runtimeexception_ce;
zend_class_entry *zendframework_mvc_exception_runtimeexception_ce;
zend_class_entry *zendframework_progressbar_exception_runtimeexception_ce;
zend_class_entry *zendframework_text_exception_unexpectedvalueexception_ce;
zend_class_entry *zendframework_uri_exception_invalidargumentexception_ce;
zend_class_entry *zendframework_xmlrpc_exception_badmethodcallexception_ce;
zend_class_entry *zendframework_authentication_exception_unexpectedvalueexception_ce;
zend_class_entry *zendframework_barcode_exception_unexpectedvalueexception_ce;
zend_class_entry *zendframework_barcode_object_exception_invalidargumentexception_ce;
zend_class_entry *zendframework_barcode_object_exception_runtimeexception_ce;
zend_class_entry *zendframework_captcha_exception_invalidargumentexception_ce;
zend_class_entry *zendframework_code_exception_badmethodcallexception_ce;
zend_class_entry *zendframework_db_adapter_exception_errorexception_ce;
zend_class_entry *zendframework_db_adapter_exception_runtimeexception_ce;
zend_class_entry *zendframework_db_adapter_exception_unexpectedvalueexception_ce;
zend_class_entry *zendframework_eventmanager_exception_domainexception_ce;
zend_class_entry *zendframework_file_exception_badmethodcallexception_ce;
zend_class_entry *zendframework_file_exception_invalidargumentexception_ce;
zend_class_entry *zendframework_file_transfer_exception_runtimeexception_ce;
zend_class_entry *zendframework_filter_exception_runtimeexception_ce;
zend_class_entry *zendframework_form_exception_domainexception_ce;
zend_class_entry *zendframework_form_exception_invalidargumentexception_ce;
zend_class_entry *zendframework_http_client_exception_invalidargumentexception_ce;
zend_class_entry *zendframework_http_client_exception_outofrangeexception_ce;
zend_class_entry *zendframework_i18n_exception_runtimeexception_ce;
zend_class_entry *zendframework_json_exception_badmethodcallexception_ce;
zend_class_entry *zendframework_json_exception_invalidargumentexception_ce;
zend_class_entry *zendframework_json_server_exception_runtimeexception_ce;
zend_class_entry *zendframework_mail_exception_badmethodcallexception_ce;
zend_class_entry *zendframework_mail_exception_domainexception_ce;
zend_class_entry *zendframework_mail_exception_outofboundsexception_ce;
zend_class_entry *zendframework_mail_storage_exception_invalidargumentexception_ce;
zend_class_entry *zendframework_mail_storage_exception_runtimeexception_ce;
zend_class_entry *zendframework_math_biginteger_exception_runtimeexception_ce;
zend_class_entry *zendframework_math_exception_invalidargumentexception_ce;
zend_class_entry *zendframework_modulemanager_exception_invalidargumentexception_ce;
zend_class_entry *zendframework_mvc_exception_invalidargumentexception_ce;
zend_class_entry *zendframework_paginator_exception_invalidargumentexception_ce;
zend_class_entry *zendframework_paginator_exception_runtimeexception_ce;
zend_class_entry *zendframework_paginator_exception_unexpectedvalueexception_ce;
zend_class_entry *zendframework_progressbar_exception_invalidargumentexception_ce;
zend_class_entry *zendframework_serializer_exception_runtimeexception_ce;
zend_class_entry *zendframework_server_exception_badmethodcallexception_ce;
zend_class_entry *zendframework_server_exception_invalidargumentexception_ce;
zend_class_entry *zendframework_server_exception_runtimeexception_ce;
zend_class_entry *zendframework_servicemanager_exception_invalidargumentexception_ce;
zend_class_entry *zendframework_stdlib_exception_domainexception_ce;
zend_class_entry *zendframework_stdlib_exception_runtimeexception_ce;
zend_class_entry *zendframework_tag_exception_invalidargumentexception_ce;
zend_class_entry *zendframework_text_exception_invalidargumentexception_ce;
zend_class_entry *zendframework_text_exception_outofboundsexception_ce;
zend_class_entry *zendframework_text_exception_overflowexception_ce;
zend_class_entry *zendframework_text_exception_runtimeexception_ce;
zend_class_entry *zendframework_validator_exception_invalidargumentexception_ce;
zend_class_entry *zendframework_validator_exception_runtimeexception_ce;
zend_class_entry *zendframework_xmlrpc_client_exception_invalidargumentexception_ce;
zend_class_entry *zendframework_xmlrpc_client_exception_runtimeexception_ce;
zend_class_entry *zendframework_authentication_adapter_dbtable_exception_invalidargumentexception_ce;
zend_class_entry *zendframework_authentication_adapter_dbtable_exception_runtimeexception_ce;
zend_class_entry *zendframework_authentication_adapter_exception_unexpectedvalueexception_ce;
zend_class_entry *zendframework_authentication_adapter_http_exception_invalidargumentexception_ce;
zend_class_entry *zendframework_authentication_adapter_http_exception_runtimeexception_ce;
zend_class_entry *zendframework_barcode_exception_renderercreationexception_ce;
zend_class_entry *zendframework_barcode_object_exception_barcodevalidationexception_ce;
zend_class_entry *zendframework_barcode_object_exception_extensionnotloadedexception_ce;
zend_class_entry *zendframework_barcode_object_exception_outofrangeexception_ce;
zend_class_entry *zendframework_barcode_renderer_exception_invalidargumentexception_ce;
zend_class_entry *zendframework_barcode_renderer_exception_outofrangeexception_ce;
zend_class_entry *zendframework_barcode_renderer_exception_runtimeexception_ce;
zend_class_entry *zendframework_barcode_renderer_exception_unexpectedvalueexception_ce;
zend_class_entry *zendframework_cache_exception_badmethodcallexception_ce;
zend_class_entry *zendframework_cache_exception_extensionnotloadedexception_ce;
zend_class_entry *zendframework_cache_exception_invalidargumentexception_ce;
zend_class_entry *zendframework_cache_exception_logicexception_ce;
zend_class_entry *zendframework_cache_exception_missingdependencyexception_ce;
zend_class_entry *zendframework_cache_exception_missingkeyexception_ce;
zend_class_entry *zendframework_cache_exception_outofspaceexception_ce;
zend_class_entry *zendframework_cache_exception_unexpectedvalueexception_ce;
zend_class_entry *zendframework_cache_exception_unsupportedmethodcallexception_ce;
zend_class_entry *zendframework_captcha_exception_domainexception_ce;
zend_class_entry *zendframework_captcha_exception_extensionnotloadedexception_ce;
zend_class_entry *zendframework_captcha_exception_imagenotloadableexception_ce;
zend_class_entry *zendframework_captcha_exception_nofontprovidedexception_ce;
zend_class_entry *zendframework_code_generator_exception_invalidargumentexception_ce;
zend_class_entry *zendframework_code_generator_exception_runtimeexception_ce;
zend_class_entry *zendframework_code_reflection_exception_badmethodcallexception_ce;
zend_class_entry *zendframework_code_reflection_exception_invalidargumentexception_ce;
zend_class_entry *zendframework_code_reflection_exception_runtimeexception_ce;
zend_class_entry *zendframework_config_exception_invalidargumentexception_ce;
zend_class_entry *zendframework_config_exception_runtimeexception_ce;
zend_class_entry *zendframework_console_exception_badmethodcallexception_ce;
zend_class_entry *zendframework_console_exception_invalidargumentexception_ce;
zend_class_entry *zendframework_console_exception_runtimeexception_ce;
zend_class_entry *zendframework_crypt_key_derivation_exception_invalidargumentexception_ce;
zend_class_entry *zendframework_crypt_key_derivation_exception_runtimeexception_ce;
zend_class_entry *zendframework_crypt_password_exception_invalidargumentexception_ce;
zend_class_entry *zendframework_crypt_password_exception_runtimeexception_ce;
zend_class_entry *zendframework_crypt_publickey_rsa_exception_invalidargumentexception_ce;
zend_class_entry *zendframework_crypt_publickey_rsa_exception_runtimeexception_ce;
zend_class_entry *zendframework_crypt_symmetric_exception_invalidargumentexception_ce;
zend_class_entry *zendframework_crypt_symmetric_exception_runtimeexception_ce;
zend_class_entry *zendframework_db_adapter_driver_sqlsrv_exception_errorexception_ce;
zend_class_entry *zendframework_db_adapter_exception_invalidargumentexception_ce;
zend_class_entry *zendframework_db_adapter_exception_invalidconnectionparametersexception_ce;
zend_class_entry *zendframework_db_adapter_exception_invalidqueryexception_ce;
zend_class_entry *zendframework_db_resultset_exception_invalidargumentexception_ce;
zend_class_entry *zendframework_db_resultset_exception_runtimeexception_ce;
zend_class_entry *zendframework_db_rowgateway_exception_invalidargumentexception_ce;
zend_class_entry *zendframework_db_rowgateway_exception_runtimeexception_ce;
zend_class_entry *zendframework_db_sql_exception_invalidargumentexception_ce;
zend_class_entry *zendframework_db_sql_exception_runtimeexception_ce;
zend_class_entry *zendframework_db_tablegateway_exception_invalidargumentexception_ce;
zend_class_entry *zendframework_db_tablegateway_exception_runtimeexception_ce;
zend_class_entry *zendframework_di_exception_circulardependencyexception_ce;
zend_class_entry *zendframework_di_exception_classnotfoundexception_ce;
zend_class_entry *zendframework_di_exception_invalidcallbackexception_ce;
zend_class_entry *zendframework_di_exception_invalidparamnameexception_ce;
zend_class_entry *zendframework_di_exception_invalidpositionexception_ce;
zend_class_entry *zendframework_di_exception_missingpropertyexception_ce;
zend_class_entry *zendframework_di_exception_runtimeexception_ce;
zend_class_entry *zendframework_di_exception_undefinedreferenceexception_ce;
zend_class_entry *zendframework_dom_exception_badmethodcallexception_ce;
zend_class_entry *zendframework_dom_exception_runtimeexception_ce;
zend_class_entry *zendframework_escaper_exception_invalidargumentexception_ce;
zend_class_entry *zendframework_escaper_exception_runtimeexception_ce;
zend_class_entry *zendframework_eventmanager_exception_invalidargumentexception_ce;
zend_class_entry *zendframework_eventmanager_exception_invalidcallbackexception_ce;
zend_class_entry *zendframework_feed_pubsubhubbub_exception_invalidargumentexception_ce;
zend_class_entry *zendframework_feed_pubsubhubbub_exception_runtimeexception_ce;
zend_class_entry *zendframework_feed_reader_exception_badmethodcallexception_ce;
zend_class_entry *zendframework_feed_reader_exception_invalidargumentexception_ce;
zend_class_entry *zendframework_feed_reader_exception_runtimeexception_ce;
zend_class_entry *zendframework_feed_writer_exception_badmethodcallexception_ce;
zend_class_entry *zendframework_feed_writer_exception_invalidargumentexception_ce;
zend_class_entry *zendframework_feed_writer_exception_runtimeexception_ce;
zend_class_entry *zendframework_file_transfer_exception_badmethodcallexception_ce;
zend_class_entry *zendframework_file_transfer_exception_invalidargumentexception_ce;
zend_class_entry *zendframework_file_transfer_exception_phpenvironmentexception_ce;
zend_class_entry *zendframework_filter_exception_badmethodcallexception_ce;
zend_class_entry *zendframework_filter_exception_domainexception_ce;
zend_class_entry *zendframework_filter_exception_extensionnotloadedexception_ce;
zend_class_entry *zendframework_filter_exception_invalidargumentexception_ce;
zend_class_entry *zendframework_form_exception_badmethodcallexception_ce;
zend_class_entry *zendframework_form_exception_extensionnotloadedexception_ce;
zend_class_entry *zendframework_form_exception_invalidelementexception_ce;
zend_class_entry *zendframework_form_exception_unexpectedvalueexception_ce;
zend_class_entry *zendframework_http_client_adapter_exception_initializationexception_ce;
zend_class_entry *zendframework_http_client_adapter_exception_invalidargumentexception_ce;
zend_class_entry *zendframework_http_client_adapter_exception_outofrangeexception_ce;
zend_class_entry *zendframework_http_client_adapter_exception_timeoutexception_ce;
zend_class_entry *zendframework_http_header_exception_domainexception_ce;
zend_class_entry *zendframework_http_header_exception_invalidargumentexception_ce;
zend_class_entry *zendframework_http_header_exception_runtimeexception_ce;
zend_class_entry *zendframework_i18n_exception_extensionnotloadedexception_ce;
zend_class_entry *zendframework_i18n_exception_invalidargumentexception_ce;
zend_class_entry *zendframework_i18n_exception_outofboundsexception_ce;
zend_class_entry *zendframework_i18n_exception_parseexception_ce;
zend_class_entry *zendframework_i18n_exception_rangeexception_ce;
zend_class_entry *zendframework_inputfilter_exception_invalidargumentexception_ce;
zend_class_entry *zendframework_inputfilter_exception_runtimeexception_ce;
zend_class_entry *zendframework_json_exception_recursionexception_ce;
zend_class_entry *zendframework_json_server_exception_errorexception_ce;
zend_class_entry *zendframework_json_server_exception_httpexception_ce;
zend_class_entry *zendframework_json_server_exception_invalidargumentexception_ce;
zend_class_entry *zendframework_ldap_converter_exception_converterexception_ce;
zend_class_entry *zendframework_ldap_converter_exception_invalidargumentexception_ce;
zend_class_entry *zendframework_ldap_converter_exception_unexpectedvalueexception_ce;
zend_class_entry *zendframework_ldap_exception_badmethodcallexception_ce;
zend_class_entry *zendframework_ldap_exception_invalidargumentexception_ce;
zend_class_entry *zendframework_ldap_exception_ldapexception_ce;
zend_class_entry *zendframework_ldap_filter_exception_filterexception_ce;
zend_class_entry *zendframework_loader_autoloaderfactory_ce;
zend_class_entry *zendframework_loader_classmapautoloader_ce;
zend_class_entry *zendframework_loader_exception_badmethodcallexception_ce;
zend_class_entry *zendframework_loader_exception_invalidargumentexception_ce;
zend_class_entry *zendframework_loader_exception_invalidpathexception_ce;
zend_class_entry *zendframework_loader_exception_missingresourcenamespaceexception_ce;
zend_class_entry *zendframework_loader_exception_pluginloaderexception_ce;
zend_class_entry *zendframework_loader_exception_runtimeexception_ce;
zend_class_entry *zendframework_loader_exception_securityexception_ce;
zend_class_entry *zendframework_loader_moduleautoloader_ce;
zend_class_entry *zendframework_loader_pluginclassloader_ce;
zend_class_entry *zendframework_loader_standardautoloader_ce;
zend_class_entry *zendframework_log_exception_invalidargumentexception_ce;
zend_class_entry *zendframework_log_exception_runtimeexception_ce;
zend_class_entry *zendframework_mail_header_exception_badmethodcallexception_ce;
zend_class_entry *zendframework_mail_header_exception_invalidargumentexception_ce;
zend_class_entry *zendframework_mail_header_exception_runtimeexception_ce;
zend_class_entry *zendframework_mail_protocol_exception_invalidargumentexception_ce;
zend_class_entry *zendframework_mail_protocol_exception_runtimeexception_ce;
zend_class_entry *zendframework_mail_storage_exception_outofboundsexception_ce;
zend_class_entry *zendframework_mail_storage_part_exception_invalidargumentexception_ce;
zend_class_entry *zendframework_mail_storage_part_exception_runtimeexception_ce;
zend_class_entry *zendframework_mail_transport_exception_domainexception_ce;
zend_class_entry *zendframework_mail_transport_exception_invalidargumentexception_ce;
zend_class_entry *zendframework_mail_transport_exception_runtimeexception_ce;
zend_class_entry *zendframework_math_biginteger_exception_divisionbyzeroexception_ce;
zend_class_entry *zendframework_math_biginteger_exception_invalidargumentexception_ce;
zend_class_entry *zendframework_math_exception_domainexception_ce;
zend_class_entry *zendframework_memory_exception_invalidargumentexception_ce;
zend_class_entry *zendframework_memory_exception_runtimeexception_ce;
zend_class_entry *zendframework_mime_exception_runtimeexception_ce;
zend_class_entry *zendframework_modulemanager_exception_missingdependencymoduleexception_ce;
zend_class_entry *zendframework_modulemanager_listener_exception_invalidargumentexception_ce;
zend_class_entry *zendframework_modulemanager_listener_exception_runtimeexception_ce;
zend_class_entry *zendframework_mvc_exception_badmethodcallexception_ce;
zend_class_entry *zendframework_mvc_exception_domainexception_ce;
zend_class_entry *zendframework_mvc_exception_invalidcontrollerexception_ce;
zend_class_entry *zendframework_mvc_exception_invalidpluginexception_ce;
zend_class_entry *zendframework_mvc_exception_missinglocatorexception_ce;
zend_class_entry *zendframework_mvc_router_exception_invalidargumentexception_ce;
zend_class_entry *zendframework_mvc_router_exception_runtimeexception_ce;
zend_class_entry *zendframework_navigation_exception_badmethodcallexception_ce;
zend_class_entry *zendframework_navigation_exception_domainexception_ce;
zend_class_entry *zendframework_navigation_exception_invalidargumentexception_ce;
zend_class_entry *zendframework_navigation_exception_outofboundsexception_ce;
zend_class_entry *zendframework_paginator_adapter_exception_invalidargumentexception_ce;
zend_class_entry *zendframework_paginator_adapter_exception_runtimeexception_ce;
zend_class_entry *zendframework_paginator_adapter_exception_unexpectedvalueexception_ce;
zend_class_entry *zendframework_permissions_acl_assertion_exception_invalidassertionexception_ce;
zend_class_entry *zendframework_permissions_acl_exception_invalidargumentexception_ce;
zend_class_entry *zendframework_permissions_acl_exception_runtimeexception_ce;
zend_class_entry *zendframework_permissions_rbac_exception_invalidargumentexception_ce;
zend_class_entry *zendframework_progressbar_adapter_exception_invalidargumentexception_ce;
zend_class_entry *zendframework_progressbar_adapter_exception_runtimeexception_ce;
zend_class_entry *zendframework_progressbar_exception_outofrangeexception_ce;
zend_class_entry *zendframework_progressbar_exception_phpenvironmentexception_ce;
zend_class_entry *zendframework_serializer_exception_extensionnotloadedexception_ce;
zend_class_entry *zendframework_serializer_exception_invalidargumentexception_ce;
zend_class_entry *zendframework_server_reflection_exception_badmethodcallexception_ce;
zend_class_entry *zendframework_server_reflection_exception_invalidargumentexception_ce;
zend_class_entry *zendframework_server_reflection_exception_runtimeexception_ce;
zend_class_entry *zendframework_servicemanager_exception_circulardependencyfoundexception_ce;
zend_class_entry *zendframework_servicemanager_exception_circularreferenceexception_ce;
zend_class_entry *zendframework_servicemanager_exception_invalidservicenameexception_ce;
zend_class_entry *zendframework_servicemanager_exception_servicenotcreatedexception_ce;
zend_class_entry *zendframework_servicemanager_exception_servicenotfoundexception_ce;
zend_class_entry *zendframework_session_exception_badmethodcallexception_ce;
zend_class_entry *zendframework_session_exception_invalidargumentexception_ce;
zend_class_entry *zendframework_session_exception_runtimeexception_ce;
zend_class_entry *zendframework_soap_exception_badmethodcallexception_ce;
zend_class_entry *zendframework_soap_exception_extensionnotloadedexception_ce;
zend_class_entry *zendframework_soap_exception_invalidargumentexception_ce;
zend_class_entry *zendframework_soap_exception_runtimeexception_ce;
zend_class_entry *zendframework_soap_exception_unexpectedvalueexception_ce;
zend_class_entry *zendframework_stdlib_arraystack_ce;
zend_class_entry *zendframework_stdlib_exception_badmethodcallexception_ce;
zend_class_entry *zendframework_stdlib_exception_extensionnotloadedexception_ce;
zend_class_entry *zendframework_stdlib_exception_invalidargumentexception_ce;
zend_class_entry *zendframework_stdlib_exception_invalidcallbackexception_ce;
zend_class_entry *zendframework_stdlib_exception_logicexception_ce;
zend_class_entry *zendframework_stdlib_prioritylist_ce;
zend_class_entry *zendframework_stdlib_priorityqueue_ce;
zend_class_entry *zendframework_stdlib_splqueue_ce;
zend_class_entry *zendframework_stdlib_splstack_ce;
zend_class_entry *zendframework_tag_cloud_decorator_exception_invalidargumentexception_ce;
zend_class_entry *zendframework_tag_exception_invalidattributenameexception_ce;
zend_class_entry *zendframework_tag_exception_invalidelementnameexception_ce;
zend_class_entry *zendframework_tag_exception_outofboundsexception_ce;
zend_class_entry *zendframework_text_figlet_exception_invalidargumentexception_ce;
zend_class_entry *zendframework_text_figlet_exception_runtimeexception_ce;
zend_class_entry *zendframework_text_figlet_exception_unexpectedvalueexception_ce;
zend_class_entry *zendframework_text_table_exception_invalidargumentexception_ce;
zend_class_entry *zendframework_text_table_exception_invaliddecoratorexception_ce;
zend_class_entry *zendframework_text_table_exception_outofboundsexception_ce;
zend_class_entry *zendframework_text_table_exception_overflowexception_ce;
zend_class_entry *zendframework_text_table_exception_unexpectedvalueexception_ce;
zend_class_entry *zendframework_uri_exception_invaliduriexception_ce;
zend_class_entry *zendframework_uri_exception_invaliduripartexception_ce;
zend_class_entry *zendframework_validator_exception_badmethodcallexception_ce;
zend_class_entry *zendframework_validator_exception_extensionnotloadedexception_ce;
zend_class_entry *zendframework_validator_exception_invalidmagicmimefileexception_ce;
zend_class_entry *zendframework_view_exception_badmethodcallexception_ce;
zend_class_entry *zendframework_view_exception_domainexception_ce;
zend_class_entry *zendframework_view_exception_invalidargumentexception_ce;
zend_class_entry *zendframework_view_exception_invalidhelperexception_ce;
zend_class_entry *zendframework_view_exception_runtimeexception_ce;
zend_class_entry *zendframework_view_exception_unexpectedvalueexception_ce;
zend_class_entry *zendframework_xmlrpc_client_exception_faultexception_ce;
zend_class_entry *zendframework_xmlrpc_client_exception_httpexception_ce;
zend_class_entry *zendframework_xmlrpc_client_exception_introspectexception_ce;
zend_class_entry *zendframework_xmlrpc_exception_valueexception_ce;
zend_class_entry *zendframework_xmlrpc_server_exception_badmethodcallexception_ce;
zend_class_entry *zendframework_xmlrpc_server_exception_invalidargumentexception_ce;
zend_class_entry *zendframework_xmlrpc_server_exception_runtimeexception_ce;

ZEND_DECLARE_MODULE_GLOBALS(zendframework)

static PHP_MINIT_FUNCTION(zendframework)
{
#if PHP_VERSION_ID < 50500
	char* old_lc_all = setlocale(LC_ALL, NULL);
	if (old_lc_all) {
		size_t len = strlen(old_lc_all);
		char *tmp  = calloc(len+1, 1);
		if (UNEXPECTED(!tmp)) {
			return FAILURE;
		}

		memcpy(tmp, old_lc_all, len);
		old_lc_all = tmp;
	}

	setlocale(LC_ALL, "C");
#endif

	ZEPHIR_INIT(ZendFramework_Http_Exception_ExceptionInterface);
	ZEPHIR_INIT(ZendFramework_Db_Exception_ExceptionInterface);
	ZEPHIR_INIT(ZendFramework_Authentication_Exception_ExceptionInterface);
	ZEPHIR_INIT(ZendFramework_XmlRpc_Exception_ExceptionInterface);
	ZEPHIR_INIT(ZendFramework_Mail_Exception_ExceptionInterface);
	ZEPHIR_INIT(ZendFramework_Barcode_Exception_ExceptionInterface);
	ZEPHIR_INIT(ZendFramework_Http_Client_Exception_ExceptionInterface);
	ZEPHIR_INIT(ZendFramework_Crypt_Exception_ExceptionInterface);
	ZEPHIR_INIT(ZendFramework_Math_Exception_ExceptionInterface);
	ZEPHIR_INIT(ZendFramework_Text_Exception_ExceptionInterface);
	ZEPHIR_INIT(ZendFramework_Feed_Exception_ExceptionInterface);
	ZEPHIR_INIT(ZendFramework_Json_Exception_ExceptionInterface);
	ZEPHIR_INIT(ZendFramework_Db_Adapter_Exception_ExceptionInterface);
	ZEPHIR_INIT(ZendFramework_Authentication_Adapter_Exception_ExceptionInterface);
	ZEPHIR_INIT(ZendFramework_Code_Exception_ExceptionInterface);
	ZEPHIR_INIT(ZendFramework_Cache_Exception_ExceptionInterface);
	ZEPHIR_INIT(ZendFramework_File_Exception_ExceptionInterface);
	ZEPHIR_INIT(ZendFramework_Paginator_Exception_ExceptionInterface);
	ZEPHIR_INIT(ZendFramework_ProgressBar_Exception_ExceptionInterface);
	ZEPHIR_INIT(ZendFramework_Mvc_Exception_ExceptionInterface);
	ZEPHIR_INIT(ZendFramework_ServiceManager_Exception_ExceptionInterface);
	ZEPHIR_INIT(ZendFramework_Server_Exception_ExceptionInterface);
	ZEPHIR_INIT(ZendFramework_Captcha_Exception_ExceptionInterface);
	ZEPHIR_INIT(ZendFramework_ModuleManager_Exception_ExceptionInterface);
	ZEPHIR_INIT(ZendFramework_Barcode_Object_Exception_ExceptionInterface);
	ZEPHIR_INIT(ZendFramework_Di_Exception_ExceptionInterface);
	ZEPHIR_INIT(ZendFramework_I18n_Exception_ExceptionInterface);
	ZEPHIR_INIT(ZendFramework_Stdlib_Exception_ExceptionInterface);
	ZEPHIR_INIT(ZendFramework_Tag_Exception_ExceptionInterface);
	ZEPHIR_INIT(ZendFramework_XmlRpc_Client_Exception_ExceptionInterface);
	ZEPHIR_INIT(ZendFramework_Loader_Exception_ExceptionInterface);
	ZEPHIR_INIT(ZendFramework_Mail_Storage_Exception_ExceptionInterface);
	ZEPHIR_INIT(ZendFramework_Filter_Exception_ExceptionInterface);
	ZEPHIR_INIT(ZendFramework_Http_Client_Adapter_Exception_ExceptionInterface);
	ZEPHIR_INIT(ZendFramework_Validator_Exception_ExceptionInterface);
	ZEPHIR_INIT(ZendFramework_File_Transfer_Exception_ExceptionInterface);
	ZEPHIR_INIT(ZendFramework_Form_Exception_ExceptionInterface);
	ZEPHIR_INIT(ZendFramework_Json_Server_Exception_ExceptionInterface);
	ZEPHIR_INIT(ZendFramework_View_Exception_ExceptionInterface);
	ZEPHIR_INIT(ZendFramework_Ldap_Exception_ExceptionInterface);
	ZEPHIR_INIT(ZendFramework_Math_BigInteger_Exception_ExceptionInterface);
	ZEPHIR_INIT(ZendFramework_Serializer_Exception_ExceptionInterface);
	ZEPHIR_INIT(ZendFramework_Text_Table_Exception_ExceptionInterface);
	ZEPHIR_INIT(ZendFramework_Barcode_Renderer_Exception_ExceptionInterface);
	ZEPHIR_INIT(ZendFramework_Loader_ShortNameLocator);
	ZEPHIR_INIT(ZendFramework_Navigation_Exception_ExceptionInterface);
	ZEPHIR_INIT(ZendFramework_Soap_Exception_ExceptionInterface);
	ZEPHIR_INIT(ZendFramework_Code_Reflection_Exception_ExceptionInterface);
	ZEPHIR_INIT(ZendFramework_Console_Exception_ExceptionInterface);
	ZEPHIR_INIT(ZendFramework_EventManager_Exception_ExceptionInterface);
	ZEPHIR_INIT(ZendFramework_Feed_Reader_Exception_ExceptionInterface);
	ZEPHIR_INIT(ZendFramework_Feed_Writer_Exception_ExceptionInterface);
	ZEPHIR_INIT(ZendFramework_Http_Header_Exception_ExceptionInterface);
	ZEPHIR_INIT(ZendFramework_Ldap_Converter_Exception_ExceptionInterface);
	ZEPHIR_INIT(ZendFramework_Loader_SplAutoloader);
	ZEPHIR_INIT(ZendFramework_Mail_Header_Exception_ExceptionInterface);
	ZEPHIR_INIT(ZendFramework_Mail_Transport_Exception_ExceptionInterface);
	ZEPHIR_INIT(ZendFramework_Paginator_Adapter_Exception_ExceptionInterface);
	ZEPHIR_INIT(ZendFramework_Permissions_Acl_Exception_ExceptionInterface);
	ZEPHIR_INIT(ZendFramework_Server_Reflection_Exception_ExceptionInterface);
	ZEPHIR_INIT(ZendFramework_Session_Exception_ExceptionInterface);
	ZEPHIR_INIT(ZendFramework_Text_Figlet_Exception_ExceptionInterface);
	ZEPHIR_INIT(ZendFramework_Uri_Exception_ExceptionInterface);
	ZEPHIR_INIT(ZendFramework_XmlRpc_Server_Exception_ExceptionInterface);
	ZEPHIR_INIT(ZendFramework_Authentication_Adapter_DbTable_Exception_ExceptionInterface);
	ZEPHIR_INIT(ZendFramework_Authentication_Adapter_Http_Exception_ExceptionInterface);
	ZEPHIR_INIT(ZendFramework_Code_Generator_Exception_ExceptionInterface);
	ZEPHIR_INIT(ZendFramework_Config_Exception_ExceptionInterface);
	ZEPHIR_INIT(ZendFramework_Crypt_Key_Derivation_Exception_ExceptionInterface);
	ZEPHIR_INIT(ZendFramework_Crypt_Password_Exception_ExceptionInterface);
	ZEPHIR_INIT(ZendFramework_Crypt_PublicKey_Rsa_Exception_ExceptionInterface);
	ZEPHIR_INIT(ZendFramework_Crypt_Symmetric_Exception_ExceptionInterface);
	ZEPHIR_INIT(ZendFramework_Db_ResultSet_Exception_ExceptionInterface);
	ZEPHIR_INIT(ZendFramework_Db_RowGateway_Exception_ExceptionInterface);
	ZEPHIR_INIT(ZendFramework_Db_Sql_Exception_ExceptionInterface);
	ZEPHIR_INIT(ZendFramework_Db_TableGateway_Exception_ExceptionInterface);
	ZEPHIR_INIT(ZendFramework_Dom_Exception_ExceptionInterface);
	ZEPHIR_INIT(ZendFramework_Escaper_Exception_ExceptionInterface);
	ZEPHIR_INIT(ZendFramework_Feed_PubSubHubbub_Exception_ExceptionInterface);
	ZEPHIR_INIT(ZendFramework_InputFilter_Exception_ExceptionInterface);
	ZEPHIR_INIT(ZendFramework_Log_Exception_ExceptionInterface);
	ZEPHIR_INIT(ZendFramework_Mail_Protocol_Exception_ExceptionInterface);
	ZEPHIR_INIT(ZendFramework_Mail_Storage_Part_Exception_ExceptionInterface);
	ZEPHIR_INIT(ZendFramework_Memory_Exception_ExceptionInterface);
	ZEPHIR_INIT(ZendFramework_ModuleManager_Listener_Exception_ExceptionInterface);
	ZEPHIR_INIT(ZendFramework_Mvc_Router_Exception_ExceptionInterface);
	ZEPHIR_INIT(ZendFramework_ProgressBar_Adapter_Exception_ExceptionInterface);
	ZEPHIR_INIT(ZendFramework_Stdlib_MessageInterface);
	ZEPHIR_INIT(ZendFramework_Db_Adapter_Driver_Sqlsrv_Exception_ExceptionInterface);
	ZEPHIR_INIT(ZendFramework_Ldap_Filter_Exception_ExceptionInterface);
	ZEPHIR_INIT(ZendFramework_Loader_PluginClassLocator);
	ZEPHIR_INIT(ZendFramework_Mime_Exception_ExceptionInterface);
	ZEPHIR_INIT(ZendFramework_Permissions_Rbac_Exception_ExceptionInterface);
	ZEPHIR_INIT(ZendFramework_Tag_Cloud_Decorator_Exception_ExceptionInterface);
	ZEPHIR_INIT(ZendFramework_Cache_Storage_FlushableInterface);
	ZEPHIR_INIT(ZendFramework_Cache_Storage_IterableInterface);
	ZEPHIR_INIT(ZendFramework_Cache_Storage_TaggableInterface);
	ZEPHIR_INIT(ZendFramework_Cache_Storage_TotalSpaceCapableInterface);
	ZEPHIR_INIT(ZendFramework_Config_Reader_ReaderInterface);
	ZEPHIR_INIT(ZendFramework_Filter_Compress_CompressionAlgorithmInterface);
	ZEPHIR_INIT(ZendFramework_Filter_Encrypt_EncryptionAlgorithmInterface);
	ZEPHIR_INIT(ZendFramework_Filter_FilterInterface);
	ZEPHIR_INIT(ZendFramework_Log_Filter_FilterInterface);
	ZEPHIR_INIT(ZendFramework_Log_Formatter_FormatterInterface);
	ZEPHIR_INIT(ZendFramework_Log_LoggerInterface);
	ZEPHIR_INIT(ZendFramework_Log_Processor_ProcessorInterface);
	ZEPHIR_INIT(ZendFramework_Log_Writer_ChromePhp_ChromePhpInterface);
	ZEPHIR_INIT(ZendFramework_Log_Writer_WriterInterface);
	ZEPHIR_INIT(ZendFramework_Stdlib_ArraySerializableInterface);
	ZEPHIR_INIT(ZendFramework_Stdlib_DispatchableInterface);
	ZEPHIR_INIT(ZendFramework_Stdlib_InitializableInterface);
	ZEPHIR_INIT(ZendFramework_Stdlib_ParameterObjectInterface);
	ZEPHIR_INIT(ZendFramework_Stdlib_ParametersInterface);
	ZEPHIR_INIT(ZendFramework_Stdlib_RequestInterface);
	ZEPHIR_INIT(ZendFramework_Stdlib_ResponseInterface);
	ZEPHIR_INIT(ZendFramework_Http_Exception_RuntimeException);
	ZEPHIR_INIT(ZendFramework_Db_Exception_RuntimeException);
	ZEPHIR_INIT(ZendFramework_Db_Exception_InvalidArgumentException);
	ZEPHIR_INIT(ZendFramework_Authentication_Exception_InvalidArgumentException);
	ZEPHIR_INIT(ZendFramework_Authentication_Exception_RuntimeException);
	ZEPHIR_INIT(ZendFramework_Barcode_Exception_InvalidArgumentException);
	ZEPHIR_INIT(ZendFramework_Barcode_Exception_RuntimeException);
	ZEPHIR_INIT(ZendFramework_Http_Client_Exception_RuntimeException);
	ZEPHIR_INIT(ZendFramework_Http_Exception_InvalidArgumentException);
	ZEPHIR_INIT(ZendFramework_Json_Exception_RuntimeException);
	ZEPHIR_INIT(ZendFramework_Mail_Exception_InvalidArgumentException);
	ZEPHIR_INIT(ZendFramework_Mail_Exception_RuntimeException);
	ZEPHIR_INIT(ZendFramework_XmlRpc_Exception_InvalidArgumentException);
	ZEPHIR_INIT(ZendFramework_XmlRpc_Exception_RuntimeException);
	ZEPHIR_INIT(ZendFramework_Crypt_Exception_InvalidArgumentException);
	ZEPHIR_INIT(ZendFramework_Crypt_Exception_RuntimeException);
	ZEPHIR_INIT(ZendFramework_Db_Exception_ErrorException);
	ZEPHIR_INIT(ZendFramework_Db_Exception_UnexpectedValueException);
	ZEPHIR_INIT(ZendFramework_File_Exception_RuntimeException);
	ZEPHIR_INIT(ZendFramework_Http_Exception_OutOfRangeException);
	ZEPHIR_INIT(ZendFramework_Math_Exception_RuntimeException);
	ZEPHIR_INIT(ZendFramework_ServiceManager_Exception_RuntimeException);
	ZEPHIR_INIT(ZendFramework_Cache_Exception_RuntimeException);
	ZEPHIR_INIT(ZendFramework_Di_Exception_InvalidArgumentException);
	ZEPHIR_INIT(ZendFramework_Feed_Exception_InvalidArgumentException);
	ZEPHIR_INIT(ZendFramework_Feed_Exception_RuntimeException);
	ZEPHIR_INIT(ZendFramework_Authentication_Adapter_Exception_InvalidArgumentException);
	ZEPHIR_INIT(ZendFramework_Authentication_Adapter_Exception_RuntimeException);
	ZEPHIR_INIT(ZendFramework_Barcode_Exception_OutOfRangeException);
	ZEPHIR_INIT(ZendFramework_Captcha_Exception_RuntimeException);
	ZEPHIR_INIT(ZendFramework_Code_Exception_InvalidArgumentException);
	ZEPHIR_INIT(ZendFramework_Code_Exception_RuntimeException);
	ZEPHIR_INIT(ZendFramework_Feed_Exception_BadMethodCallException);
	ZEPHIR_INIT(ZendFramework_Http_Client_Adapter_Exception_RuntimeException);
	ZEPHIR_INIT(ZendFramework_Loader_Exception_DomainException);
	ZEPHIR_INIT(ZendFramework_ModuleManager_Exception_RuntimeException);
	ZEPHIR_INIT(ZendFramework_Mvc_Exception_RuntimeException);
	ZEPHIR_INIT(ZendFramework_ProgressBar_Exception_RuntimeException);
	ZEPHIR_INIT(ZendFramework_Text_Exception_UnexpectedValueException);
	ZEPHIR_INIT(ZendFramework_Uri_Exception_InvalidArgumentException);
	ZEPHIR_INIT(ZendFramework_XmlRpc_Exception_BadMethodCallException);
	ZEPHIR_INIT(ZendFramework_Authentication_Exception_UnexpectedValueException);
	ZEPHIR_INIT(ZendFramework_Barcode_Exception_UnexpectedValueException);
	ZEPHIR_INIT(ZendFramework_Barcode_Object_Exception_InvalidArgumentException);
	ZEPHIR_INIT(ZendFramework_Barcode_Object_Exception_RuntimeException);
	ZEPHIR_INIT(ZendFramework_Captcha_Exception_InvalidArgumentException);
	ZEPHIR_INIT(ZendFramework_Code_Exception_BadMethodCallException);
	ZEPHIR_INIT(ZendFramework_Db_Adapter_Exception_ErrorException);
	ZEPHIR_INIT(ZendFramework_Db_Adapter_Exception_RuntimeException);
	ZEPHIR_INIT(ZendFramework_Db_Adapter_Exception_UnexpectedValueException);
	ZEPHIR_INIT(ZendFramework_EventManager_Exception_DomainException);
	ZEPHIR_INIT(ZendFramework_File_Exception_BadMethodCallException);
	ZEPHIR_INIT(ZendFramework_File_Exception_InvalidArgumentException);
	ZEPHIR_INIT(ZendFramework_File_Transfer_Exception_RuntimeException);
	ZEPHIR_INIT(ZendFramework_Filter_Exception_RuntimeException);
	ZEPHIR_INIT(ZendFramework_Form_Exception_DomainException);
	ZEPHIR_INIT(ZendFramework_Form_Exception_InvalidArgumentException);
	ZEPHIR_INIT(ZendFramework_Http_Client_Exception_InvalidArgumentException);
	ZEPHIR_INIT(ZendFramework_Http_Client_Exception_OutOfRangeException);
	ZEPHIR_INIT(ZendFramework_I18n_Exception_RuntimeException);
	ZEPHIR_INIT(ZendFramework_Json_Exception_BadMethodCallException);
	ZEPHIR_INIT(ZendFramework_Json_Exception_InvalidArgumentException);
	ZEPHIR_INIT(ZendFramework_Json_Server_Exception_RuntimeException);
	ZEPHIR_INIT(ZendFramework_Mail_Exception_BadMethodCallException);
	ZEPHIR_INIT(ZendFramework_Mail_Exception_DomainException);
	ZEPHIR_INIT(ZendFramework_Mail_Exception_OutOfBoundsException);
	ZEPHIR_INIT(ZendFramework_Mail_Storage_Exception_InvalidArgumentException);
	ZEPHIR_INIT(ZendFramework_Mail_Storage_Exception_RuntimeException);
	ZEPHIR_INIT(ZendFramework_Math_BigInteger_Exception_RuntimeException);
	ZEPHIR_INIT(ZendFramework_Math_Exception_InvalidArgumentException);
	ZEPHIR_INIT(ZendFramework_ModuleManager_Exception_InvalidArgumentException);
	ZEPHIR_INIT(ZendFramework_Mvc_Exception_InvalidArgumentException);
	ZEPHIR_INIT(ZendFramework_Paginator_Exception_InvalidArgumentException);
	ZEPHIR_INIT(ZendFramework_Paginator_Exception_RuntimeException);
	ZEPHIR_INIT(ZendFramework_Paginator_Exception_UnexpectedValueException);
	ZEPHIR_INIT(ZendFramework_ProgressBar_Exception_InvalidArgumentException);
	ZEPHIR_INIT(ZendFramework_Serializer_Exception_RuntimeException);
	ZEPHIR_INIT(ZendFramework_Server_Exception_BadMethodCallException);
	ZEPHIR_INIT(ZendFramework_Server_Exception_InvalidArgumentException);
	ZEPHIR_INIT(ZendFramework_Server_Exception_RuntimeException);
	ZEPHIR_INIT(ZendFramework_ServiceManager_Exception_InvalidArgumentException);
	ZEPHIR_INIT(ZendFramework_Stdlib_Exception_DomainException);
	ZEPHIR_INIT(ZendFramework_Stdlib_Exception_RuntimeException);
	ZEPHIR_INIT(ZendFramework_Tag_Exception_InvalidArgumentException);
	ZEPHIR_INIT(ZendFramework_Text_Exception_InvalidArgumentException);
	ZEPHIR_INIT(ZendFramework_Text_Exception_OutOfBoundsException);
	ZEPHIR_INIT(ZendFramework_Text_Exception_OverflowException);
	ZEPHIR_INIT(ZendFramework_Text_Exception_RuntimeException);
	ZEPHIR_INIT(ZendFramework_Validator_Exception_InvalidArgumentException);
	ZEPHIR_INIT(ZendFramework_Validator_Exception_RuntimeException);
	ZEPHIR_INIT(ZendFramework_XmlRpc_Client_Exception_InvalidArgumentException);
	ZEPHIR_INIT(ZendFramework_XmlRpc_Client_Exception_RuntimeException);
	ZEPHIR_INIT(ZendFramework_Authentication_Adapter_DbTable_Exception_InvalidArgumentException);
	ZEPHIR_INIT(ZendFramework_Authentication_Adapter_DbTable_Exception_RuntimeException);
	ZEPHIR_INIT(ZendFramework_Authentication_Adapter_Exception_UnexpectedValueException);
	ZEPHIR_INIT(ZendFramework_Authentication_Adapter_Http_Exception_InvalidArgumentException);
	ZEPHIR_INIT(ZendFramework_Authentication_Adapter_Http_Exception_RuntimeException);
	ZEPHIR_INIT(ZendFramework_Barcode_Exception_RendererCreationException);
	ZEPHIR_INIT(ZendFramework_Barcode_Object_Exception_BarcodeValidationException);
	ZEPHIR_INIT(ZendFramework_Barcode_Object_Exception_ExtensionNotLoadedException);
	ZEPHIR_INIT(ZendFramework_Barcode_Object_Exception_OutOfRangeException);
	ZEPHIR_INIT(ZendFramework_Barcode_Renderer_Exception_InvalidArgumentException);
	ZEPHIR_INIT(ZendFramework_Barcode_Renderer_Exception_OutOfRangeException);
	ZEPHIR_INIT(ZendFramework_Barcode_Renderer_Exception_RuntimeException);
	ZEPHIR_INIT(ZendFramework_Barcode_Renderer_Exception_UnexpectedValueException);
	ZEPHIR_INIT(ZendFramework_Cache_Exception_BadMethodCallException);
	ZEPHIR_INIT(ZendFramework_Cache_Exception_ExtensionNotLoadedException);
	ZEPHIR_INIT(ZendFramework_Cache_Exception_InvalidArgumentException);
	ZEPHIR_INIT(ZendFramework_Cache_Exception_LogicException);
	ZEPHIR_INIT(ZendFramework_Cache_Exception_MissingDependencyException);
	ZEPHIR_INIT(ZendFramework_Cache_Exception_MissingKeyException);
	ZEPHIR_INIT(ZendFramework_Cache_Exception_OutOfSpaceException);
	ZEPHIR_INIT(ZendFramework_Cache_Exception_UnexpectedValueException);
	ZEPHIR_INIT(ZendFramework_Cache_Exception_UnsupportedMethodCallException);
	ZEPHIR_INIT(ZendFramework_Captcha_Exception_DomainException);
	ZEPHIR_INIT(ZendFramework_Captcha_Exception_ExtensionNotLoadedException);
	ZEPHIR_INIT(ZendFramework_Captcha_Exception_ImageNotLoadableException);
	ZEPHIR_INIT(ZendFramework_Captcha_Exception_NoFontProvidedException);
	ZEPHIR_INIT(ZendFramework_Code_Generator_Exception_InvalidArgumentException);
	ZEPHIR_INIT(ZendFramework_Code_Generator_Exception_RuntimeException);
	ZEPHIR_INIT(ZendFramework_Code_Reflection_Exception_BadMethodCallException);
	ZEPHIR_INIT(ZendFramework_Code_Reflection_Exception_InvalidArgumentException);
	ZEPHIR_INIT(ZendFramework_Code_Reflection_Exception_RuntimeException);
	ZEPHIR_INIT(ZendFramework_Config_Exception_InvalidArgumentException);
	ZEPHIR_INIT(ZendFramework_Config_Exception_RuntimeException);
	ZEPHIR_INIT(ZendFramework_Console_Exception_BadMethodCallException);
	ZEPHIR_INIT(ZendFramework_Console_Exception_InvalidArgumentException);
	ZEPHIR_INIT(ZendFramework_Console_Exception_RuntimeException);
	ZEPHIR_INIT(ZendFramework_Crypt_Key_Derivation_Exception_InvalidArgumentException);
	ZEPHIR_INIT(ZendFramework_Crypt_Key_Derivation_Exception_RuntimeException);
	ZEPHIR_INIT(ZendFramework_Crypt_Password_Exception_InvalidArgumentException);
	ZEPHIR_INIT(ZendFramework_Crypt_Password_Exception_RuntimeException);
	ZEPHIR_INIT(ZendFramework_Crypt_PublicKey_Rsa_Exception_InvalidArgumentException);
	ZEPHIR_INIT(ZendFramework_Crypt_PublicKey_Rsa_Exception_RuntimeException);
	ZEPHIR_INIT(ZendFramework_Crypt_Symmetric_Exception_InvalidArgumentException);
	ZEPHIR_INIT(ZendFramework_Crypt_Symmetric_Exception_RuntimeException);
	ZEPHIR_INIT(ZendFramework_Db_Adapter_Driver_Sqlsrv_Exception_ErrorException);
	ZEPHIR_INIT(ZendFramework_Db_Adapter_Exception_InvalidArgumentException);
	ZEPHIR_INIT(ZendFramework_Db_Adapter_Exception_InvalidConnectionParametersException);
	ZEPHIR_INIT(ZendFramework_Db_Adapter_Exception_InvalidQueryException);
	ZEPHIR_INIT(ZendFramework_Db_ResultSet_Exception_InvalidArgumentException);
	ZEPHIR_INIT(ZendFramework_Db_ResultSet_Exception_RuntimeException);
	ZEPHIR_INIT(ZendFramework_Db_RowGateway_Exception_InvalidArgumentException);
	ZEPHIR_INIT(ZendFramework_Db_RowGateway_Exception_RuntimeException);
	ZEPHIR_INIT(ZendFramework_Db_Sql_Exception_InvalidArgumentException);
	ZEPHIR_INIT(ZendFramework_Db_Sql_Exception_RuntimeException);
	ZEPHIR_INIT(ZendFramework_Db_TableGateway_Exception_InvalidArgumentException);
	ZEPHIR_INIT(ZendFramework_Db_TableGateway_Exception_RuntimeException);
	ZEPHIR_INIT(ZendFramework_Di_Exception_CircularDependencyException);
	ZEPHIR_INIT(ZendFramework_Di_Exception_ClassNotFoundException);
	ZEPHIR_INIT(ZendFramework_Di_Exception_InvalidCallbackException);
	ZEPHIR_INIT(ZendFramework_Di_Exception_InvalidParamNameException);
	ZEPHIR_INIT(ZendFramework_Di_Exception_InvalidPositionException);
	ZEPHIR_INIT(ZendFramework_Di_Exception_MissingPropertyException);
	ZEPHIR_INIT(ZendFramework_Di_Exception_RuntimeException);
	ZEPHIR_INIT(ZendFramework_Di_Exception_UndefinedReferenceException);
	ZEPHIR_INIT(ZendFramework_Dom_Exception_BadMethodCallException);
	ZEPHIR_INIT(ZendFramework_Dom_Exception_RuntimeException);
	ZEPHIR_INIT(ZendFramework_Escaper_Exception_InvalidArgumentException);
	ZEPHIR_INIT(ZendFramework_Escaper_Exception_RuntimeException);
	ZEPHIR_INIT(ZendFramework_EventManager_Exception_InvalidArgumentException);
	ZEPHIR_INIT(ZendFramework_EventManager_Exception_InvalidCallbackException);
	ZEPHIR_INIT(ZendFramework_Feed_PubSubHubbub_Exception_InvalidArgumentException);
	ZEPHIR_INIT(ZendFramework_Feed_PubSubHubbub_Exception_RuntimeException);
	ZEPHIR_INIT(ZendFramework_Feed_Reader_Exception_BadMethodCallException);
	ZEPHIR_INIT(ZendFramework_Feed_Reader_Exception_InvalidArgumentException);
	ZEPHIR_INIT(ZendFramework_Feed_Reader_Exception_RuntimeException);
	ZEPHIR_INIT(ZendFramework_Feed_Writer_Exception_BadMethodCallException);
	ZEPHIR_INIT(ZendFramework_Feed_Writer_Exception_InvalidArgumentException);
	ZEPHIR_INIT(ZendFramework_Feed_Writer_Exception_RuntimeException);
	ZEPHIR_INIT(ZendFramework_File_Transfer_Exception_BadMethodCallException);
	ZEPHIR_INIT(ZendFramework_File_Transfer_Exception_InvalidArgumentException);
	ZEPHIR_INIT(ZendFramework_File_Transfer_Exception_PhpEnvironmentException);
	ZEPHIR_INIT(ZendFramework_Filter_Exception_BadMethodCallException);
	ZEPHIR_INIT(ZendFramework_Filter_Exception_DomainException);
	ZEPHIR_INIT(ZendFramework_Filter_Exception_ExtensionNotLoadedException);
	ZEPHIR_INIT(ZendFramework_Filter_Exception_InvalidArgumentException);
	ZEPHIR_INIT(ZendFramework_Form_Exception_BadMethodCallException);
	ZEPHIR_INIT(ZendFramework_Form_Exception_ExtensionNotLoadedException);
	ZEPHIR_INIT(ZendFramework_Form_Exception_InvalidElementException);
	ZEPHIR_INIT(ZendFramework_Form_Exception_UnexpectedValueException);
	ZEPHIR_INIT(ZendFramework_Http_Client_Adapter_Exception_InitializationException);
	ZEPHIR_INIT(ZendFramework_Http_Client_Adapter_Exception_InvalidArgumentException);
	ZEPHIR_INIT(ZendFramework_Http_Client_Adapter_Exception_OutOfRangeException);
	ZEPHIR_INIT(ZendFramework_Http_Client_Adapter_Exception_TimeoutException);
	ZEPHIR_INIT(ZendFramework_Http_Header_Exception_DomainException);
	ZEPHIR_INIT(ZendFramework_Http_Header_Exception_InvalidArgumentException);
	ZEPHIR_INIT(ZendFramework_Http_Header_Exception_RuntimeException);
	ZEPHIR_INIT(ZendFramework_I18n_Exception_ExtensionNotLoadedException);
	ZEPHIR_INIT(ZendFramework_I18n_Exception_InvalidArgumentException);
	ZEPHIR_INIT(ZendFramework_I18n_Exception_OutOfBoundsException);
	ZEPHIR_INIT(ZendFramework_I18n_Exception_ParseException);
	ZEPHIR_INIT(ZendFramework_I18n_Exception_RangeException);
	ZEPHIR_INIT(ZendFramework_InputFilter_Exception_InvalidArgumentException);
	ZEPHIR_INIT(ZendFramework_InputFilter_Exception_RuntimeException);
	ZEPHIR_INIT(ZendFramework_Json_Exception_RecursionException);
	ZEPHIR_INIT(ZendFramework_Json_Server_Exception_ErrorException);
	ZEPHIR_INIT(ZendFramework_Json_Server_Exception_HttpException);
	ZEPHIR_INIT(ZendFramework_Json_Server_Exception_InvalidArgumentException);
	ZEPHIR_INIT(ZendFramework_Ldap_Converter_Exception_ConverterException);
	ZEPHIR_INIT(ZendFramework_Ldap_Converter_Exception_InvalidArgumentException);
	ZEPHIR_INIT(ZendFramework_Ldap_Converter_Exception_UnexpectedValueException);
	ZEPHIR_INIT(ZendFramework_Ldap_Exception_BadMethodCallException);
	ZEPHIR_INIT(ZendFramework_Ldap_Exception_InvalidArgumentException);
	ZEPHIR_INIT(ZendFramework_Ldap_Exception_LdapException);
	ZEPHIR_INIT(ZendFramework_Ldap_Filter_Exception_FilterException);
	ZEPHIR_INIT(ZendFramework_Loader_AutoloaderFactory);
	ZEPHIR_INIT(ZendFramework_Loader_ClassMapAutoloader);
	ZEPHIR_INIT(ZendFramework_Loader_Exception_BadMethodCallException);
	ZEPHIR_INIT(ZendFramework_Loader_Exception_InvalidArgumentException);
	ZEPHIR_INIT(ZendFramework_Loader_Exception_InvalidPathException);
	ZEPHIR_INIT(ZendFramework_Loader_Exception_MissingResourceNamespaceException);
	ZEPHIR_INIT(ZendFramework_Loader_Exception_PluginLoaderException);
	ZEPHIR_INIT(ZendFramework_Loader_Exception_RuntimeException);
	ZEPHIR_INIT(ZendFramework_Loader_Exception_SecurityException);
	ZEPHIR_INIT(ZendFramework_Loader_ModuleAutoloader);
	ZEPHIR_INIT(ZendFramework_Loader_PluginClassLoader);
	ZEPHIR_INIT(ZendFramework_Loader_StandardAutoloader);
	ZEPHIR_INIT(ZendFramework_Log_Exception_InvalidArgumentException);
	ZEPHIR_INIT(ZendFramework_Log_Exception_RuntimeException);
	ZEPHIR_INIT(ZendFramework_Mail_Header_Exception_BadMethodCallException);
	ZEPHIR_INIT(ZendFramework_Mail_Header_Exception_InvalidArgumentException);
	ZEPHIR_INIT(ZendFramework_Mail_Header_Exception_RuntimeException);
	ZEPHIR_INIT(ZendFramework_Mail_Protocol_Exception_InvalidArgumentException);
	ZEPHIR_INIT(ZendFramework_Mail_Protocol_Exception_RuntimeException);
	ZEPHIR_INIT(ZendFramework_Mail_Storage_Exception_OutOfBoundsException);
	ZEPHIR_INIT(ZendFramework_Mail_Storage_Part_Exception_InvalidArgumentException);
	ZEPHIR_INIT(ZendFramework_Mail_Storage_Part_Exception_RuntimeException);
	ZEPHIR_INIT(ZendFramework_Mail_Transport_Exception_DomainException);
	ZEPHIR_INIT(ZendFramework_Mail_Transport_Exception_InvalidArgumentException);
	ZEPHIR_INIT(ZendFramework_Mail_Transport_Exception_RuntimeException);
	ZEPHIR_INIT(ZendFramework_Math_BigInteger_Exception_DivisionByZeroException);
	ZEPHIR_INIT(ZendFramework_Math_BigInteger_Exception_InvalidArgumentException);
	ZEPHIR_INIT(ZendFramework_Math_Exception_DomainException);
	ZEPHIR_INIT(ZendFramework_Memory_Exception_InvalidArgumentException);
	ZEPHIR_INIT(ZendFramework_Memory_Exception_RuntimeException);
	ZEPHIR_INIT(ZendFramework_Mime_Exception_RuntimeException);
	ZEPHIR_INIT(ZendFramework_ModuleManager_Exception_MissingDependencyModuleException);
	ZEPHIR_INIT(ZendFramework_ModuleManager_Listener_Exception_InvalidArgumentException);
	ZEPHIR_INIT(ZendFramework_ModuleManager_Listener_Exception_RuntimeException);
	ZEPHIR_INIT(ZendFramework_Mvc_Exception_BadMethodCallException);
	ZEPHIR_INIT(ZendFramework_Mvc_Exception_DomainException);
	ZEPHIR_INIT(ZendFramework_Mvc_Exception_InvalidControllerException);
	ZEPHIR_INIT(ZendFramework_Mvc_Exception_InvalidPluginException);
	ZEPHIR_INIT(ZendFramework_Mvc_Exception_MissingLocatorException);
	ZEPHIR_INIT(ZendFramework_Mvc_Router_Exception_InvalidArgumentException);
	ZEPHIR_INIT(ZendFramework_Mvc_Router_Exception_RuntimeException);
	ZEPHIR_INIT(ZendFramework_Navigation_Exception_BadMethodCallException);
	ZEPHIR_INIT(ZendFramework_Navigation_Exception_DomainException);
	ZEPHIR_INIT(ZendFramework_Navigation_Exception_InvalidArgumentException);
	ZEPHIR_INIT(ZendFramework_Navigation_Exception_OutOfBoundsException);
	ZEPHIR_INIT(ZendFramework_Paginator_Adapter_Exception_InvalidArgumentException);
	ZEPHIR_INIT(ZendFramework_Paginator_Adapter_Exception_RuntimeException);
	ZEPHIR_INIT(ZendFramework_Paginator_Adapter_Exception_UnexpectedValueException);
	ZEPHIR_INIT(ZendFramework_Permissions_Acl_Assertion_Exception_InvalidAssertionException);
	ZEPHIR_INIT(ZendFramework_Permissions_Acl_Exception_InvalidArgumentException);
	ZEPHIR_INIT(ZendFramework_Permissions_Acl_Exception_RuntimeException);
	ZEPHIR_INIT(ZendFramework_Permissions_Rbac_Exception_InvalidArgumentException);
	ZEPHIR_INIT(ZendFramework_ProgressBar_Adapter_Exception_InvalidArgumentException);
	ZEPHIR_INIT(ZendFramework_ProgressBar_Adapter_Exception_RuntimeException);
	ZEPHIR_INIT(ZendFramework_ProgressBar_Exception_OutOfRangeException);
	ZEPHIR_INIT(ZendFramework_ProgressBar_Exception_PhpEnvironmentException);
	ZEPHIR_INIT(ZendFramework_Serializer_Exception_ExtensionNotLoadedException);
	ZEPHIR_INIT(ZendFramework_Serializer_Exception_InvalidArgumentException);
	ZEPHIR_INIT(ZendFramework_Server_Reflection_Exception_BadMethodCallException);
	ZEPHIR_INIT(ZendFramework_Server_Reflection_Exception_InvalidArgumentException);
	ZEPHIR_INIT(ZendFramework_Server_Reflection_Exception_RuntimeException);
	ZEPHIR_INIT(ZendFramework_ServiceManager_Exception_CircularDependencyFoundException);
	ZEPHIR_INIT(ZendFramework_ServiceManager_Exception_CircularReferenceException);
	ZEPHIR_INIT(ZendFramework_ServiceManager_Exception_InvalidServiceNameException);
	ZEPHIR_INIT(ZendFramework_ServiceManager_Exception_ServiceNotCreatedException);
	ZEPHIR_INIT(ZendFramework_ServiceManager_Exception_ServiceNotFoundException);
	ZEPHIR_INIT(ZendFramework_Session_Exception_BadMethodCallException);
	ZEPHIR_INIT(ZendFramework_Session_Exception_InvalidArgumentException);
	ZEPHIR_INIT(ZendFramework_Session_Exception_RuntimeException);
	ZEPHIR_INIT(ZendFramework_Soap_Exception_BadMethodCallException);
	ZEPHIR_INIT(ZendFramework_Soap_Exception_ExtensionNotLoadedException);
	ZEPHIR_INIT(ZendFramework_Soap_Exception_InvalidArgumentException);
	ZEPHIR_INIT(ZendFramework_Soap_Exception_RuntimeException);
	ZEPHIR_INIT(ZendFramework_Soap_Exception_UnexpectedValueException);
	ZEPHIR_INIT(ZendFramework_Stdlib_ArrayStack);
	ZEPHIR_INIT(ZendFramework_Stdlib_Exception_BadMethodCallException);
	ZEPHIR_INIT(ZendFramework_Stdlib_Exception_ExtensionNotLoadedException);
	ZEPHIR_INIT(ZendFramework_Stdlib_Exception_InvalidArgumentException);
	ZEPHIR_INIT(ZendFramework_Stdlib_Exception_InvalidCallbackException);
	ZEPHIR_INIT(ZendFramework_Stdlib_Exception_LogicException);
	ZEPHIR_INIT(ZendFramework_Stdlib_PriorityList);
	ZEPHIR_INIT(ZendFramework_Stdlib_PriorityQueue);
	ZEPHIR_INIT(ZendFramework_Stdlib_SplQueue);
	ZEPHIR_INIT(ZendFramework_Stdlib_SplStack);
	ZEPHIR_INIT(ZendFramework_Tag_Cloud_Decorator_Exception_InvalidArgumentException);
	ZEPHIR_INIT(ZendFramework_Tag_Exception_InvalidAttributeNameException);
	ZEPHIR_INIT(ZendFramework_Tag_Exception_InvalidElementNameException);
	ZEPHIR_INIT(ZendFramework_Tag_Exception_OutOfBoundsException);
	ZEPHIR_INIT(ZendFramework_Text_Figlet_Exception_InvalidArgumentException);
	ZEPHIR_INIT(ZendFramework_Text_Figlet_Exception_RuntimeException);
	ZEPHIR_INIT(ZendFramework_Text_Figlet_Exception_UnexpectedValueException);
	ZEPHIR_INIT(ZendFramework_Text_Table_Exception_InvalidArgumentException);
	ZEPHIR_INIT(ZendFramework_Text_Table_Exception_InvalidDecoratorException);
	ZEPHIR_INIT(ZendFramework_Text_Table_Exception_OutOfBoundsException);
	ZEPHIR_INIT(ZendFramework_Text_Table_Exception_OverflowException);
	ZEPHIR_INIT(ZendFramework_Text_Table_Exception_UnexpectedValueException);
	ZEPHIR_INIT(ZendFramework_Uri_Exception_InvalidUriException);
	ZEPHIR_INIT(ZendFramework_Uri_Exception_InvalidUriPartException);
	ZEPHIR_INIT(ZendFramework_Validator_Exception_BadMethodCallException);
	ZEPHIR_INIT(ZendFramework_Validator_Exception_ExtensionNotLoadedException);
	ZEPHIR_INIT(ZendFramework_Validator_Exception_InvalidMagicMimeFileException);
	ZEPHIR_INIT(ZendFramework_View_Exception_BadMethodCallException);
	ZEPHIR_INIT(ZendFramework_View_Exception_DomainException);
	ZEPHIR_INIT(ZendFramework_View_Exception_InvalidArgumentException);
	ZEPHIR_INIT(ZendFramework_View_Exception_InvalidHelperException);
	ZEPHIR_INIT(ZendFramework_View_Exception_RuntimeException);
	ZEPHIR_INIT(ZendFramework_View_Exception_UnexpectedValueException);
	ZEPHIR_INIT(ZendFramework_XmlRpc_Client_Exception_FaultException);
	ZEPHIR_INIT(ZendFramework_XmlRpc_Client_Exception_HttpException);
	ZEPHIR_INIT(ZendFramework_XmlRpc_Client_Exception_IntrospectException);
	ZEPHIR_INIT(ZendFramework_XmlRpc_Exception_ValueException);
	ZEPHIR_INIT(ZendFramework_XmlRpc_Server_Exception_BadMethodCallException);
	ZEPHIR_INIT(ZendFramework_XmlRpc_Server_Exception_InvalidArgumentException);
	ZEPHIR_INIT(ZendFramework_XmlRpc_Server_Exception_RuntimeException);

#if PHP_VERSION_ID < 50500
	setlocale(LC_ALL, old_lc_all);
	free(old_lc_all);
#endif
	return SUCCESS;
}

#ifndef ZEPHIR_RELEASE
static PHP_MSHUTDOWN_FUNCTION(zendframework)
{

	zephir_deinitialize_memory(TSRMLS_C);

	return SUCCESS;
}
#endif

/**
 * Initialize globals on each request or each thread started
 */
static void php_zephir_init_globals(zend_zendframework_globals *zephir_globals TSRMLS_DC)
{
	zephir_globals->initialized = 0;

	/* Memory options */
	zephir_globals->active_memory = NULL;

	/* Virtual Symbol Tables */
	zephir_globals->active_symbol_table = NULL;

	/* Cache Enabled */
#if PHP_VERSION_ID < 50600
	zephir_globals->cache_enabled = 1;
#else
	zephir_globals->cache_enabled = 0;
#endif

	/* Recursive Lock */
	zephir_globals->recursive_lock = 0;


}

static PHP_RINIT_FUNCTION(zendframework)
{

	zend_zendframework_globals *zephir_globals_ptr = ZEPHIR_VGLOBAL;

	php_zephir_init_globals(zephir_globals_ptr TSRMLS_CC);
	//zephir_init_interned_strings(TSRMLS_C);

	zephir_initialize_memory(zephir_globals_ptr TSRMLS_CC);

	return SUCCESS;
}

static PHP_RSHUTDOWN_FUNCTION(zendframework)
{

	

	zephir_deinitialize_memory(TSRMLS_C);
	return SUCCESS;
}

static PHP_MINFO_FUNCTION(zendframework)
{
	php_info_print_box_start(0);
	php_printf("%s", PHP_ZENDFRAMEWORK_DESCRIPTION);
	php_info_print_box_end();

	php_info_print_table_start();
	php_info_print_table_header(2, PHP_ZENDFRAMEWORK_NAME, "enabled");
	php_info_print_table_row(2, "Author", PHP_ZENDFRAMEWORK_AUTHOR);
	php_info_print_table_row(2, "Version", PHP_ZENDFRAMEWORK_VERSION);
	php_info_print_table_row(2, "Powered by Zephir", "Version " PHP_ZENDFRAMEWORK_ZEPVERSION);
	php_info_print_table_end();


}

static PHP_GINIT_FUNCTION(zendframework)
{
	php_zephir_init_globals(zendframework_globals TSRMLS_CC);
}

static PHP_GSHUTDOWN_FUNCTION(zendframework)
{

}

zend_module_entry zendframework_module_entry = {
	STANDARD_MODULE_HEADER_EX,
	NULL,
	NULL,
	PHP_ZENDFRAMEWORK_EXTNAME,
	NULL,
	PHP_MINIT(zendframework),
#ifndef ZEPHIR_RELEASE
	PHP_MSHUTDOWN(zendframework),
#else
	NULL,
#endif
	PHP_RINIT(zendframework),
	PHP_RSHUTDOWN(zendframework),
	PHP_MINFO(zendframework),
	PHP_ZENDFRAMEWORK_VERSION,
	ZEND_MODULE_GLOBALS(zendframework),
	PHP_GINIT(zendframework),
	PHP_GSHUTDOWN(zendframework),
	NULL,
	STANDARD_MODULE_PROPERTIES_EX
};

#ifdef COMPILE_DL_ZENDFRAMEWORK
ZEND_GET_MODULE(zendframework)
#endif
