
/* This file was generated automatically by Zephir do not modify it! */

#ifndef ZEPHIR_CLASS_ENTRIES_H
#define ZEPHIR_CLASS_ENTRIES_H

#include "zendframework/cache/exception/badmethodcallexception.zep.h"
#include "zendframework/cache/exception/exceptioninterface.zep.h"
#include "zendframework/cache/exception/extensionnotloadedexception.zep.h"
#include "zendframework/cache/exception/invalidargumentexception.zep.h"
#include "zendframework/cache/exception/logicexception.zep.h"
#include "zendframework/cache/exception/missingdependencyexception.zep.h"
#include "zendframework/cache/exception/missingkeyexception.zep.h"
#include "zendframework/cache/exception/outofspaceexception.zep.h"
#include "zendframework/cache/exception/runtimeexception.zep.h"
#include "zendframework/cache/exception/unexpectedvalueexception.zep.h"
#include "zendframework/cache/exception/unsupportedmethodcallexception.zep.h"
#include "zendframework/cache/storage/flushableinterface.zep.h"
#include "zendframework/cache/storage/iterableinterface.zep.h"
#include "zendframework/cache/storage/taggableinterface.zep.h"
#include "zendframework/cache/storage/totalspacecapableinterface.zep.h"
#include "zendframework/config/exception/exceptioninterface.zep.h"
#include "zendframework/config/exception/invalidargumentexception.zep.h"
#include "zendframework/config/exception/runtimeexception.zep.h"
#include "zendframework/config/reader/readerinterface.zep.h"
#include "zendframework/filter/compress/compressionalgorithminterface.zep.h"
#include "zendframework/filter/encrypt/encryptionalgorithminterface.zep.h"
#include "zendframework/filter/exception/badmethodcallexception.zep.h"
#include "zendframework/filter/exception/domainexception.zep.h"
#include "zendframework/filter/exception/exceptioninterface.zep.h"
#include "zendframework/filter/exception/extensionnotloadedexception.zep.h"
#include "zendframework/filter/exception/invalidargumentexception.zep.h"
#include "zendframework/filter/exception/runtimeexception.zep.h"
#include "zendframework/filter/filterinterface.zep.h"
#include "zendframework/loader/autoloaderfactory.zep.h"
#include "zendframework/loader/classmapautoloader.zep.h"
#include "zendframework/loader/exception/badmethodcallexception.zep.h"
#include "zendframework/loader/exception/domainexception.zep.h"
#include "zendframework/loader/exception/exceptioninterface.zep.h"
#include "zendframework/loader/exception/invalidargumentexception.zep.h"
#include "zendframework/loader/exception/invalidpathexception.zep.h"
#include "zendframework/loader/exception/missingresourcenamespaceexception.zep.h"
#include "zendframework/loader/exception/pluginloaderexception.zep.h"
#include "zendframework/loader/exception/runtimeexception.zep.h"
#include "zendframework/loader/exception/securityexception.zep.h"
#include "zendframework/loader/moduleautoloader.zep.h"
#include "zendframework/loader/pluginclassloader.zep.h"
#include "zendframework/loader/pluginclasslocator.zep.h"
#include "zendframework/loader/shortnamelocator.zep.h"
#include "zendframework/loader/splautoloader.zep.h"
#include "zendframework/loader/standardautoloader.zep.h"
#include "zendframework/log/exception/exceptioninterface.zep.h"
#include "zendframework/log/exception/invalidargumentexception.zep.h"
#include "zendframework/log/exception/runtimeexception.zep.h"
#include "zendframework/log/filter/filterinterface.zep.h"
#include "zendframework/log/formatter/formatterinterface.zep.h"
#include "zendframework/log/loggerinterface.zep.h"
#include "zendframework/log/processor/processorinterface.zep.h"
#include "zendframework/log/writer/chromephp/chromephpinterface.zep.h"
#include "zendframework/log/writer/writerinterface.zep.h"

#endif