
extern zend_class_entry *zendframework_permissions_acl_resource_genericresource_ce;

ZEPHIR_INIT_CLASS(ZendFramework_Permissions_Acl_Resource_GenericResource);

PHP_METHOD(ZendFramework_Permissions_Acl_Resource_GenericResource, __construct);
PHP_METHOD(ZendFramework_Permissions_Acl_Resource_GenericResource, getResourceId);
PHP_METHOD(ZendFramework_Permissions_Acl_Resource_GenericResource, __toString);

ZEND_BEGIN_ARG_INFO_EX(arginfo_zendframework_permissions_acl_resource_genericresource___construct, 0, 0, 1)
	ZEND_ARG_INFO(0, resourceId)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(zendframework_permissions_acl_resource_genericresource_method_entry) {
	PHP_ME(ZendFramework_Permissions_Acl_Resource_GenericResource, __construct, arginfo_zendframework_permissions_acl_resource_genericresource___construct, ZEND_ACC_PUBLIC|ZEND_ACC_CTOR)
	PHP_ME(ZendFramework_Permissions_Acl_Resource_GenericResource, getResourceId, NULL, ZEND_ACC_PUBLIC)
	PHP_ME(ZendFramework_Permissions_Acl_Resource_GenericResource, __toString, NULL, ZEND_ACC_PUBLIC)
  PHP_FE_END
};
