
extern zend_class_entry *zendframework_modulemanager_modulemanagerinterface_ce;

ZEPHIR_INIT_CLASS(ZendFramework_ModuleManager_ModuleManagerInterface);

ZEND_BEGIN_ARG_INFO_EX(arginfo_zendframework_modulemanager_modulemanagerinterface_loadmodule, 0, 0, 1)
	ZEND_ARG_INFO(0, moduleName)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_INFO_EX(arginfo_zendframework_modulemanager_modulemanagerinterface_getloadedmodules, 0, 0, 1)
	ZEND_ARG_INFO(0, loadModules)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_INFO_EX(arginfo_zendframework_modulemanager_modulemanagerinterface_setmodules, 0, 0, 1)
	ZEND_ARG_INFO(0, modules)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(zendframework_modulemanager_modulemanagerinterface_method_entry) {
	PHP_ABSTRACT_ME(ZendFramework_ModuleManager_ModuleManagerInterface, loadModules, NULL)
	PHP_ABSTRACT_ME(ZendFramework_ModuleManager_ModuleManagerInterface, loadModule, arginfo_zendframework_modulemanager_modulemanagerinterface_loadmodule)
	PHP_ABSTRACT_ME(ZendFramework_ModuleManager_ModuleManagerInterface, getLoadedModules, arginfo_zendframework_modulemanager_modulemanagerinterface_getloadedmodules)
	PHP_ABSTRACT_ME(ZendFramework_ModuleManager_ModuleManagerInterface, getModules, NULL)
	PHP_ABSTRACT_ME(ZendFramework_ModuleManager_ModuleManagerInterface, setModules, arginfo_zendframework_modulemanager_modulemanagerinterface_setmodules)
  PHP_FE_END
};
