
extern zend_class_entry *zendframework_console_routematcher_routematcherinterface_ce;

ZEPHIR_INIT_CLASS(ZendFramework_Console_RouteMatcher_RouteMatcherInterface);

ZEND_BEGIN_ARG_INFO_EX(arginfo_zendframework_console_routematcher_routematcherinterface_match, 0, 0, 1)
	ZEND_ARG_ARRAY_INFO(0, params, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(zendframework_console_routematcher_routematcherinterface_method_entry) {
	PHP_ABSTRACT_ME(ZendFramework_Console_RouteMatcher_RouteMatcherInterface, match, arginfo_zendframework_console_routematcher_routematcherinterface_match)
  PHP_FE_END
};
