
extern zend_class_entry *zendframework_di_definition_arraydefinition_ce;

ZEPHIR_INIT_CLASS(ZendFramework_Di_Definition_ArrayDefinition);

PHP_METHOD(ZendFramework_Di_Definition_ArrayDefinition, __construct);
PHP_METHOD(ZendFramework_Di_Definition_ArrayDefinition, getClasses);
PHP_METHOD(ZendFramework_Di_Definition_ArrayDefinition, hasClass);
PHP_METHOD(ZendFramework_Di_Definition_ArrayDefinition, getClassSupertypes);
PHP_METHOD(ZendFramework_Di_Definition_ArrayDefinition, getInstantiator);
PHP_METHOD(ZendFramework_Di_Definition_ArrayDefinition, hasMethods);
PHP_METHOD(ZendFramework_Di_Definition_ArrayDefinition, hasMethod);
PHP_METHOD(ZendFramework_Di_Definition_ArrayDefinition, getMethods);
PHP_METHOD(ZendFramework_Di_Definition_ArrayDefinition, hasMethodParameters);
PHP_METHOD(ZendFramework_Di_Definition_ArrayDefinition, getMethodParameters);
PHP_METHOD(ZendFramework_Di_Definition_ArrayDefinition, toArray);

ZEND_BEGIN_ARG_INFO_EX(arginfo_zendframework_di_definition_arraydefinition___construct, 0, 0, 1)
	ZEND_ARG_ARRAY_INFO(0, dataArray, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_INFO_EX(arginfo_zendframework_di_definition_arraydefinition_hasclass, 0, 0, 1)
	ZEND_ARG_INFO(0, class)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_INFO_EX(arginfo_zendframework_di_definition_arraydefinition_getclasssupertypes, 0, 0, 1)
	ZEND_ARG_INFO(0, class)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_INFO_EX(arginfo_zendframework_di_definition_arraydefinition_getinstantiator, 0, 0, 1)
	ZEND_ARG_INFO(0, class)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_INFO_EX(arginfo_zendframework_di_definition_arraydefinition_hasmethods, 0, 0, 1)
	ZEND_ARG_INFO(0, class)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_INFO_EX(arginfo_zendframework_di_definition_arraydefinition_hasmethod, 0, 0, 2)
	ZEND_ARG_INFO(0, class)
	ZEND_ARG_INFO(0, method)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_INFO_EX(arginfo_zendframework_di_definition_arraydefinition_getmethods, 0, 0, 1)
	ZEND_ARG_INFO(0, class)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_INFO_EX(arginfo_zendframework_di_definition_arraydefinition_hasmethodparameters, 0, 0, 2)
	ZEND_ARG_INFO(0, class)
	ZEND_ARG_INFO(0, method)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_INFO_EX(arginfo_zendframework_di_definition_arraydefinition_getmethodparameters, 0, 0, 2)
	ZEND_ARG_INFO(0, class)
	ZEND_ARG_INFO(0, method)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(zendframework_di_definition_arraydefinition_method_entry) {
	PHP_ME(ZendFramework_Di_Definition_ArrayDefinition, __construct, arginfo_zendframework_di_definition_arraydefinition___construct, ZEND_ACC_PUBLIC|ZEND_ACC_CTOR)
	PHP_ME(ZendFramework_Di_Definition_ArrayDefinition, getClasses, NULL, ZEND_ACC_PUBLIC)
	PHP_ME(ZendFramework_Di_Definition_ArrayDefinition, hasClass, arginfo_zendframework_di_definition_arraydefinition_hasclass, ZEND_ACC_PUBLIC)
	PHP_ME(ZendFramework_Di_Definition_ArrayDefinition, getClassSupertypes, arginfo_zendframework_di_definition_arraydefinition_getclasssupertypes, ZEND_ACC_PUBLIC)
	PHP_ME(ZendFramework_Di_Definition_ArrayDefinition, getInstantiator, arginfo_zendframework_di_definition_arraydefinition_getinstantiator, ZEND_ACC_PUBLIC)
	PHP_ME(ZendFramework_Di_Definition_ArrayDefinition, hasMethods, arginfo_zendframework_di_definition_arraydefinition_hasmethods, ZEND_ACC_PUBLIC)
	PHP_ME(ZendFramework_Di_Definition_ArrayDefinition, hasMethod, arginfo_zendframework_di_definition_arraydefinition_hasmethod, ZEND_ACC_PUBLIC)
	PHP_ME(ZendFramework_Di_Definition_ArrayDefinition, getMethods, arginfo_zendframework_di_definition_arraydefinition_getmethods, ZEND_ACC_PUBLIC)
	PHP_ME(ZendFramework_Di_Definition_ArrayDefinition, hasMethodParameters, arginfo_zendframework_di_definition_arraydefinition_hasmethodparameters, ZEND_ACC_PUBLIC)
	PHP_ME(ZendFramework_Di_Definition_ArrayDefinition, getMethodParameters, arginfo_zendframework_di_definition_arraydefinition_getmethodparameters, ZEND_ACC_PUBLIC)
	PHP_ME(ZendFramework_Di_Definition_ArrayDefinition, toArray, NULL, ZEND_ACC_PUBLIC)
  PHP_FE_END
};
