
extern zend_class_entry *zendframework_di_definition_definitioninterface_ce;

ZEPHIR_INIT_CLASS(ZendFramework_Di_Definition_DefinitionInterface);

ZEND_BEGIN_ARG_INFO_EX(arginfo_zendframework_di_definition_definitioninterface_hasclass, 0, 0, 1)
	ZEND_ARG_INFO(0, class)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_INFO_EX(arginfo_zendframework_di_definition_definitioninterface_getclasssupertypes, 0, 0, 1)
	ZEND_ARG_INFO(0, class)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_INFO_EX(arginfo_zendframework_di_definition_definitioninterface_getinstantiator, 0, 0, 1)
	ZEND_ARG_INFO(0, class)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_INFO_EX(arginfo_zendframework_di_definition_definitioninterface_hasmethods, 0, 0, 1)
	ZEND_ARG_INFO(0, class)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_INFO_EX(arginfo_zendframework_di_definition_definitioninterface_getmethods, 0, 0, 1)
	ZEND_ARG_INFO(0, class)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_INFO_EX(arginfo_zendframework_di_definition_definitioninterface_hasmethod, 0, 0, 2)
	ZEND_ARG_INFO(0, class)
	ZEND_ARG_INFO(0, method)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_INFO_EX(arginfo_zendframework_di_definition_definitioninterface_hasmethodparameters, 0, 0, 2)
	ZEND_ARG_INFO(0, class)
	ZEND_ARG_INFO(0, method)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_INFO_EX(arginfo_zendframework_di_definition_definitioninterface_getmethodparameters, 0, 0, 2)
	ZEND_ARG_INFO(0, class)
	ZEND_ARG_INFO(0, method)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(zendframework_di_definition_definitioninterface_method_entry) {
	PHP_ABSTRACT_ME(ZendFramework_Di_Definition_DefinitionInterface, getClasses, NULL)
	PHP_ABSTRACT_ME(ZendFramework_Di_Definition_DefinitionInterface, hasClass, arginfo_zendframework_di_definition_definitioninterface_hasclass)
	PHP_ABSTRACT_ME(ZendFramework_Di_Definition_DefinitionInterface, getClassSupertypes, arginfo_zendframework_di_definition_definitioninterface_getclasssupertypes)
	PHP_ABSTRACT_ME(ZendFramework_Di_Definition_DefinitionInterface, getInstantiator, arginfo_zendframework_di_definition_definitioninterface_getinstantiator)
	PHP_ABSTRACT_ME(ZendFramework_Di_Definition_DefinitionInterface, hasMethods, arginfo_zendframework_di_definition_definitioninterface_hasmethods)
	PHP_ABSTRACT_ME(ZendFramework_Di_Definition_DefinitionInterface, getMethods, arginfo_zendframework_di_definition_definitioninterface_getmethods)
	PHP_ABSTRACT_ME(ZendFramework_Di_Definition_DefinitionInterface, hasMethod, arginfo_zendframework_di_definition_definitioninterface_hasmethod)
	PHP_ABSTRACT_ME(ZendFramework_Di_Definition_DefinitionInterface, hasMethodParameters, arginfo_zendframework_di_definition_definitioninterface_hasmethodparameters)
	PHP_ABSTRACT_ME(ZendFramework_Di_Definition_DefinitionInterface, getMethodParameters, arginfo_zendframework_di_definition_definitioninterface_getmethodparameters)
  PHP_FE_END
};
