
extern zend_class_entry *zendframework_mvc_responsesender_responsesenderinterface_ce;

ZEPHIR_INIT_CLASS(ZendFramework_Mvc_ResponseSender_ResponseSenderInterface);

ZEND_BEGIN_ARG_INFO_EX(arginfo_zendframework_mvc_responsesender_responsesenderinterface___invoke, 0, 0, 1)
	ZEND_ARG_INFO(0, event)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(zendframework_mvc_responsesender_responsesenderinterface_method_entry) {
	PHP_ABSTRACT_ME(ZendFramework_Mvc_ResponseSender_ResponseSenderInterface, __invoke, arginfo_zendframework_mvc_responsesender_responsesenderinterface___invoke)
  PHP_FE_END
};
