
extern zend_class_entry *zendframework_session_config_configinterface_ce;

ZEPHIR_INIT_CLASS(ZendFramework_Session_Config_ConfigInterface);

ZEND_BEGIN_ARG_INFO_EX(arginfo_zendframework_session_config_configinterface_setoptions, 0, 0, 1)
	ZEND_ARG_INFO(0, options)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_INFO_EX(arginfo_zendframework_session_config_configinterface_setoption, 0, 0, 2)
	ZEND_ARG_INFO(0, option)
	ZEND_ARG_INFO(0, value)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_INFO_EX(arginfo_zendframework_session_config_configinterface_getoption, 0, 0, 1)
	ZEND_ARG_INFO(0, option)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_INFO_EX(arginfo_zendframework_session_config_configinterface_hasoption, 0, 0, 1)
	ZEND_ARG_INFO(0, option)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_INFO_EX(arginfo_zendframework_session_config_configinterface_setname, 0, 0, 1)
	ZEND_ARG_INFO(0, name)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_INFO_EX(arginfo_zendframework_session_config_configinterface_setsavepath, 0, 0, 1)
	ZEND_ARG_INFO(0, savePath)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_INFO_EX(arginfo_zendframework_session_config_configinterface_setcookielifetime, 0, 0, 1)
	ZEND_ARG_INFO(0, cookieLifetime)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_INFO_EX(arginfo_zendframework_session_config_configinterface_setcookiepath, 0, 0, 1)
	ZEND_ARG_INFO(0, cookiePath)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_INFO_EX(arginfo_zendframework_session_config_configinterface_setcookiedomain, 0, 0, 1)
	ZEND_ARG_INFO(0, cookieDomain)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_INFO_EX(arginfo_zendframework_session_config_configinterface_setcookiesecure, 0, 0, 1)
	ZEND_ARG_INFO(0, cookieSecure)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_INFO_EX(arginfo_zendframework_session_config_configinterface_setcookiehttponly, 0, 0, 1)
	ZEND_ARG_INFO(0, cookieHttpOnly)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_INFO_EX(arginfo_zendframework_session_config_configinterface_setusecookies, 0, 0, 1)
	ZEND_ARG_INFO(0, useCookies)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_INFO_EX(arginfo_zendframework_session_config_configinterface_setremembermeseconds, 0, 0, 1)
	ZEND_ARG_INFO(0, rememberMeSeconds)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(zendframework_session_config_configinterface_method_entry) {
	PHP_ABSTRACT_ME(ZendFramework_Session_Config_ConfigInterface, setOptions, arginfo_zendframework_session_config_configinterface_setoptions)
	PHP_ABSTRACT_ME(ZendFramework_Session_Config_ConfigInterface, getOptions, NULL)
	PHP_ABSTRACT_ME(ZendFramework_Session_Config_ConfigInterface, setOption, arginfo_zendframework_session_config_configinterface_setoption)
	PHP_ABSTRACT_ME(ZendFramework_Session_Config_ConfigInterface, getOption, arginfo_zendframework_session_config_configinterface_getoption)
	PHP_ABSTRACT_ME(ZendFramework_Session_Config_ConfigInterface, hasOption, arginfo_zendframework_session_config_configinterface_hasoption)
	PHP_ABSTRACT_ME(ZendFramework_Session_Config_ConfigInterface, toArray, NULL)
	PHP_ABSTRACT_ME(ZendFramework_Session_Config_ConfigInterface, setName, arginfo_zendframework_session_config_configinterface_setname)
	PHP_ABSTRACT_ME(ZendFramework_Session_Config_ConfigInterface, getName, NULL)
	PHP_ABSTRACT_ME(ZendFramework_Session_Config_ConfigInterface, setSavePath, arginfo_zendframework_session_config_configinterface_setsavepath)
	PHP_ABSTRACT_ME(ZendFramework_Session_Config_ConfigInterface, getSavePath, NULL)
	PHP_ABSTRACT_ME(ZendFramework_Session_Config_ConfigInterface, setCookieLifetime, arginfo_zendframework_session_config_configinterface_setcookielifetime)
	PHP_ABSTRACT_ME(ZendFramework_Session_Config_ConfigInterface, getCookieLifetime, NULL)
	PHP_ABSTRACT_ME(ZendFramework_Session_Config_ConfigInterface, setCookiePath, arginfo_zendframework_session_config_configinterface_setcookiepath)
	PHP_ABSTRACT_ME(ZendFramework_Session_Config_ConfigInterface, getCookiePath, NULL)
	PHP_ABSTRACT_ME(ZendFramework_Session_Config_ConfigInterface, setCookieDomain, arginfo_zendframework_session_config_configinterface_setcookiedomain)
	PHP_ABSTRACT_ME(ZendFramework_Session_Config_ConfigInterface, getCookieDomain, NULL)
	PHP_ABSTRACT_ME(ZendFramework_Session_Config_ConfigInterface, setCookieSecure, arginfo_zendframework_session_config_configinterface_setcookiesecure)
	PHP_ABSTRACT_ME(ZendFramework_Session_Config_ConfigInterface, getCookieSecure, NULL)
	PHP_ABSTRACT_ME(ZendFramework_Session_Config_ConfigInterface, setCookieHttpOnly, arginfo_zendframework_session_config_configinterface_setcookiehttponly)
	PHP_ABSTRACT_ME(ZendFramework_Session_Config_ConfigInterface, getCookieHttpOnly, NULL)
	PHP_ABSTRACT_ME(ZendFramework_Session_Config_ConfigInterface, setUseCookies, arginfo_zendframework_session_config_configinterface_setusecookies)
	PHP_ABSTRACT_ME(ZendFramework_Session_Config_ConfigInterface, getUseCookies, NULL)
	PHP_ABSTRACT_ME(ZendFramework_Session_Config_ConfigInterface, setRememberMeSeconds, arginfo_zendframework_session_config_configinterface_setremembermeseconds)
	PHP_ABSTRACT_ME(ZendFramework_Session_Config_ConfigInterface, getRememberMeSeconds, NULL)
  PHP_FE_END
};
