
extern zend_class_entry *zendframework_code_annotation_annotationcollection_ce;

ZEPHIR_INIT_CLASS(ZendFramework_Code_Annotation_AnnotationCollection);

PHP_METHOD(ZendFramework_Code_Annotation_AnnotationCollection, hasAnnotation);

ZEND_BEGIN_ARG_INFO_EX(arginfo_zendframework_code_annotation_annotationcollection_hasannotation, 0, 0, 1)
	ZEND_ARG_INFO(0, class)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(zendframework_code_annotation_annotationcollection_method_entry) {
	PHP_ME(ZendFramework_Code_Annotation_AnnotationCollection, hasAnnotation, arginfo_zendframework_code_annotation_annotationcollection_hasannotation, ZEND_ACC_PUBLIC)
  PHP_FE_END
};
