
extern zend_class_entry *zendframework_code_annotation_annotationmanager_ce;

ZEPHIR_INIT_CLASS(ZendFramework_Code_Annotation_AnnotationManager);

PHP_METHOD(ZendFramework_Code_Annotation_AnnotationManager, setEventManager);
PHP_METHOD(ZendFramework_Code_Annotation_AnnotationManager, getEventManager);
PHP_METHOD(ZendFramework_Code_Annotation_AnnotationManager, attach);
PHP_METHOD(ZendFramework_Code_Annotation_AnnotationManager, createAnnotation);
PHP_METHOD(ZendFramework_Code_Annotation_AnnotationManager, _eventCallaback);

ZEND_BEGIN_ARG_INFO_EX(arginfo_zendframework_code_annotation_annotationmanager_seteventmanager, 0, 0, 1)
	ZEND_ARG_OBJ_INFO(0, events, ZendFramework\\EventManager\\EventManagerInterface, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_INFO_EX(arginfo_zendframework_code_annotation_annotationmanager_attach, 0, 0, 1)
	ZEND_ARG_OBJ_INFO(0, parser, ZendFramework\\Code\\Annotation\\Parser\\ParserInterface, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_INFO_EX(arginfo_zendframework_code_annotation_annotationmanager_createannotation, 0, 0, 1)
	ZEND_ARG_ARRAY_INFO(0, annotationData, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_INFO_EX(arginfo_zendframework_code_annotation_annotationmanager__eventcallaback, 0, 0, 1)
	ZEND_ARG_INFO(0, v)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(zendframework_code_annotation_annotationmanager_method_entry) {
	PHP_ME(ZendFramework_Code_Annotation_AnnotationManager, setEventManager, arginfo_zendframework_code_annotation_annotationmanager_seteventmanager, ZEND_ACC_PUBLIC)
	PHP_ME(ZendFramework_Code_Annotation_AnnotationManager, getEventManager, NULL, ZEND_ACC_PUBLIC)
	PHP_ME(ZendFramework_Code_Annotation_AnnotationManager, attach, arginfo_zendframework_code_annotation_annotationmanager_attach, ZEND_ACC_PUBLIC)
	PHP_ME(ZendFramework_Code_Annotation_AnnotationManager, createAnnotation, arginfo_zendframework_code_annotation_annotationmanager_createannotation, ZEND_ACC_PUBLIC)
	PHP_ME(ZendFramework_Code_Annotation_AnnotationManager, _eventCallaback, arginfo_zendframework_code_annotation_annotationmanager__eventcallaback, ZEND_ACC_PRIVATE)
  PHP_FE_END
};
