
extern zend_class_entry *zendframework_di_definition_builder_injectionmethod_ce;

ZEPHIR_INIT_CLASS(ZendFramework_Di_Definition_Builder_InjectionMethod);

PHP_METHOD(ZendFramework_Di_Definition_Builder_InjectionMethod, setName);
PHP_METHOD(ZendFramework_Di_Definition_Builder_InjectionMethod, getName);
PHP_METHOD(ZendFramework_Di_Definition_Builder_InjectionMethod, addParameter);
PHP_METHOD(ZendFramework_Di_Definition_Builder_InjectionMethod, getParameters);
PHP_METHOD(ZendFramework_Di_Definition_Builder_InjectionMethod, detectMethodRequirement);
PHP_METHOD(ZendFramework_Di_Definition_Builder_InjectionMethod, __construct);

ZEND_BEGIN_ARG_INFO_EX(arginfo_zendframework_di_definition_builder_injectionmethod_setname, 0, 0, 1)
	ZEND_ARG_INFO(0, name)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_INFO_EX(arginfo_zendframework_di_definition_builder_injectionmethod_addparameter, 0, 0, 1)
	ZEND_ARG_INFO(0, name)
	ZEND_ARG_INFO(0, class)
	ZEND_ARG_INFO(0, isRequired)
	ZEND_ARG_INFO(0, defaultVal)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_INFO_EX(arginfo_zendframework_di_definition_builder_injectionmethod_detectmethodrequirement, 0, 0, 1)
	ZEND_ARG_INFO(0, requirement)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(zendframework_di_definition_builder_injectionmethod_method_entry) {
	PHP_ME(ZendFramework_Di_Definition_Builder_InjectionMethod, setName, arginfo_zendframework_di_definition_builder_injectionmethod_setname, ZEND_ACC_PUBLIC)
	PHP_ME(ZendFramework_Di_Definition_Builder_InjectionMethod, getName, NULL, ZEND_ACC_PUBLIC)
	PHP_ME(ZendFramework_Di_Definition_Builder_InjectionMethod, addParameter, arginfo_zendframework_di_definition_builder_injectionmethod_addparameter, ZEND_ACC_PUBLIC)
	PHP_ME(ZendFramework_Di_Definition_Builder_InjectionMethod, getParameters, NULL, ZEND_ACC_PUBLIC)
	PHP_ME(ZendFramework_Di_Definition_Builder_InjectionMethod, detectMethodRequirement, arginfo_zendframework_di_definition_builder_injectionmethod_detectmethodrequirement, ZEND_ACC_PUBLIC|ZEND_ACC_STATIC)
	PHP_ME(ZendFramework_Di_Definition_Builder_InjectionMethod, __construct, NULL, ZEND_ACC_PUBLIC|ZEND_ACC_CTOR)
  PHP_FE_END
};
