
extern zend_class_entry *zendframework_eventmanager_abstractlisteneraggregate_ce;

ZEPHIR_INIT_CLASS(ZendFramework_EventManager_AbstractListenerAggregate);

PHP_METHOD(ZendFramework_EventManager_AbstractListenerAggregate, detach);
PHP_METHOD(ZendFramework_EventManager_AbstractListenerAggregate, __construct);

ZEND_BEGIN_ARG_INFO_EX(arginfo_zendframework_eventmanager_abstractlisteneraggregate_detach, 0, 0, 1)
	ZEND_ARG_OBJ_INFO(0, events, ZendFramework\\EventManager\\EventManagerInterface, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(zendframework_eventmanager_abstractlisteneraggregate_method_entry) {
	PHP_ME(ZendFramework_EventManager_AbstractListenerAggregate, detach, arginfo_zendframework_eventmanager_abstractlisteneraggregate_detach, ZEND_ACC_PUBLIC)
	PHP_ME(ZendFramework_EventManager_AbstractListenerAggregate, __construct, NULL, ZEND_ACC_PUBLIC|ZEND_ACC_CTOR)
  PHP_FE_END
};
