
extern zend_class_entry *zendframework_eventmanager_listeneraggregateinterface_ce;

ZEPHIR_INIT_CLASS(ZendFramework_EventManager_ListenerAggregateInterface);

ZEND_BEGIN_ARG_INFO_EX(arginfo_zendframework_eventmanager_listeneraggregateinterface_attach, 0, 0, 1)
	ZEND_ARG_OBJ_INFO(0, events, ZendFramework\\EventManager\\EventManagerInterface, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_INFO_EX(arginfo_zendframework_eventmanager_listeneraggregateinterface_detach, 0, 0, 1)
	ZEND_ARG_OBJ_INFO(0, events, ZendFramework\\EventManager\\EventManagerInterface, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(zendframework_eventmanager_listeneraggregateinterface_method_entry) {
	PHP_ABSTRACT_ME(ZendFramework_EventManager_ListenerAggregateInterface, attach, arginfo_zendframework_eventmanager_listeneraggregateinterface_attach)
	PHP_ABSTRACT_ME(ZendFramework_EventManager_ListenerAggregateInterface, detach, arginfo_zendframework_eventmanager_listeneraggregateinterface_detach)
  PHP_FE_END
};
