
extern zend_class_entry *zendframework_eventmanager_sharedlisteneraggregateinterface_ce;

ZEPHIR_INIT_CLASS(ZendFramework_EventManager_SharedListenerAggregateInterface);

ZEND_BEGIN_ARG_INFO_EX(arginfo_zendframework_eventmanager_sharedlisteneraggregateinterface_attachshared, 0, 0, 1)
	ZEND_ARG_OBJ_INFO(0, events, ZendFramework\\EventManager\\SharedEventManagerInterface, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_INFO_EX(arginfo_zendframework_eventmanager_sharedlisteneraggregateinterface_detachshared, 0, 0, 1)
	ZEND_ARG_OBJ_INFO(0, events, ZendFramework\\EventManager\\SharedEventManagerInterface, 0)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(zendframework_eventmanager_sharedlisteneraggregateinterface_method_entry) {
	PHP_ABSTRACT_ME(ZendFramework_EventManager_SharedListenerAggregateInterface, attachShared, arginfo_zendframework_eventmanager_sharedlisteneraggregateinterface_attachshared)
	PHP_ABSTRACT_ME(ZendFramework_EventManager_SharedListenerAggregateInterface, detachShared, arginfo_zendframework_eventmanager_sharedlisteneraggregateinterface_detachshared)
  PHP_FE_END
};
