
extern zend_class_entry *zendframework_serializer_adapter_adapterinterface_ce;

ZEPHIR_INIT_CLASS(ZendFramework_Serializer_Adapter_AdapterInterface);

ZEND_BEGIN_ARG_INFO_EX(arginfo_zendframework_serializer_adapter_adapterinterface_serialize, 0, 0, 1)
	ZEND_ARG_INFO(0, value)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_INFO_EX(arginfo_zendframework_serializer_adapter_adapterinterface_unserialize, 0, 0, 1)
	ZEND_ARG_INFO(0, serialized)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(zendframework_serializer_adapter_adapterinterface_method_entry) {
	PHP_ABSTRACT_ME(ZendFramework_Serializer_Adapter_AdapterInterface, serialize, arginfo_zendframework_serializer_adapter_adapterinterface_serialize)
	PHP_ABSTRACT_ME(ZendFramework_Serializer_Adapter_AdapterInterface, unserialize, arginfo_zendframework_serializer_adapter_adapterinterface_unserialize)
  PHP_FE_END
};
