
extern zend_class_entry *zendframework_db_rowgateway_rowgatewayinterface_ce;

ZEPHIR_INIT_CLASS(ZendFramework_Db_RowGateway_RowGatewayInterface);

ZEPHIR_INIT_FUNCS(zendframework_db_rowgateway_rowgatewayinterface_method_entry) {
	PHP_ABSTRACT_ME(ZendFramework_Db_RowGateway_RowGatewayInterface, save, NULL)
	PHP_ABSTRACT_ME(ZendFramework_Db_RowGateway_RowGatewayInterface, delete, NULL)
  PHP_FE_END
};
