
extern zend_class_entry *zendframework_tag_cloud_decorator_decoratorinterface_ce;

ZEPHIR_INIT_CLASS(ZendFramework_Tag_Cloud_Decorator_DecoratorInterface);

ZEND_BEGIN_ARG_INFO_EX(arginfo_zendframework_tag_cloud_decorator_decoratorinterface___construct, 0, 0, 0)
	ZEND_ARG_INFO(0, options)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_INFO_EX(arginfo_zendframework_tag_cloud_decorator_decoratorinterface_render, 0, 0, 1)
	ZEND_ARG_INFO(0, tags)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(zendframework_tag_cloud_decorator_decoratorinterface_method_entry) {
	PHP_ABSTRACT_ME(ZendFramework_Tag_Cloud_Decorator_DecoratorInterface, __construct, arginfo_zendframework_tag_cloud_decorator_decoratorinterface___construct)
	PHP_ABSTRACT_ME(ZendFramework_Tag_Cloud_Decorator_DecoratorInterface, render, arginfo_zendframework_tag_cloud_decorator_decoratorinterface_render)
  PHP_FE_END
};
