
extern zend_class_entry *zendframework_session_storage_storageinitializationinterface_ce;

ZEPHIR_INIT_CLASS(ZendFramework_Session_Storage_StorageInitializationInterface);

ZEND_BEGIN_ARG_INFO_EX(arginfo_zendframework_session_storage_storageinitializationinterface_init, 0, 0, 0)
	ZEND_ARG_ARRAY_INFO(0, input, 1)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(zendframework_session_storage_storageinitializationinterface_method_entry) {
	PHP_ABSTRACT_ME(ZendFramework_Session_Storage_StorageInitializationInterface, init, arginfo_zendframework_session_storage_storageinitializationinterface_init)
  PHP_FE_END
};
