
extern zend_class_entry *zendframework_validator_validatorinterface_ce;

ZEPHIR_INIT_CLASS(ZendFramework_Validator_ValidatorInterface);

ZEND_BEGIN_ARG_INFO_EX(arginfo_zendframework_validator_validatorinterface_isvalid, 0, 0, 1)
	ZEND_ARG_INFO(0, value)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(zendframework_validator_validatorinterface_method_entry) {
	PHP_ABSTRACT_ME(ZendFramework_Validator_ValidatorInterface, isValid, arginfo_zendframework_validator_validatorinterface_isvalid)
	PHP_ABSTRACT_ME(ZendFramework_Validator_ValidatorInterface, getMessages, NULL)
  PHP_FE_END
};
