
extern zend_class_entry *zendframework_authentication_authenticationserviceinterface_ce;

ZEPHIR_INIT_CLASS(ZendFramework_Authentication_AuthenticationServiceInterface);

ZEPHIR_INIT_FUNCS(zendframework_authentication_authenticationserviceinterface_method_entry) {
	PHP_ABSTRACT_ME(ZendFramework_Authentication_AuthenticationServiceInterface, authenticate, NULL)
	PHP_ABSTRACT_ME(ZendFramework_Authentication_AuthenticationServiceInterface, hasIdentity, NULL)
	PHP_ABSTRACT_ME(ZendFramework_Authentication_AuthenticationServiceInterface, getIdentity, NULL)
	PHP_ABSTRACT_ME(ZendFramework_Authentication_AuthenticationServiceInterface, clearIdentity, NULL)
  PHP_FE_END
};
