
extern zend_class_entry *zendframework_paginator_scrollingstyle_scrollingstyleinterface_ce;

ZEPHIR_INIT_CLASS(ZendFramework_Paginator_ScrollingStyle_ScrollingStyleInterface);

ZEND_BEGIN_ARG_INFO_EX(arginfo_zendframework_paginator_scrollingstyle_scrollingstyleinterface_getpages, 0, 0, 1)
	ZEND_ARG_INFO(0, paginator)
	ZEND_ARG_INFO(0, pageRange)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(zendframework_paginator_scrollingstyle_scrollingstyleinterface_method_entry) {
	PHP_ABSTRACT_ME(ZendFramework_Paginator_ScrollingStyle_ScrollingStyleInterface, getPages, arginfo_zendframework_paginator_scrollingstyle_scrollingstyleinterface_getpages)
  PHP_FE_END
};
