
extern zend_class_entry *zendframework_db_sql_ddl_column_columninterface_ce;

ZEPHIR_INIT_CLASS(ZendFramework_Db_Sql_Ddl_Column_ColumnInterface);

ZEPHIR_INIT_FUNCS(zendframework_db_sql_ddl_column_columninterface_method_entry) {
	PHP_ABSTRACT_ME(ZendFramework_Db_Sql_Ddl_Column_ColumnInterface, getName, NULL)
	PHP_ABSTRACT_ME(ZendFramework_Db_Sql_Ddl_Column_ColumnInterface, isNullable, NULL)
	PHP_ABSTRACT_ME(ZendFramework_Db_Sql_Ddl_Column_ColumnInterface, getDefault, NULL)
	PHP_ABSTRACT_ME(ZendFramework_Db_Sql_Ddl_Column_ColumnInterface, getOptions, NULL)
  PHP_FE_END
};
