
extern zend_class_entry *zendframework_permissions_acl_assertion_exception_invalidassertionexception_ce;

ZEPHIR_INIT_CLASS(ZendFramework_Permissions_Acl_Assertion_Exception_InvalidAssertionException);

